// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: TPCommandArchives.sos.proto

package TP

import (
	TSA "github.com/orcastor/iwork-converter/proto/TSA"
	TSK "github.com/orcastor/iwork-converter/proto/TSK"
	TSP "github.com/orcastor/iwork-converter/proto/TSP"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InducedVerifyDocumentWithServerCommandArchive struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	Super                        *TSK.CommandArchive    `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	DrawablesZOrderList          []*TSP.UUID            `protobuf:"bytes,2,rep,name=drawables_z_order_list,json=drawablesZOrderList" json:"drawables_z_order_list,omitempty"`
	DrawablesZOrderListUndefined *bool                  `protobuf:"varint,3,opt,name=drawables_z_order_list_undefined,json=drawablesZOrderListUndefined" json:"drawables_z_order_list_undefined,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *InducedVerifyDocumentWithServerCommandArchive) Reset() {
	*x = InducedVerifyDocumentWithServerCommandArchive{}
	mi := &file_TPCommandArchives_sos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InducedVerifyDocumentWithServerCommandArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InducedVerifyDocumentWithServerCommandArchive) ProtoMessage() {}

func (x *InducedVerifyDocumentWithServerCommandArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TPCommandArchives_sos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InducedVerifyDocumentWithServerCommandArchive.ProtoReflect.Descriptor instead.
func (*InducedVerifyDocumentWithServerCommandArchive) Descriptor() ([]byte, []int) {
	return file_TPCommandArchives_sos_proto_rawDescGZIP(), []int{0}
}

func (x *InducedVerifyDocumentWithServerCommandArchive) GetSuper() *TSK.CommandArchive {
	if x != nil {
		return x.Super
	}
	return nil
}

func (x *InducedVerifyDocumentWithServerCommandArchive) GetDrawablesZOrderList() []*TSP.UUID {
	if x != nil {
		return x.DrawablesZOrderList
	}
	return nil
}

func (x *InducedVerifyDocumentWithServerCommandArchive) GetDrawablesZOrderListUndefined() bool {
	if x != nil && x.DrawablesZOrderListUndefined != nil {
		return *x.DrawablesZOrderListUndefined
	}
	return false
}

type InducedVerifyDrawableZOrdersWithServerCommandArchive struct {
	state         protoimpl.MessageState                                    `protogen:"open.v1"`
	Super         *TSA.InducedVerifyDrawableZOrdersWithServerCommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InducedVerifyDrawableZOrdersWithServerCommandArchive) Reset() {
	*x = InducedVerifyDrawableZOrdersWithServerCommandArchive{}
	mi := &file_TPCommandArchives_sos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InducedVerifyDrawableZOrdersWithServerCommandArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InducedVerifyDrawableZOrdersWithServerCommandArchive) ProtoMessage() {}

func (x *InducedVerifyDrawableZOrdersWithServerCommandArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TPCommandArchives_sos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InducedVerifyDrawableZOrdersWithServerCommandArchive.ProtoReflect.Descriptor instead.
func (*InducedVerifyDrawableZOrdersWithServerCommandArchive) Descriptor() ([]byte, []int) {
	return file_TPCommandArchives_sos_proto_rawDescGZIP(), []int{1}
}

func (x *InducedVerifyDrawableZOrdersWithServerCommandArchive) GetSuper() *TSA.InducedVerifyDrawableZOrdersWithServerCommandArchive {
	if x != nil {
		return x.Super
	}
	return nil
}

type ReapplyPageTemplateCommandArchive struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Super         *TSA.CommandReapplyMasterArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReapplyPageTemplateCommandArchive) Reset() {
	*x = ReapplyPageTemplateCommandArchive{}
	mi := &file_TPCommandArchives_sos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReapplyPageTemplateCommandArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReapplyPageTemplateCommandArchive) ProtoMessage() {}

func (x *ReapplyPageTemplateCommandArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TPCommandArchives_sos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReapplyPageTemplateCommandArchive.ProtoReflect.Descriptor instead.
func (*ReapplyPageTemplateCommandArchive) Descriptor() ([]byte, []int) {
	return file_TPCommandArchives_sos_proto_rawDescGZIP(), []int{2}
}

func (x *ReapplyPageTemplateCommandArchive) GetSuper() *TSA.CommandReapplyMasterArchive {
	if x != nil {
		return x.Super
	}
	return nil
}

var File_TPCommandArchives_sos_proto protoreflect.FileDescriptor

const file_TPCommandArchives_sos_proto_rawDesc = "" +
	"\n" +
	"\x1bTPCommandArchives.sos.proto\x12\x02TP\x1a\x1cTSACommandArchives.sos.proto\x1a\x11TSKArchives.proto\x1a\x11TSPMessages.proto\"\xe2\x01\n" +
	"-InducedVerifyDocumentWithServerCommandArchive\x12)\n" +
	"\x05super\x18\x01 \x02(\v2\x13.TSK.CommandArchiveR\x05super\x12>\n" +
	"\x16drawables_z_order_list\x18\x02 \x03(\v2\t.TSP.UUIDR\x13drawablesZOrderList\x12F\n" +
	" drawables_z_order_list_undefined\x18\x03 \x01(\bR\x1cdrawablesZOrderListUndefined\"\x87\x01\n" +
	"4InducedVerifyDrawableZOrdersWithServerCommandArchive\x12O\n" +
	"\x05super\x18\x01 \x02(\v29.TSA.InducedVerifyDrawableZOrdersWithServerCommandArchiveR\x05super\"[\n" +
	"!ReapplyPageTemplateCommandArchive\x126\n" +
	"\x05super\x18\x01 \x02(\v2 .TSA.CommandReapplyMasterArchiveR\x05superB.Z,github.com/orcastor/iwork-converter/proto/TP"

var (
	file_TPCommandArchives_sos_proto_rawDescOnce sync.Once
	file_TPCommandArchives_sos_proto_rawDescData []byte
)

func file_TPCommandArchives_sos_proto_rawDescGZIP() []byte {
	file_TPCommandArchives_sos_proto_rawDescOnce.Do(func() {
		file_TPCommandArchives_sos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_TPCommandArchives_sos_proto_rawDesc), len(file_TPCommandArchives_sos_proto_rawDesc)))
	})
	return file_TPCommandArchives_sos_proto_rawDescData
}

var file_TPCommandArchives_sos_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_TPCommandArchives_sos_proto_goTypes = []any{
	(*InducedVerifyDocumentWithServerCommandArchive)(nil),            // 0: TP.InducedVerifyDocumentWithServerCommandArchive
	(*InducedVerifyDrawableZOrdersWithServerCommandArchive)(nil),     // 1: TP.InducedVerifyDrawableZOrdersWithServerCommandArchive
	(*ReapplyPageTemplateCommandArchive)(nil),                        // 2: TP.ReapplyPageTemplateCommandArchive
	(*TSK.CommandArchive)(nil),                                       // 3: TSK.CommandArchive
	(*TSP.UUID)(nil),                                                 // 4: TSP.UUID
	(*TSA.InducedVerifyDrawableZOrdersWithServerCommandArchive)(nil), // 5: TSA.InducedVerifyDrawableZOrdersWithServerCommandArchive
	(*TSA.CommandReapplyMasterArchive)(nil),                          // 6: TSA.CommandReapplyMasterArchive
}
var file_TPCommandArchives_sos_proto_depIdxs = []int32{
	3, // 0: TP.InducedVerifyDocumentWithServerCommandArchive.super:type_name -> TSK.CommandArchive
	4, // 1: TP.InducedVerifyDocumentWithServerCommandArchive.drawables_z_order_list:type_name -> TSP.UUID
	5, // 2: TP.InducedVerifyDrawableZOrdersWithServerCommandArchive.super:type_name -> TSA.InducedVerifyDrawableZOrdersWithServerCommandArchive
	6, // 3: TP.ReapplyPageTemplateCommandArchive.super:type_name -> TSA.CommandReapplyMasterArchive
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_TPCommandArchives_sos_proto_init() }
func file_TPCommandArchives_sos_proto_init() {
	if File_TPCommandArchives_sos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_TPCommandArchives_sos_proto_rawDesc), len(file_TPCommandArchives_sos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TPCommandArchives_sos_proto_goTypes,
		DependencyIndexes: file_TPCommandArchives_sos_proto_depIdxs,
		MessageInfos:      file_TPCommandArchives_sos_proto_msgTypes,
	}.Build()
	File_TPCommandArchives_sos_proto = out.File
	file_TPCommandArchives_sos_proto_goTypes = nil
	file_TPCommandArchives_sos_proto_depIdxs = nil
}
