// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: TSCH3DArchives.proto

package TSCH

import (
	_ "github.com/orcastor/iwork-converter/proto/TSD"
	TSP "github.com/orcastor/iwork-converter/proto/TSP"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TextureTilingMode int32

const (
	TextureTilingMode_textureTilingModeNone    TextureTilingMode = 0
	TextureTilingMode_textureTilingModeTallest TextureTilingMode = 1
)

// Enum value maps for TextureTilingMode.
var (
	TextureTilingMode_name = map[int32]string{
		0: "textureTilingModeNone",
		1: "textureTilingModeTallest",
	}
	TextureTilingMode_value = map[string]int32{
		"textureTilingModeNone":    0,
		"textureTilingModeTallest": 1,
	}
)

func (x TextureTilingMode) Enum() *TextureTilingMode {
	p := new(TextureTilingMode)
	*p = x
	return p
}

func (x TextureTilingMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TextureTilingMode) Descriptor() protoreflect.EnumDescriptor {
	return file_TSCH3DArchives_proto_enumTypes[0].Descriptor()
}

func (TextureTilingMode) Type() protoreflect.EnumType {
	return &file_TSCH3DArchives_proto_enumTypes[0]
}

func (x TextureTilingMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *TextureTilingMode) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = TextureTilingMode(num)
	return nil
}

// Deprecated: Use TextureTilingMode.Descriptor instead.
func (TextureTilingMode) EnumDescriptor() ([]byte, []int) {
	return file_TSCH3DArchives_proto_rawDescGZIP(), []int{0}
}

type TextureTilingFace int32

const (
	TextureTilingFace_textureTilingFaceAll          TextureTilingFace = 0
	TextureTilingFace_textureTilingFaceTopAndBottom TextureTilingFace = 1
	TextureTilingFace_textureTilingFaceSide         TextureTilingFace = 2
)

// Enum value maps for TextureTilingFace.
var (
	TextureTilingFace_name = map[int32]string{
		0: "textureTilingFaceAll",
		1: "textureTilingFaceTopAndBottom",
		2: "textureTilingFaceSide",
	}
	TextureTilingFace_value = map[string]int32{
		"textureTilingFaceAll":          0,
		"textureTilingFaceTopAndBottom": 1,
		"textureTilingFaceSide":         2,
	}
)

func (x TextureTilingFace) Enum() *TextureTilingFace {
	p := new(TextureTilingFace)
	*p = x
	return p
}

func (x TextureTilingFace) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TextureTilingFace) Descriptor() protoreflect.EnumDescriptor {
	return file_TSCH3DArchives_proto_enumTypes[1].Descriptor()
}

func (TextureTilingFace) Type() protoreflect.EnumType {
	return &file_TSCH3DArchives_proto_enumTypes[1]
}

func (x TextureTilingFace) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *TextureTilingFace) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = TextureTilingFace(num)
	return nil
}

// Deprecated: Use TextureTilingFace.Descriptor instead.
func (TextureTilingFace) EnumDescriptor() ([]byte, []int) {
	return file_TSCH3DArchives_proto_rawDescGZIP(), []int{1}
}

type TextureTilingWrap int32

const (
	TextureTilingWrap_textureTilingWrapProjected TextureTilingWrap = 0
	TextureTilingWrap_textureTilingWrapFaceWrap  TextureTilingWrap = 1
)

// Enum value maps for TextureTilingWrap.
var (
	TextureTilingWrap_name = map[int32]string{
		0: "textureTilingWrapProjected",
		1: "textureTilingWrapFaceWrap",
	}
	TextureTilingWrap_value = map[string]int32{
		"textureTilingWrapProjected": 0,
		"textureTilingWrapFaceWrap":  1,
	}
)

func (x TextureTilingWrap) Enum() *TextureTilingWrap {
	p := new(TextureTilingWrap)
	*p = x
	return p
}

func (x TextureTilingWrap) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TextureTilingWrap) Descriptor() protoreflect.EnumDescriptor {
	return file_TSCH3DArchives_proto_enumTypes[2].Descriptor()
}

func (TextureTilingWrap) Type() protoreflect.EnumType {
	return &file_TSCH3DArchives_proto_enumTypes[2]
}

func (x TextureTilingWrap) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *TextureTilingWrap) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = TextureTilingWrap(num)
	return nil
}

// Deprecated: Use TextureTilingWrap.Descriptor instead.
func (TextureTilingWrap) EnumDescriptor() ([]byte, []int) {
	return file_TSCH3DArchives_proto_rawDescGZIP(), []int{2}
}

type TextureTilingXPosition int32

const (
	TextureTilingXPosition_textureTilingXPositionLeft   TextureTilingXPosition = 0
	TextureTilingXPosition_textureTilingXPositionCenter TextureTilingXPosition = 1
	TextureTilingXPosition_textureTilingXPositionRight  TextureTilingXPosition = 2
)

// Enum value maps for TextureTilingXPosition.
var (
	TextureTilingXPosition_name = map[int32]string{
		0: "textureTilingXPositionLeft",
		1: "textureTilingXPositionCenter",
		2: "textureTilingXPositionRight",
	}
	TextureTilingXPosition_value = map[string]int32{
		"textureTilingXPositionLeft":   0,
		"textureTilingXPositionCenter": 1,
		"textureTilingXPositionRight":  2,
	}
)

func (x TextureTilingXPosition) Enum() *TextureTilingXPosition {
	p := new(TextureTilingXPosition)
	*p = x
	return p
}

func (x TextureTilingXPosition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TextureTilingXPosition) Descriptor() protoreflect.EnumDescriptor {
	return file_TSCH3DArchives_proto_enumTypes[3].Descriptor()
}

func (TextureTilingXPosition) Type() protoreflect.EnumType {
	return &file_TSCH3DArchives_proto_enumTypes[3]
}

func (x TextureTilingXPosition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *TextureTilingXPosition) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = TextureTilingXPosition(num)
	return nil
}

// Deprecated: Use TextureTilingXPosition.Descriptor instead.
func (TextureTilingXPosition) EnumDescriptor() ([]byte, []int) {
	return file_TSCH3DArchives_proto_rawDescGZIP(), []int{3}
}

type TextureTilingYPosition int32

const (
	TextureTilingYPosition_textureTilingYPositionTop    TextureTilingYPosition = 0
	TextureTilingYPosition_textureTilingYPositionMiddle TextureTilingYPosition = 1
	TextureTilingYPosition_textureTilingYPositionBottom TextureTilingYPosition = 2
)

// Enum value maps for TextureTilingYPosition.
var (
	TextureTilingYPosition_name = map[int32]string{
		0: "textureTilingYPositionTop",
		1: "textureTilingYPositionMiddle",
		2: "textureTilingYPositionBottom",
	}
	TextureTilingYPosition_value = map[string]int32{
		"textureTilingYPositionTop":    0,
		"textureTilingYPositionMiddle": 1,
		"textureTilingYPositionBottom": 2,
	}
)

func (x TextureTilingYPosition) Enum() *TextureTilingYPosition {
	p := new(TextureTilingYPosition)
	*p = x
	return p
}

func (x TextureTilingYPosition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TextureTilingYPosition) Descriptor() protoreflect.EnumDescriptor {
	return file_TSCH3DArchives_proto_enumTypes[4].Descriptor()
}

func (TextureTilingYPosition) Type() protoreflect.EnumType {
	return &file_TSCH3DArchives_proto_enumTypes[4]
}

func (x TextureTilingYPosition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *TextureTilingYPosition) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = TextureTilingYPosition(num)
	return nil
}

// Deprecated: Use TextureTilingYPosition.Descriptor instead.
func (TextureTilingYPosition) EnumDescriptor() ([]byte, []int) {
	return file_TSCH3DArchives_proto_rawDescGZIP(), []int{4}
}

type TextureTilingContinuity int32

const (
	TextureTilingContinuity_textureTilingContinuityNone     TextureTilingContinuity = 0
	TextureTilingContinuity_textureTilingContinuityGlobal   TextureTilingContinuity = 1
	TextureTilingContinuity_textureTilingContinuitySeries   TextureTilingContinuity = 2
	TextureTilingContinuity_textureTilingContinuityJittered TextureTilingContinuity = 3
)

// Enum value maps for TextureTilingContinuity.
var (
	TextureTilingContinuity_name = map[int32]string{
		0: "textureTilingContinuityNone",
		1: "textureTilingContinuityGlobal",
		2: "textureTilingContinuitySeries",
		3: "textureTilingContinuityJittered",
	}
	TextureTilingContinuity_value = map[string]int32{
		"textureTilingContinuityNone":     0,
		"textureTilingContinuityGlobal":   1,
		"textureTilingContinuitySeries":   2,
		"textureTilingContinuityJittered": 3,
	}
)

func (x TextureTilingContinuity) Enum() *TextureTilingContinuity {
	p := new(TextureTilingContinuity)
	*p = x
	return p
}

func (x TextureTilingContinuity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TextureTilingContinuity) Descriptor() protoreflect.EnumDescriptor {
	return file_TSCH3DArchives_proto_enumTypes[5].Descriptor()
}

func (TextureTilingContinuity) Type() protoreflect.EnumType {
	return &file_TSCH3DArchives_proto_enumTypes[5]
}

func (x TextureTilingContinuity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *TextureTilingContinuity) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = TextureTilingContinuity(num)
	return nil
}

// Deprecated: Use TextureTilingContinuity.Descriptor instead.
func (TextureTilingContinuity) EnumDescriptor() ([]byte, []int) {
	return file_TSCH3DArchives_proto_rawDescGZIP(), []int{5}
}

type FillPropertyType int32

const (
	FillPropertyType_fillPropertyTypeUndefined FillPropertyType = 0
	FillPropertyType_fillPropertyTypeArea      FillPropertyType = 1
	FillPropertyType_fillPropertyTypeBar       FillPropertyType = 2
	FillPropertyType_fillPropertyTypeColumn    FillPropertyType = 3
	FillPropertyType_fillPropertyTypeLine      FillPropertyType = 4
	FillPropertyType_fillPropertyTypePie       FillPropertyType = 5
)

// Enum value maps for FillPropertyType.
var (
	FillPropertyType_name = map[int32]string{
		0: "fillPropertyTypeUndefined",
		1: "fillPropertyTypeArea",
		2: "fillPropertyTypeBar",
		3: "fillPropertyTypeColumn",
		4: "fillPropertyTypeLine",
		5: "fillPropertyTypePie",
	}
	FillPropertyType_value = map[string]int32{
		"fillPropertyTypeUndefined": 0,
		"fillPropertyTypeArea":      1,
		"fillPropertyTypeBar":       2,
		"fillPropertyTypeColumn":    3,
		"fillPropertyTypeLine":      4,
		"fillPropertyTypePie":       5,
	}
)

func (x FillPropertyType) Enum() *FillPropertyType {
	p := new(FillPropertyType)
	*p = x
	return p
}

func (x FillPropertyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FillPropertyType) Descriptor() protoreflect.EnumDescriptor {
	return file_TSCH3DArchives_proto_enumTypes[6].Descriptor()
}

func (FillPropertyType) Type() protoreflect.EnumType {
	return &file_TSCH3DArchives_proto_enumTypes[6]
}

func (x FillPropertyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *FillPropertyType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = FillPropertyType(num)
	return nil
}

// Deprecated: Use FillPropertyType.Descriptor instead.
func (FillPropertyType) EnumDescriptor() ([]byte, []int) {
	return file_TSCH3DArchives_proto_rawDescGZIP(), []int{6}
}

type Chart3DEnvironmentPackageArchive struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Materials     []*Chart3DEnvironmentMaterialArchive `protobuf:"bytes,1,rep,name=materials" json:"materials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chart3DEnvironmentPackageArchive) Reset() {
	*x = Chart3DEnvironmentPackageArchive{}
	mi := &file_TSCH3DArchives_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chart3DEnvironmentPackageArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chart3DEnvironmentPackageArchive) ProtoMessage() {}

func (x *Chart3DEnvironmentPackageArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSCH3DArchives_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chart3DEnvironmentPackageArchive.ProtoReflect.Descriptor instead.
func (*Chart3DEnvironmentPackageArchive) Descriptor() ([]byte, []int) {
	return file_TSCH3DArchives_proto_rawDescGZIP(), []int{0}
}

func (x *Chart3DEnvironmentPackageArchive) GetMaterials() []*Chart3DEnvironmentMaterialArchive {
	if x != nil {
		return x.Materials
	}
	return nil
}

type Chart3DFillArchive struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Lightingmodel *Chart3DLightingModelArchive `protobuf:"bytes,1,opt,name=lightingmodel" json:"lightingmodel,omitempty"`
	TexturesetId  *string                      `protobuf:"bytes,2,opt,name=textureset_id,json=texturesetId" json:"textureset_id,omitempty"`
	FillType      *FillPropertyType            `protobuf:"varint,3,opt,name=fill_type,json=fillType,enum=TSCH.FillPropertyType" json:"fill_type,omitempty"`
	SeriesIndex   *uint32                      `protobuf:"varint,4,opt,name=series_index,json=seriesIndex" json:"series_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chart3DFillArchive) Reset() {
	*x = Chart3DFillArchive{}
	mi := &file_TSCH3DArchives_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chart3DFillArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chart3DFillArchive) ProtoMessage() {}

func (x *Chart3DFillArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSCH3DArchives_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chart3DFillArchive.ProtoReflect.Descriptor instead.
func (*Chart3DFillArchive) Descriptor() ([]byte, []int) {
	return file_TSCH3DArchives_proto_rawDescGZIP(), []int{1}
}

func (x *Chart3DFillArchive) GetLightingmodel() *Chart3DLightingModelArchive {
	if x != nil {
		return x.Lightingmodel
	}
	return nil
}

func (x *Chart3DFillArchive) GetTexturesetId() string {
	if x != nil && x.TexturesetId != nil {
		return *x.TexturesetId
	}
	return ""
}

func (x *Chart3DFillArchive) GetFillType() FillPropertyType {
	if x != nil && x.FillType != nil {
		return *x.FillType
	}
	return FillPropertyType_fillPropertyTypeUndefined
}

func (x *Chart3DFillArchive) GetSeriesIndex() uint32 {
	if x != nil && x.SeriesIndex != nil {
		return *x.SeriesIndex
	}
	return 0
}

type Chart3DPointLightArchive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *Chart3DVectorArchive  `protobuf:"bytes,1,req,name=position" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chart3DPointLightArchive) Reset() {
	*x = Chart3DPointLightArchive{}
	mi := &file_TSCH3DArchives_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chart3DPointLightArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chart3DPointLightArchive) ProtoMessage() {}

func (x *Chart3DPointLightArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSCH3DArchives_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chart3DPointLightArchive.ProtoReflect.Descriptor instead.
func (*Chart3DPointLightArchive) Descriptor() ([]byte, []int) {
	return file_TSCH3DArchives_proto_rawDescGZIP(), []int{2}
}

func (x *Chart3DPointLightArchive) GetPosition() *Chart3DVectorArchive {
	if x != nil {
		return x.Position
	}
	return nil
}

type Chart3DDirectionalLightArchive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Direction     *Chart3DVectorArchive  `protobuf:"bytes,1,req,name=direction" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chart3DDirectionalLightArchive) Reset() {
	*x = Chart3DDirectionalLightArchive{}
	mi := &file_TSCH3DArchives_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chart3DDirectionalLightArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chart3DDirectionalLightArchive) ProtoMessage() {}

func (x *Chart3DDirectionalLightArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSCH3DArchives_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chart3DDirectionalLightArchive.ProtoReflect.Descriptor instead.
func (*Chart3DDirectionalLightArchive) Descriptor() ([]byte, []int) {
	return file_TSCH3DArchives_proto_rawDescGZIP(), []int{3}
}

func (x *Chart3DDirectionalLightArchive) GetDirection() *Chart3DVectorArchive {
	if x != nil {
		return x.Direction
	}
	return nil
}

type Chart3DSpotLightArchive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *Chart3DVectorArchive  `protobuf:"bytes,1,req,name=position" json:"position,omitempty"`
	Direction     *Chart3DVectorArchive  `protobuf:"bytes,2,req,name=direction" json:"direction,omitempty"`
	Cutoff        *float32               `protobuf:"fixed32,3,req,name=cutoff" json:"cutoff,omitempty"`
	Dropoff       *float32               `protobuf:"fixed32,4,req,name=dropoff" json:"dropoff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chart3DSpotLightArchive) Reset() {
	*x = Chart3DSpotLightArchive{}
	mi := &file_TSCH3DArchives_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chart3DSpotLightArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chart3DSpotLightArchive) ProtoMessage() {}

func (x *Chart3DSpotLightArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSCH3DArchives_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chart3DSpotLightArchive.ProtoReflect.Descriptor instead.
func (*Chart3DSpotLightArchive) Descriptor() ([]byte, []int) {
	return file_TSCH3DArchives_proto_rawDescGZIP(), []int{4}
}

func (x *Chart3DSpotLightArchive) GetPosition() *Chart3DVectorArchive {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Chart3DSpotLightArchive) GetDirection() *Chart3DVectorArchive {
	if x != nil {
		return x.Direction
	}
	return nil
}

func (x *Chart3DSpotLightArchive) GetCutoff() float32 {
	if x != nil && x.Cutoff != nil {
		return *x.Cutoff
	}
	return 0
}

func (x *Chart3DSpotLightArchive) GetDropoff() float32 {
	if x != nil && x.Dropoff != nil {
		return *x.Dropoff
	}
	return 0
}

type Chart3DLightArchive struct {
	state            protoimpl.MessageState          `protogen:"open.v1"`
	Name             *string                         `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	AmbientColor     *Chart3DVectorArchive           `protobuf:"bytes,2,req,name=ambient_color,json=ambientColor" json:"ambient_color,omitempty"`
	DiffuseColor     *Chart3DVectorArchive           `protobuf:"bytes,3,req,name=diffuse_color,json=diffuseColor" json:"diffuse_color,omitempty"`
	SpecularColor    *Chart3DVectorArchive           `protobuf:"bytes,4,req,name=specular_color,json=specularColor" json:"specular_color,omitempty"`
	Intensity        *float32                        `protobuf:"fixed32,5,req,name=intensity" json:"intensity,omitempty"`
	Attenuation      *Chart3DVectorArchive           `protobuf:"bytes,6,req,name=attenuation" json:"attenuation,omitempty"`
	CoordinateSpace  *uint32                         `protobuf:"varint,7,req,name=coordinate_space,json=coordinateSpace" json:"coordinate_space,omitempty"`
	Enabled          *bool                           `protobuf:"varint,8,req,name=enabled" json:"enabled,omitempty"`
	PointLight       *Chart3DPointLightArchive       `protobuf:"bytes,9,opt,name=point_light,json=pointLight" json:"point_light,omitempty"`
	DirectionalLight *Chart3DDirectionalLightArchive `protobuf:"bytes,10,opt,name=directional_light,json=directionalLight" json:"directional_light,omitempty"`
	SpotLight        *Chart3DSpotLightArchive        `protobuf:"bytes,11,opt,name=spot_light,json=spotLight" json:"spot_light,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Chart3DLightArchive) Reset() {
	*x = Chart3DLightArchive{}
	mi := &file_TSCH3DArchives_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chart3DLightArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chart3DLightArchive) ProtoMessage() {}

func (x *Chart3DLightArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSCH3DArchives_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chart3DLightArchive.ProtoReflect.Descriptor instead.
func (*Chart3DLightArchive) Descriptor() ([]byte, []int) {
	return file_TSCH3DArchives_proto_rawDescGZIP(), []int{5}
}

func (x *Chart3DLightArchive) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Chart3DLightArchive) GetAmbientColor() *Chart3DVectorArchive {
	if x != nil {
		return x.AmbientColor
	}
	return nil
}

func (x *Chart3DLightArchive) GetDiffuseColor() *Chart3DVectorArchive {
	if x != nil {
		return x.DiffuseColor
	}
	return nil
}

func (x *Chart3DLightArchive) GetSpecularColor() *Chart3DVectorArchive {
	if x != nil {
		return x.SpecularColor
	}
	return nil
}

func (x *Chart3DLightArchive) GetIntensity() float32 {
	if x != nil && x.Intensity != nil {
		return *x.Intensity
	}
	return 0
}

func (x *Chart3DLightArchive) GetAttenuation() *Chart3DVectorArchive {
	if x != nil {
		return x.Attenuation
	}
	return nil
}

func (x *Chart3DLightArchive) GetCoordinateSpace() uint32 {
	if x != nil && x.CoordinateSpace != nil {
		return *x.CoordinateSpace
	}
	return 0
}

func (x *Chart3DLightArchive) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

func (x *Chart3DLightArchive) GetPointLight() *Chart3DPointLightArchive {
	if x != nil {
		return x.PointLight
	}
	return nil
}

func (x *Chart3DLightArchive) GetDirectionalLight() *Chart3DDirectionalLightArchive {
	if x != nil {
		return x.DirectionalLight
	}
	return nil
}

func (x *Chart3DLightArchive) GetSpotLight() *Chart3DSpotLightArchive {
	if x != nil {
		return x.SpotLight
	}
	return nil
}

type Chart3DLightingModelArchive struct {
	state         protoimpl.MessageState                    `protogen:"open.v1"`
	Phong         *Chart3DPhongLightingModelArchive         `protobuf:"bytes,1,opt,name=phong" json:"phong,omitempty"`
	FixedFunction *Chart3DFixedFunctionLightingModelArchive `protobuf:"bytes,2,opt,name=fixed_function,json=fixedFunction" json:"fixed_function,omitempty"`
	Environment   *Chart3DEnvironmentPackageArchive         `protobuf:"bytes,3,opt,name=environment" json:"environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chart3DLightingModelArchive) Reset() {
	*x = Chart3DLightingModelArchive{}
	mi := &file_TSCH3DArchives_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chart3DLightingModelArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chart3DLightingModelArchive) ProtoMessage() {}

func (x *Chart3DLightingModelArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSCH3DArchives_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chart3DLightingModelArchive.ProtoReflect.Descriptor instead.
func (*Chart3DLightingModelArchive) Descriptor() ([]byte, []int) {
	return file_TSCH3DArchives_proto_rawDescGZIP(), []int{6}
}

func (x *Chart3DLightingModelArchive) GetPhong() *Chart3DPhongLightingModelArchive {
	if x != nil {
		return x.Phong
	}
	return nil
}

func (x *Chart3DLightingModelArchive) GetFixedFunction() *Chart3DFixedFunctionLightingModelArchive {
	if x != nil {
		return x.FixedFunction
	}
	return nil
}

func (x *Chart3DLightingModelArchive) GetEnvironment() *Chart3DEnvironmentPackageArchive {
	if x != nil {
		return x.Environment
	}
	return nil
}

type Chart3DLightingPackageArchive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Lights        []*Chart3DLightArchive `protobuf:"bytes,2,rep,name=lights" json:"lights,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chart3DLightingPackageArchive) Reset() {
	*x = Chart3DLightingPackageArchive{}
	mi := &file_TSCH3DArchives_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chart3DLightingPackageArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chart3DLightingPackageArchive) ProtoMessage() {}

func (x *Chart3DLightingPackageArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSCH3DArchives_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chart3DLightingPackageArchive.ProtoReflect.Descriptor instead.
func (*Chart3DLightingPackageArchive) Descriptor() ([]byte, []int) {
	return file_TSCH3DArchives_proto_rawDescGZIP(), []int{7}
}

func (x *Chart3DLightingPackageArchive) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Chart3DLightingPackageArchive) GetLights() []*Chart3DLightArchive {
	if x != nil {
		return x.Lights
	}
	return nil
}

type Chart3DTexturesMaterialArchive struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Color         *Chart3DVectorArchive                `protobuf:"bytes,1,req,name=color" json:"color,omitempty"`
	Textures      []*Chart3DTSPImageDataTextureArchive `protobuf:"bytes,2,rep,name=textures" json:"textures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chart3DTexturesMaterialArchive) Reset() {
	*x = Chart3DTexturesMaterialArchive{}
	mi := &file_TSCH3DArchives_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chart3DTexturesMaterialArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chart3DTexturesMaterialArchive) ProtoMessage() {}

func (x *Chart3DTexturesMaterialArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSCH3DArchives_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chart3DTexturesMaterialArchive.ProtoReflect.Descriptor instead.
func (*Chart3DTexturesMaterialArchive) Descriptor() ([]byte, []int) {
	return file_TSCH3DArchives_proto_rawDescGZIP(), []int{8}
}

func (x *Chart3DTexturesMaterialArchive) GetColor() *Chart3DVectorArchive {
	if x != nil {
		return x.Color
	}
	return nil
}

func (x *Chart3DTexturesMaterialArchive) GetTextures() []*Chart3DTSPImageDataTextureArchive {
	if x != nil {
		return x.Textures
	}
	return nil
}

type Chart3DEmissiveMaterialArchive struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Super         *Chart3DTexturesMaterialArchive     `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Tilings       []*Chart3DImageTextureTilingArchive `protobuf:"bytes,2,rep,name=tilings" json:"tilings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chart3DEmissiveMaterialArchive) Reset() {
	*x = Chart3DEmissiveMaterialArchive{}
	mi := &file_TSCH3DArchives_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chart3DEmissiveMaterialArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chart3DEmissiveMaterialArchive) ProtoMessage() {}

func (x *Chart3DEmissiveMaterialArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSCH3DArchives_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chart3DEmissiveMaterialArchive.ProtoReflect.Descriptor instead.
func (*Chart3DEmissiveMaterialArchive) Descriptor() ([]byte, []int) {
	return file_TSCH3DArchives_proto_rawDescGZIP(), []int{9}
}

func (x *Chart3DEmissiveMaterialArchive) GetSuper() *Chart3DTexturesMaterialArchive {
	if x != nil {
		return x.Super
	}
	return nil
}

func (x *Chart3DEmissiveMaterialArchive) GetTilings() []*Chart3DImageTextureTilingArchive {
	if x != nil {
		return x.Tilings
	}
	return nil
}

type Chart3DDiffuseMaterialArchive struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Super         *Chart3DTexturesMaterialArchive     `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Tilings       []*Chart3DImageTextureTilingArchive `protobuf:"bytes,2,rep,name=tilings" json:"tilings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chart3DDiffuseMaterialArchive) Reset() {
	*x = Chart3DDiffuseMaterialArchive{}
	mi := &file_TSCH3DArchives_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chart3DDiffuseMaterialArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chart3DDiffuseMaterialArchive) ProtoMessage() {}

func (x *Chart3DDiffuseMaterialArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSCH3DArchives_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chart3DDiffuseMaterialArchive.ProtoReflect.Descriptor instead.
func (*Chart3DDiffuseMaterialArchive) Descriptor() ([]byte, []int) {
	return file_TSCH3DArchives_proto_rawDescGZIP(), []int{10}
}

func (x *Chart3DDiffuseMaterialArchive) GetSuper() *Chart3DTexturesMaterialArchive {
	if x != nil {
		return x.Super
	}
	return nil
}

func (x *Chart3DDiffuseMaterialArchive) GetTilings() []*Chart3DImageTextureTilingArchive {
	if x != nil {
		return x.Tilings
	}
	return nil
}

type Chart3DModulateMaterialArchive struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Super         *Chart3DTexturesMaterialArchive     `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Tilings       []*Chart3DImageTextureTilingArchive `protobuf:"bytes,2,rep,name=tilings" json:"tilings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chart3DModulateMaterialArchive) Reset() {
	*x = Chart3DModulateMaterialArchive{}
	mi := &file_TSCH3DArchives_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chart3DModulateMaterialArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chart3DModulateMaterialArchive) ProtoMessage() {}

func (x *Chart3DModulateMaterialArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSCH3DArchives_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chart3DModulateMaterialArchive.ProtoReflect.Descriptor instead.
func (*Chart3DModulateMaterialArchive) Descriptor() ([]byte, []int) {
	return file_TSCH3DArchives_proto_rawDescGZIP(), []int{11}
}

func (x *Chart3DModulateMaterialArchive) GetSuper() *Chart3DTexturesMaterialArchive {
	if x != nil {
		return x.Super
	}
	return nil
}

func (x *Chart3DModulateMaterialArchive) GetTilings() []*Chart3DImageTextureTilingArchive {
	if x != nil {
		return x.Tilings
	}
	return nil
}

type Chart3DSpecularMaterialArchive struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Super         *Chart3DTexturesMaterialArchive     `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Tilings       []*Chart3DImageTextureTilingArchive `protobuf:"bytes,2,rep,name=tilings" json:"tilings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chart3DSpecularMaterialArchive) Reset() {
	*x = Chart3DSpecularMaterialArchive{}
	mi := &file_TSCH3DArchives_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chart3DSpecularMaterialArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chart3DSpecularMaterialArchive) ProtoMessage() {}

func (x *Chart3DSpecularMaterialArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSCH3DArchives_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chart3DSpecularMaterialArchive.ProtoReflect.Descriptor instead.
func (*Chart3DSpecularMaterialArchive) Descriptor() ([]byte, []int) {
	return file_TSCH3DArchives_proto_rawDescGZIP(), []int{12}
}

func (x *Chart3DSpecularMaterialArchive) GetSuper() *Chart3DTexturesMaterialArchive {
	if x != nil {
		return x.Super
	}
	return nil
}

func (x *Chart3DSpecularMaterialArchive) GetTilings() []*Chart3DImageTextureTilingArchive {
	if x != nil {
		return x.Tilings
	}
	return nil
}

type Chart3DShininessMaterialArchive struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Super         *Chart3DTexturesMaterialArchive     `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Tilings       []*Chart3DImageTextureTilingArchive `protobuf:"bytes,2,rep,name=tilings" json:"tilings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chart3DShininessMaterialArchive) Reset() {
	*x = Chart3DShininessMaterialArchive{}
	mi := &file_TSCH3DArchives_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chart3DShininessMaterialArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chart3DShininessMaterialArchive) ProtoMessage() {}

func (x *Chart3DShininessMaterialArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSCH3DArchives_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chart3DShininessMaterialArchive.ProtoReflect.Descriptor instead.
func (*Chart3DShininessMaterialArchive) Descriptor() ([]byte, []int) {
	return file_TSCH3DArchives_proto_rawDescGZIP(), []int{13}
}

func (x *Chart3DShininessMaterialArchive) GetSuper() *Chart3DTexturesMaterialArchive {
	if x != nil {
		return x.Super
	}
	return nil
}

func (x *Chart3DShininessMaterialArchive) GetTilings() []*Chart3DImageTextureTilingArchive {
	if x != nil {
		return x.Tilings
	}
	return nil
}

type Chart3DEnvironmentMaterialArchive struct {
	state           protoimpl.MessageState                  `protogen:"open.v1"`
	Super           *Chart3DTexturesMaterialArchive         `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	OBSOLETETilings []*Chart3DBaseImageTextureTilingArchive `protobuf:"bytes,2,rep,name=OBSOLETE_tilings,json=OBSOLETETilings" json:"OBSOLETE_tilings,omitempty"`
	DecalMode       *bool                                   `protobuf:"varint,3,opt,name=decalMode" json:"decalMode,omitempty"`
	Tilings         []*Chart3DImageTextureTilingArchive     `protobuf:"bytes,4,rep,name=tilings" json:"tilings,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Chart3DEnvironmentMaterialArchive) Reset() {
	*x = Chart3DEnvironmentMaterialArchive{}
	mi := &file_TSCH3DArchives_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chart3DEnvironmentMaterialArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chart3DEnvironmentMaterialArchive) ProtoMessage() {}

func (x *Chart3DEnvironmentMaterialArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSCH3DArchives_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chart3DEnvironmentMaterialArchive.ProtoReflect.Descriptor instead.
func (*Chart3DEnvironmentMaterialArchive) Descriptor() ([]byte, []int) {
	return file_TSCH3DArchives_proto_rawDescGZIP(), []int{14}
}

func (x *Chart3DEnvironmentMaterialArchive) GetSuper() *Chart3DTexturesMaterialArchive {
	if x != nil {
		return x.Super
	}
	return nil
}

func (x *Chart3DEnvironmentMaterialArchive) GetOBSOLETETilings() []*Chart3DBaseImageTextureTilingArchive {
	if x != nil {
		return x.OBSOLETETilings
	}
	return nil
}

func (x *Chart3DEnvironmentMaterialArchive) GetDecalMode() bool {
	if x != nil && x.DecalMode != nil {
		return *x.DecalMode
	}
	return false
}

func (x *Chart3DEnvironmentMaterialArchive) GetTilings() []*Chart3DImageTextureTilingArchive {
	if x != nil {
		return x.Tilings
	}
	return nil
}

type Chart3DFixedFunctionLightingModelArchive struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Materials     *Chart3DPhongMaterialPackageArchive `protobuf:"bytes,1,req,name=materials" json:"materials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chart3DFixedFunctionLightingModelArchive) Reset() {
	*x = Chart3DFixedFunctionLightingModelArchive{}
	mi := &file_TSCH3DArchives_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chart3DFixedFunctionLightingModelArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chart3DFixedFunctionLightingModelArchive) ProtoMessage() {}

func (x *Chart3DFixedFunctionLightingModelArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSCH3DArchives_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chart3DFixedFunctionLightingModelArchive.ProtoReflect.Descriptor instead.
func (*Chart3DFixedFunctionLightingModelArchive) Descriptor() ([]byte, []int) {
	return file_TSCH3DArchives_proto_rawDescGZIP(), []int{15}
}

func (x *Chart3DFixedFunctionLightingModelArchive) GetMaterials() *Chart3DPhongMaterialPackageArchive {
	if x != nil {
		return x.Materials
	}
	return nil
}

type Chart3DPhongLightingModelArchive struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Materials     *Chart3DPhongMaterialPackageArchive `protobuf:"bytes,1,req,name=materials" json:"materials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chart3DPhongLightingModelArchive) Reset() {
	*x = Chart3DPhongLightingModelArchive{}
	mi := &file_TSCH3DArchives_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chart3DPhongLightingModelArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chart3DPhongLightingModelArchive) ProtoMessage() {}

func (x *Chart3DPhongLightingModelArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSCH3DArchives_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chart3DPhongLightingModelArchive.ProtoReflect.Descriptor instead.
func (*Chart3DPhongLightingModelArchive) Descriptor() ([]byte, []int) {
	return file_TSCH3DArchives_proto_rawDescGZIP(), []int{16}
}

func (x *Chart3DPhongLightingModelArchive) GetMaterials() *Chart3DPhongMaterialPackageArchive {
	if x != nil {
		return x.Materials
	}
	return nil
}

type Chart3DPhongMaterialPackageArchive struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Emissive      *Chart3DEmissiveMaterialArchive  `protobuf:"bytes,1,opt,name=emissive" json:"emissive,omitempty"`
	Diffuse       *Chart3DDiffuseMaterialArchive   `protobuf:"bytes,2,opt,name=diffuse" json:"diffuse,omitempty"`
	Modulate      *Chart3DModulateMaterialArchive  `protobuf:"bytes,3,opt,name=modulate" json:"modulate,omitempty"`
	Specular      *Chart3DSpecularMaterialArchive  `protobuf:"bytes,4,opt,name=specular" json:"specular,omitempty"`
	Shininess     *Chart3DShininessMaterialArchive `protobuf:"bytes,5,opt,name=shininess" json:"shininess,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chart3DPhongMaterialPackageArchive) Reset() {
	*x = Chart3DPhongMaterialPackageArchive{}
	mi := &file_TSCH3DArchives_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chart3DPhongMaterialPackageArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chart3DPhongMaterialPackageArchive) ProtoMessage() {}

func (x *Chart3DPhongMaterialPackageArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSCH3DArchives_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chart3DPhongMaterialPackageArchive.ProtoReflect.Descriptor instead.
func (*Chart3DPhongMaterialPackageArchive) Descriptor() ([]byte, []int) {
	return file_TSCH3DArchives_proto_rawDescGZIP(), []int{17}
}

func (x *Chart3DPhongMaterialPackageArchive) GetEmissive() *Chart3DEmissiveMaterialArchive {
	if x != nil {
		return x.Emissive
	}
	return nil
}

func (x *Chart3DPhongMaterialPackageArchive) GetDiffuse() *Chart3DDiffuseMaterialArchive {
	if x != nil {
		return x.Diffuse
	}
	return nil
}

func (x *Chart3DPhongMaterialPackageArchive) GetModulate() *Chart3DModulateMaterialArchive {
	if x != nil {
		return x.Modulate
	}
	return nil
}

func (x *Chart3DPhongMaterialPackageArchive) GetSpecular() *Chart3DSpecularMaterialArchive {
	if x != nil {
		return x.Specular
	}
	return nil
}

func (x *Chart3DPhongMaterialPackageArchive) GetShininess() *Chart3DShininessMaterialArchive {
	if x != nil {
		return x.Shininess
	}
	return nil
}

type Chart3DTSPImageDataTextureArchive struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Data               *TSP.DataReference     `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	Mipmapdata         *TSP.DataReference     `protobuf:"bytes,4,opt,name=mipmapdata" json:"mipmapdata,omitempty"`
	DatabaseData       *TSP.Reference         `protobuf:"bytes,1,opt,name=database_data,json=databaseData" json:"database_data,omitempty"`
	DatabaseMipmapdata *TSP.Reference         `protobuf:"bytes,2,opt,name=database_mipmapdata,json=databaseMipmapdata" json:"database_mipmapdata,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Chart3DTSPImageDataTextureArchive) Reset() {
	*x = Chart3DTSPImageDataTextureArchive{}
	mi := &file_TSCH3DArchives_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chart3DTSPImageDataTextureArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chart3DTSPImageDataTextureArchive) ProtoMessage() {}

func (x *Chart3DTSPImageDataTextureArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSCH3DArchives_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chart3DTSPImageDataTextureArchive.ProtoReflect.Descriptor instead.
func (*Chart3DTSPImageDataTextureArchive) Descriptor() ([]byte, []int) {
	return file_TSCH3DArchives_proto_rawDescGZIP(), []int{18}
}

func (x *Chart3DTSPImageDataTextureArchive) GetData() *TSP.DataReference {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Chart3DTSPImageDataTextureArchive) GetMipmapdata() *TSP.DataReference {
	if x != nil {
		return x.Mipmapdata
	}
	return nil
}

func (x *Chart3DTSPImageDataTextureArchive) GetDatabaseData() *TSP.Reference {
	if x != nil {
		return x.DatabaseData
	}
	return nil
}

func (x *Chart3DTSPImageDataTextureArchive) GetDatabaseMipmapdata() *TSP.Reference {
	if x != nil {
		return x.DatabaseMipmapdata
	}
	return nil
}

type Chart3DBaseImageTextureTilingArchive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scale         *Chart3DVectorArchive  `protobuf:"bytes,1,opt,name=scale" json:"scale,omitempty"`
	Rotation      *float32               `protobuf:"fixed32,2,opt,name=rotation" json:"rotation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chart3DBaseImageTextureTilingArchive) Reset() {
	*x = Chart3DBaseImageTextureTilingArchive{}
	mi := &file_TSCH3DArchives_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chart3DBaseImageTextureTilingArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chart3DBaseImageTextureTilingArchive) ProtoMessage() {}

func (x *Chart3DBaseImageTextureTilingArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSCH3DArchives_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chart3DBaseImageTextureTilingArchive.ProtoReflect.Descriptor instead.
func (*Chart3DBaseImageTextureTilingArchive) Descriptor() ([]byte, []int) {
	return file_TSCH3DArchives_proto_rawDescGZIP(), []int{19}
}

func (x *Chart3DBaseImageTextureTilingArchive) GetScale() *Chart3DVectorArchive {
	if x != nil {
		return x.Scale
	}
	return nil
}

func (x *Chart3DBaseImageTextureTilingArchive) GetRotation() float32 {
	if x != nil && x.Rotation != nil {
		return *x.Rotation
	}
	return 0
}

type Chart3DImageTextureTilingArchive struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	Super         *Chart3DBaseImageTextureTilingArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Mode          *TextureTilingMode                    `protobuf:"varint,2,opt,name=mode,enum=TSCH.TextureTilingMode" json:"mode,omitempty"`
	Wrap          *TextureTilingWrap                    `protobuf:"varint,3,opt,name=wrap,enum=TSCH.TextureTilingWrap" json:"wrap,omitempty"`
	Face          *TextureTilingFace                    `protobuf:"varint,4,opt,name=face,enum=TSCH.TextureTilingFace" json:"face,omitempty"`
	Xposition     *TextureTilingXPosition               `protobuf:"varint,5,opt,name=xposition,enum=TSCH.TextureTilingXPosition" json:"xposition,omitempty"`
	Yposition     *TextureTilingYPosition               `protobuf:"varint,6,opt,name=yposition,enum=TSCH.TextureTilingYPosition" json:"yposition,omitempty"`
	Scontinuity   *TextureTilingContinuity              `protobuf:"varint,7,opt,name=scontinuity,enum=TSCH.TextureTilingContinuity" json:"scontinuity,omitempty"`
	Tcontinuity   *TextureTilingContinuity              `protobuf:"varint,8,opt,name=tcontinuity,enum=TSCH.TextureTilingContinuity" json:"tcontinuity,omitempty"`
	Reveal        *bool                                 `protobuf:"varint,9,opt,name=reveal" json:"reveal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chart3DImageTextureTilingArchive) Reset() {
	*x = Chart3DImageTextureTilingArchive{}
	mi := &file_TSCH3DArchives_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chart3DImageTextureTilingArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chart3DImageTextureTilingArchive) ProtoMessage() {}

func (x *Chart3DImageTextureTilingArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSCH3DArchives_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chart3DImageTextureTilingArchive.ProtoReflect.Descriptor instead.
func (*Chart3DImageTextureTilingArchive) Descriptor() ([]byte, []int) {
	return file_TSCH3DArchives_proto_rawDescGZIP(), []int{20}
}

func (x *Chart3DImageTextureTilingArchive) GetSuper() *Chart3DBaseImageTextureTilingArchive {
	if x != nil {
		return x.Super
	}
	return nil
}

func (x *Chart3DImageTextureTilingArchive) GetMode() TextureTilingMode {
	if x != nil && x.Mode != nil {
		return *x.Mode
	}
	return TextureTilingMode_textureTilingModeNone
}

func (x *Chart3DImageTextureTilingArchive) GetWrap() TextureTilingWrap {
	if x != nil && x.Wrap != nil {
		return *x.Wrap
	}
	return TextureTilingWrap_textureTilingWrapProjected
}

func (x *Chart3DImageTextureTilingArchive) GetFace() TextureTilingFace {
	if x != nil && x.Face != nil {
		return *x.Face
	}
	return TextureTilingFace_textureTilingFaceAll
}

func (x *Chart3DImageTextureTilingArchive) GetXposition() TextureTilingXPosition {
	if x != nil && x.Xposition != nil {
		return *x.Xposition
	}
	return TextureTilingXPosition_textureTilingXPositionLeft
}

func (x *Chart3DImageTextureTilingArchive) GetYposition() TextureTilingYPosition {
	if x != nil && x.Yposition != nil {
		return *x.Yposition
	}
	return TextureTilingYPosition_textureTilingYPositionTop
}

func (x *Chart3DImageTextureTilingArchive) GetScontinuity() TextureTilingContinuity {
	if x != nil && x.Scontinuity != nil {
		return *x.Scontinuity
	}
	return TextureTilingContinuity_textureTilingContinuityNone
}

func (x *Chart3DImageTextureTilingArchive) GetTcontinuity() TextureTilingContinuity {
	if x != nil && x.Tcontinuity != nil {
		return *x.Tcontinuity
	}
	return TextureTilingContinuity_textureTilingContinuityNone
}

func (x *Chart3DImageTextureTilingArchive) GetReveal() bool {
	if x != nil && x.Reveal != nil {
		return *x.Reveal
	}
	return false
}

type Chart3DVectorArchive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             *float32               `protobuf:"fixed32,1,req,name=x" json:"x,omitempty"`
	Y             *float32               `protobuf:"fixed32,2,req,name=y" json:"y,omitempty"`
	Z             *float32               `protobuf:"fixed32,3,req,name=z" json:"z,omitempty"`
	W             *float32               `protobuf:"fixed32,4,req,name=w" json:"w,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chart3DVectorArchive) Reset() {
	*x = Chart3DVectorArchive{}
	mi := &file_TSCH3DArchives_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chart3DVectorArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chart3DVectorArchive) ProtoMessage() {}

func (x *Chart3DVectorArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSCH3DArchives_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chart3DVectorArchive.ProtoReflect.Descriptor instead.
func (*Chart3DVectorArchive) Descriptor() ([]byte, []int) {
	return file_TSCH3DArchives_proto_rawDescGZIP(), []int{21}
}

func (x *Chart3DVectorArchive) GetX() float32 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *Chart3DVectorArchive) GetY() float32 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

func (x *Chart3DVectorArchive) GetZ() float32 {
	if x != nil && x.Z != nil {
		return *x.Z
	}
	return 0
}

func (x *Chart3DVectorArchive) GetW() float32 {
	if x != nil && x.W != nil {
		return *x.W
	}
	return 0
}

var File_TSCH3DArchives_proto protoreflect.FileDescriptor

const file_TSCH3DArchives_proto_rawDesc = "" +
	"\n" +
	"\x14TSCH3DArchives.proto\x12\x04TSCH\x1a\x11TSPMessages.proto\x1a\x11TSDArchives.proto\"i\n" +
	" Chart3DEnvironmentPackageArchive\x12E\n" +
	"\tmaterials\x18\x01 \x03(\v2'.TSCH.Chart3DEnvironmentMaterialArchiveR\tmaterials\"\xda\x01\n" +
	"\x12Chart3DFillArchive\x12G\n" +
	"\rlightingmodel\x18\x01 \x01(\v2!.TSCH.Chart3DLightingModelArchiveR\rlightingmodel\x12#\n" +
	"\rtextureset_id\x18\x02 \x01(\tR\ftexturesetId\x123\n" +
	"\tfill_type\x18\x03 \x01(\x0e2\x16.TSCH.FillPropertyTypeR\bfillType\x12!\n" +
	"\fseries_index\x18\x04 \x01(\rR\vseriesIndex\"R\n" +
	"\x18Chart3DPointLightArchive\x126\n" +
	"\bposition\x18\x01 \x02(\v2\x1a.TSCH.Chart3DVectorArchiveR\bposition\"Z\n" +
	"\x1eChart3DDirectionalLightArchive\x128\n" +
	"\tdirection\x18\x01 \x02(\v2\x1a.TSCH.Chart3DVectorArchiveR\tdirection\"\xbd\x01\n" +
	"\x17Chart3DSpotLightArchive\x126\n" +
	"\bposition\x18\x01 \x02(\v2\x1a.TSCH.Chart3DVectorArchiveR\bposition\x128\n" +
	"\tdirection\x18\x02 \x02(\v2\x1a.TSCH.Chart3DVectorArchiveR\tdirection\x12\x16\n" +
	"\x06cutoff\x18\x03 \x02(\x02R\x06cutoff\x12\x18\n" +
	"\adropoff\x18\x04 \x02(\x02R\adropoff\"\xe1\x04\n" +
	"\x13Chart3DLightArchive\x12\x12\n" +
	"\x04name\x18\x01 \x02(\tR\x04name\x12?\n" +
	"\rambient_color\x18\x02 \x02(\v2\x1a.TSCH.Chart3DVectorArchiveR\fambientColor\x12?\n" +
	"\rdiffuse_color\x18\x03 \x02(\v2\x1a.TSCH.Chart3DVectorArchiveR\fdiffuseColor\x12A\n" +
	"\x0especular_color\x18\x04 \x02(\v2\x1a.TSCH.Chart3DVectorArchiveR\rspecularColor\x12\x1c\n" +
	"\tintensity\x18\x05 \x02(\x02R\tintensity\x12<\n" +
	"\vattenuation\x18\x06 \x02(\v2\x1a.TSCH.Chart3DVectorArchiveR\vattenuation\x12)\n" +
	"\x10coordinate_space\x18\a \x02(\rR\x0fcoordinateSpace\x12\x18\n" +
	"\aenabled\x18\b \x02(\bR\aenabled\x12?\n" +
	"\vpoint_light\x18\t \x01(\v2\x1e.TSCH.Chart3DPointLightArchiveR\n" +
	"pointLight\x12Q\n" +
	"\x11directional_light\x18\n" +
	" \x01(\v2$.TSCH.Chart3DDirectionalLightArchiveR\x10directionalLight\x12<\n" +
	"\n" +
	"spot_light\x18\v \x01(\v2\x1d.TSCH.Chart3DSpotLightArchiveR\tspotLight\"\xfc\x01\n" +
	"\x1bChart3DLightingModelArchive\x12<\n" +
	"\x05phong\x18\x01 \x01(\v2&.TSCH.Chart3DPhongLightingModelArchiveR\x05phong\x12U\n" +
	"\x0efixed_function\x18\x02 \x01(\v2..TSCH.Chart3DFixedFunctionLightingModelArchiveR\rfixedFunction\x12H\n" +
	"\venvironment\x18\x03 \x01(\v2&.TSCH.Chart3DEnvironmentPackageArchiveR\venvironment\"f\n" +
	"\x1dChart3DLightingPackageArchive\x12\x12\n" +
	"\x04name\x18\x01 \x02(\tR\x04name\x121\n" +
	"\x06lights\x18\x02 \x03(\v2\x19.TSCH.Chart3DLightArchiveR\x06lights\"\x97\x01\n" +
	"\x1eChart3DTexturesMaterialArchive\x120\n" +
	"\x05color\x18\x01 \x02(\v2\x1a.TSCH.Chart3DVectorArchiveR\x05color\x12C\n" +
	"\btextures\x18\x02 \x03(\v2'.TSCH.Chart3DTSPImageDataTextureArchiveR\btextures\"\x9e\x01\n" +
	"\x1eChart3DEmissiveMaterialArchive\x12:\n" +
	"\x05super\x18\x01 \x02(\v2$.TSCH.Chart3DTexturesMaterialArchiveR\x05super\x12@\n" +
	"\atilings\x18\x02 \x03(\v2&.TSCH.Chart3DImageTextureTilingArchiveR\atilings\"\x9d\x01\n" +
	"\x1dChart3DDiffuseMaterialArchive\x12:\n" +
	"\x05super\x18\x01 \x02(\v2$.TSCH.Chart3DTexturesMaterialArchiveR\x05super\x12@\n" +
	"\atilings\x18\x02 \x03(\v2&.TSCH.Chart3DImageTextureTilingArchiveR\atilings\"\x9e\x01\n" +
	"\x1eChart3DModulateMaterialArchive\x12:\n" +
	"\x05super\x18\x01 \x02(\v2$.TSCH.Chart3DTexturesMaterialArchiveR\x05super\x12@\n" +
	"\atilings\x18\x02 \x03(\v2&.TSCH.Chart3DImageTextureTilingArchiveR\atilings\"\x9e\x01\n" +
	"\x1eChart3DSpecularMaterialArchive\x12:\n" +
	"\x05super\x18\x01 \x02(\v2$.TSCH.Chart3DTexturesMaterialArchiveR\x05super\x12@\n" +
	"\atilings\x18\x02 \x03(\v2&.TSCH.Chart3DImageTextureTilingArchiveR\atilings\"\x9f\x01\n" +
	"\x1fChart3DShininessMaterialArchive\x12:\n" +
	"\x05super\x18\x01 \x02(\v2$.TSCH.Chart3DTexturesMaterialArchiveR\x05super\x12@\n" +
	"\atilings\x18\x02 \x03(\v2&.TSCH.Chart3DImageTextureTilingArchiveR\atilings\"\x96\x02\n" +
	"!Chart3DEnvironmentMaterialArchive\x12:\n" +
	"\x05super\x18\x01 \x02(\v2$.TSCH.Chart3DTexturesMaterialArchiveR\x05super\x12U\n" +
	"\x10OBSOLETE_tilings\x18\x02 \x03(\v2*.TSCH.Chart3DBaseImageTextureTilingArchiveR\x0fOBSOLETETilings\x12\x1c\n" +
	"\tdecalMode\x18\x03 \x01(\bR\tdecalMode\x12@\n" +
	"\atilings\x18\x04 \x03(\v2&.TSCH.Chart3DImageTextureTilingArchiveR\atilings\"r\n" +
	"(Chart3DFixedFunctionLightingModelArchive\x12F\n" +
	"\tmaterials\x18\x01 \x02(\v2(.TSCH.Chart3DPhongMaterialPackageArchiveR\tmaterials\"j\n" +
	" Chart3DPhongLightingModelArchive\x12F\n" +
	"\tmaterials\x18\x01 \x02(\v2(.TSCH.Chart3DPhongMaterialPackageArchiveR\tmaterials\"\xee\x02\n" +
	"\"Chart3DPhongMaterialPackageArchive\x12@\n" +
	"\bemissive\x18\x01 \x01(\v2$.TSCH.Chart3DEmissiveMaterialArchiveR\bemissive\x12=\n" +
	"\adiffuse\x18\x02 \x01(\v2#.TSCH.Chart3DDiffuseMaterialArchiveR\adiffuse\x12@\n" +
	"\bmodulate\x18\x03 \x01(\v2$.TSCH.Chart3DModulateMaterialArchiveR\bmodulate\x12@\n" +
	"\bspecular\x18\x04 \x01(\v2$.TSCH.Chart3DSpecularMaterialArchiveR\bspecular\x12C\n" +
	"\tshininess\x18\x05 \x01(\v2%.TSCH.Chart3DShininessMaterialArchiveR\tshininess\"\xf5\x01\n" +
	"!Chart3DTSPImageDataTextureArchive\x12&\n" +
	"\x04data\x18\x03 \x01(\v2\x12.TSP.DataReferenceR\x04data\x122\n" +
	"\n" +
	"mipmapdata\x18\x04 \x01(\v2\x12.TSP.DataReferenceR\n" +
	"mipmapdata\x123\n" +
	"\rdatabase_data\x18\x01 \x01(\v2\x0e.TSP.ReferenceR\fdatabaseData\x12?\n" +
	"\x13database_mipmapdata\x18\x02 \x01(\v2\x0e.TSP.ReferenceR\x12databaseMipmapdata\"t\n" +
	"$Chart3DBaseImageTextureTilingArchive\x120\n" +
	"\x05scale\x18\x01 \x01(\v2\x1a.TSCH.Chart3DVectorArchiveR\x05scale\x12\x1a\n" +
	"\brotation\x18\x02 \x01(\x02R\brotation\"\xfd\x03\n" +
	" Chart3DImageTextureTilingArchive\x12@\n" +
	"\x05super\x18\x01 \x02(\v2*.TSCH.Chart3DBaseImageTextureTilingArchiveR\x05super\x12+\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x17.TSCH.TextureTilingModeR\x04mode\x12+\n" +
	"\x04wrap\x18\x03 \x01(\x0e2\x17.TSCH.TextureTilingWrapR\x04wrap\x12+\n" +
	"\x04face\x18\x04 \x01(\x0e2\x17.TSCH.TextureTilingFaceR\x04face\x12:\n" +
	"\txposition\x18\x05 \x01(\x0e2\x1c.TSCH.TextureTilingXPositionR\txposition\x12:\n" +
	"\typosition\x18\x06 \x01(\x0e2\x1c.TSCH.TextureTilingYPositionR\typosition\x12?\n" +
	"\vscontinuity\x18\a \x01(\x0e2\x1d.TSCH.TextureTilingContinuityR\vscontinuity\x12?\n" +
	"\vtcontinuity\x18\b \x01(\x0e2\x1d.TSCH.TextureTilingContinuityR\vtcontinuity\x12\x16\n" +
	"\x06reveal\x18\t \x01(\bR\x06reveal\"N\n" +
	"\x14Chart3DVectorArchive\x12\f\n" +
	"\x01x\x18\x01 \x02(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x02(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x02(\x02R\x01z\x12\f\n" +
	"\x01w\x18\x04 \x02(\x02R\x01w*L\n" +
	"\x11TextureTilingMode\x12\x19\n" +
	"\x15textureTilingModeNone\x10\x00\x12\x1c\n" +
	"\x18textureTilingModeTallest\x10\x01*k\n" +
	"\x11TextureTilingFace\x12\x18\n" +
	"\x14textureTilingFaceAll\x10\x00\x12!\n" +
	"\x1dtextureTilingFaceTopAndBottom\x10\x01\x12\x19\n" +
	"\x15textureTilingFaceSide\x10\x02*R\n" +
	"\x11TextureTilingWrap\x12\x1e\n" +
	"\x1atextureTilingWrapProjected\x10\x00\x12\x1d\n" +
	"\x19textureTilingWrapFaceWrap\x10\x01*{\n" +
	"\x16TextureTilingXPosition\x12\x1e\n" +
	"\x1atextureTilingXPositionLeft\x10\x00\x12 \n" +
	"\x1ctextureTilingXPositionCenter\x10\x01\x12\x1f\n" +
	"\x1btextureTilingXPositionRight\x10\x02*{\n" +
	"\x16TextureTilingYPosition\x12\x1d\n" +
	"\x19textureTilingYPositionTop\x10\x00\x12 \n" +
	"\x1ctextureTilingYPositionMiddle\x10\x01\x12 \n" +
	"\x1ctextureTilingYPositionBottom\x10\x02*\xa5\x01\n" +
	"\x17TextureTilingContinuity\x12\x1f\n" +
	"\x1btextureTilingContinuityNone\x10\x00\x12!\n" +
	"\x1dtextureTilingContinuityGlobal\x10\x01\x12!\n" +
	"\x1dtextureTilingContinuitySeries\x10\x02\x12#\n" +
	"\x1ftextureTilingContinuityJittered\x10\x03*\xb3\x01\n" +
	"\x10FillPropertyType\x12\x1d\n" +
	"\x19fillPropertyTypeUndefined\x10\x00\x12\x18\n" +
	"\x14fillPropertyTypeArea\x10\x01\x12\x17\n" +
	"\x13fillPropertyTypeBar\x10\x02\x12\x1a\n" +
	"\x16fillPropertyTypeColumn\x10\x03\x12\x18\n" +
	"\x14fillPropertyTypeLine\x10\x04\x12\x17\n" +
	"\x13fillPropertyTypePie\x10\x05B0Z.github.com/orcastor/iwork-converter/proto/TSCH"

var (
	file_TSCH3DArchives_proto_rawDescOnce sync.Once
	file_TSCH3DArchives_proto_rawDescData []byte
)

func file_TSCH3DArchives_proto_rawDescGZIP() []byte {
	file_TSCH3DArchives_proto_rawDescOnce.Do(func() {
		file_TSCH3DArchives_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_TSCH3DArchives_proto_rawDesc), len(file_TSCH3DArchives_proto_rawDesc)))
	})
	return file_TSCH3DArchives_proto_rawDescData
}

var file_TSCH3DArchives_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_TSCH3DArchives_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_TSCH3DArchives_proto_goTypes = []any{
	(TextureTilingMode)(0),                           // 0: TSCH.TextureTilingMode
	(TextureTilingFace)(0),                           // 1: TSCH.TextureTilingFace
	(TextureTilingWrap)(0),                           // 2: TSCH.TextureTilingWrap
	(TextureTilingXPosition)(0),                      // 3: TSCH.TextureTilingXPosition
	(TextureTilingYPosition)(0),                      // 4: TSCH.TextureTilingYPosition
	(TextureTilingContinuity)(0),                     // 5: TSCH.TextureTilingContinuity
	(FillPropertyType)(0),                            // 6: TSCH.FillPropertyType
	(*Chart3DEnvironmentPackageArchive)(nil),         // 7: TSCH.Chart3DEnvironmentPackageArchive
	(*Chart3DFillArchive)(nil),                       // 8: TSCH.Chart3DFillArchive
	(*Chart3DPointLightArchive)(nil),                 // 9: TSCH.Chart3DPointLightArchive
	(*Chart3DDirectionalLightArchive)(nil),           // 10: TSCH.Chart3DDirectionalLightArchive
	(*Chart3DSpotLightArchive)(nil),                  // 11: TSCH.Chart3DSpotLightArchive
	(*Chart3DLightArchive)(nil),                      // 12: TSCH.Chart3DLightArchive
	(*Chart3DLightingModelArchive)(nil),              // 13: TSCH.Chart3DLightingModelArchive
	(*Chart3DLightingPackageArchive)(nil),            // 14: TSCH.Chart3DLightingPackageArchive
	(*Chart3DTexturesMaterialArchive)(nil),           // 15: TSCH.Chart3DTexturesMaterialArchive
	(*Chart3DEmissiveMaterialArchive)(nil),           // 16: TSCH.Chart3DEmissiveMaterialArchive
	(*Chart3DDiffuseMaterialArchive)(nil),            // 17: TSCH.Chart3DDiffuseMaterialArchive
	(*Chart3DModulateMaterialArchive)(nil),           // 18: TSCH.Chart3DModulateMaterialArchive
	(*Chart3DSpecularMaterialArchive)(nil),           // 19: TSCH.Chart3DSpecularMaterialArchive
	(*Chart3DShininessMaterialArchive)(nil),          // 20: TSCH.Chart3DShininessMaterialArchive
	(*Chart3DEnvironmentMaterialArchive)(nil),        // 21: TSCH.Chart3DEnvironmentMaterialArchive
	(*Chart3DFixedFunctionLightingModelArchive)(nil), // 22: TSCH.Chart3DFixedFunctionLightingModelArchive
	(*Chart3DPhongLightingModelArchive)(nil),         // 23: TSCH.Chart3DPhongLightingModelArchive
	(*Chart3DPhongMaterialPackageArchive)(nil),       // 24: TSCH.Chart3DPhongMaterialPackageArchive
	(*Chart3DTSPImageDataTextureArchive)(nil),        // 25: TSCH.Chart3DTSPImageDataTextureArchive
	(*Chart3DBaseImageTextureTilingArchive)(nil),     // 26: TSCH.Chart3DBaseImageTextureTilingArchive
	(*Chart3DImageTextureTilingArchive)(nil),         // 27: TSCH.Chart3DImageTextureTilingArchive
	(*Chart3DVectorArchive)(nil),                     // 28: TSCH.Chart3DVectorArchive
	(*TSP.DataReference)(nil),                        // 29: TSP.DataReference
	(*TSP.Reference)(nil),                            // 30: TSP.Reference
}
var file_TSCH3DArchives_proto_depIdxs = []int32{
	21, // 0: TSCH.Chart3DEnvironmentPackageArchive.materials:type_name -> TSCH.Chart3DEnvironmentMaterialArchive
	13, // 1: TSCH.Chart3DFillArchive.lightingmodel:type_name -> TSCH.Chart3DLightingModelArchive
	6,  // 2: TSCH.Chart3DFillArchive.fill_type:type_name -> TSCH.FillPropertyType
	28, // 3: TSCH.Chart3DPointLightArchive.position:type_name -> TSCH.Chart3DVectorArchive
	28, // 4: TSCH.Chart3DDirectionalLightArchive.direction:type_name -> TSCH.Chart3DVectorArchive
	28, // 5: TSCH.Chart3DSpotLightArchive.position:type_name -> TSCH.Chart3DVectorArchive
	28, // 6: TSCH.Chart3DSpotLightArchive.direction:type_name -> TSCH.Chart3DVectorArchive
	28, // 7: TSCH.Chart3DLightArchive.ambient_color:type_name -> TSCH.Chart3DVectorArchive
	28, // 8: TSCH.Chart3DLightArchive.diffuse_color:type_name -> TSCH.Chart3DVectorArchive
	28, // 9: TSCH.Chart3DLightArchive.specular_color:type_name -> TSCH.Chart3DVectorArchive
	28, // 10: TSCH.Chart3DLightArchive.attenuation:type_name -> TSCH.Chart3DVectorArchive
	9,  // 11: TSCH.Chart3DLightArchive.point_light:type_name -> TSCH.Chart3DPointLightArchive
	10, // 12: TSCH.Chart3DLightArchive.directional_light:type_name -> TSCH.Chart3DDirectionalLightArchive
	11, // 13: TSCH.Chart3DLightArchive.spot_light:type_name -> TSCH.Chart3DSpotLightArchive
	23, // 14: TSCH.Chart3DLightingModelArchive.phong:type_name -> TSCH.Chart3DPhongLightingModelArchive
	22, // 15: TSCH.Chart3DLightingModelArchive.fixed_function:type_name -> TSCH.Chart3DFixedFunctionLightingModelArchive
	7,  // 16: TSCH.Chart3DLightingModelArchive.environment:type_name -> TSCH.Chart3DEnvironmentPackageArchive
	12, // 17: TSCH.Chart3DLightingPackageArchive.lights:type_name -> TSCH.Chart3DLightArchive
	28, // 18: TSCH.Chart3DTexturesMaterialArchive.color:type_name -> TSCH.Chart3DVectorArchive
	25, // 19: TSCH.Chart3DTexturesMaterialArchive.textures:type_name -> TSCH.Chart3DTSPImageDataTextureArchive
	15, // 20: TSCH.Chart3DEmissiveMaterialArchive.super:type_name -> TSCH.Chart3DTexturesMaterialArchive
	27, // 21: TSCH.Chart3DEmissiveMaterialArchive.tilings:type_name -> TSCH.Chart3DImageTextureTilingArchive
	15, // 22: TSCH.Chart3DDiffuseMaterialArchive.super:type_name -> TSCH.Chart3DTexturesMaterialArchive
	27, // 23: TSCH.Chart3DDiffuseMaterialArchive.tilings:type_name -> TSCH.Chart3DImageTextureTilingArchive
	15, // 24: TSCH.Chart3DModulateMaterialArchive.super:type_name -> TSCH.Chart3DTexturesMaterialArchive
	27, // 25: TSCH.Chart3DModulateMaterialArchive.tilings:type_name -> TSCH.Chart3DImageTextureTilingArchive
	15, // 26: TSCH.Chart3DSpecularMaterialArchive.super:type_name -> TSCH.Chart3DTexturesMaterialArchive
	27, // 27: TSCH.Chart3DSpecularMaterialArchive.tilings:type_name -> TSCH.Chart3DImageTextureTilingArchive
	15, // 28: TSCH.Chart3DShininessMaterialArchive.super:type_name -> TSCH.Chart3DTexturesMaterialArchive
	27, // 29: TSCH.Chart3DShininessMaterialArchive.tilings:type_name -> TSCH.Chart3DImageTextureTilingArchive
	15, // 30: TSCH.Chart3DEnvironmentMaterialArchive.super:type_name -> TSCH.Chart3DTexturesMaterialArchive
	26, // 31: TSCH.Chart3DEnvironmentMaterialArchive.OBSOLETE_tilings:type_name -> TSCH.Chart3DBaseImageTextureTilingArchive
	27, // 32: TSCH.Chart3DEnvironmentMaterialArchive.tilings:type_name -> TSCH.Chart3DImageTextureTilingArchive
	24, // 33: TSCH.Chart3DFixedFunctionLightingModelArchive.materials:type_name -> TSCH.Chart3DPhongMaterialPackageArchive
	24, // 34: TSCH.Chart3DPhongLightingModelArchive.materials:type_name -> TSCH.Chart3DPhongMaterialPackageArchive
	16, // 35: TSCH.Chart3DPhongMaterialPackageArchive.emissive:type_name -> TSCH.Chart3DEmissiveMaterialArchive
	17, // 36: TSCH.Chart3DPhongMaterialPackageArchive.diffuse:type_name -> TSCH.Chart3DDiffuseMaterialArchive
	18, // 37: TSCH.Chart3DPhongMaterialPackageArchive.modulate:type_name -> TSCH.Chart3DModulateMaterialArchive
	19, // 38: TSCH.Chart3DPhongMaterialPackageArchive.specular:type_name -> TSCH.Chart3DSpecularMaterialArchive
	20, // 39: TSCH.Chart3DPhongMaterialPackageArchive.shininess:type_name -> TSCH.Chart3DShininessMaterialArchive
	29, // 40: TSCH.Chart3DTSPImageDataTextureArchive.data:type_name -> TSP.DataReference
	29, // 41: TSCH.Chart3DTSPImageDataTextureArchive.mipmapdata:type_name -> TSP.DataReference
	30, // 42: TSCH.Chart3DTSPImageDataTextureArchive.database_data:type_name -> TSP.Reference
	30, // 43: TSCH.Chart3DTSPImageDataTextureArchive.database_mipmapdata:type_name -> TSP.Reference
	28, // 44: TSCH.Chart3DBaseImageTextureTilingArchive.scale:type_name -> TSCH.Chart3DVectorArchive
	26, // 45: TSCH.Chart3DImageTextureTilingArchive.super:type_name -> TSCH.Chart3DBaseImageTextureTilingArchive
	0,  // 46: TSCH.Chart3DImageTextureTilingArchive.mode:type_name -> TSCH.TextureTilingMode
	2,  // 47: TSCH.Chart3DImageTextureTilingArchive.wrap:type_name -> TSCH.TextureTilingWrap
	1,  // 48: TSCH.Chart3DImageTextureTilingArchive.face:type_name -> TSCH.TextureTilingFace
	3,  // 49: TSCH.Chart3DImageTextureTilingArchive.xposition:type_name -> TSCH.TextureTilingXPosition
	4,  // 50: TSCH.Chart3DImageTextureTilingArchive.yposition:type_name -> TSCH.TextureTilingYPosition
	5,  // 51: TSCH.Chart3DImageTextureTilingArchive.scontinuity:type_name -> TSCH.TextureTilingContinuity
	5,  // 52: TSCH.Chart3DImageTextureTilingArchive.tcontinuity:type_name -> TSCH.TextureTilingContinuity
	53, // [53:53] is the sub-list for method output_type
	53, // [53:53] is the sub-list for method input_type
	53, // [53:53] is the sub-list for extension type_name
	53, // [53:53] is the sub-list for extension extendee
	0,  // [0:53] is the sub-list for field type_name
}

func init() { file_TSCH3DArchives_proto_init() }
func file_TSCH3DArchives_proto_init() {
	if File_TSCH3DArchives_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_TSCH3DArchives_proto_rawDesc), len(file_TSCH3DArchives_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TSCH3DArchives_proto_goTypes,
		DependencyIndexes: file_TSCH3DArchives_proto_depIdxs,
		EnumInfos:         file_TSCH3DArchives_proto_enumTypes,
		MessageInfos:      file_TSCH3DArchives_proto_msgTypes,
	}.Build()
	File_TSCH3DArchives_proto = out.File
	file_TSCH3DArchives_proto_goTypes = nil
	file_TSCH3DArchives_proto_depIdxs = nil
}
