// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: TSSArchives.sos.proto

package TSS

import (
	TSP "github.com/orcastor/iwork-converter/proto/TSP"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpecSetBoolArchive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *bool                  `protobuf:"varint,1,req,name=value" json:"value,omitempty"`
	Unset         *bool                  `protobuf:"varint,2,req,name=unset" json:"unset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpecSetBoolArchive) Reset() {
	*x = SpecSetBoolArchive{}
	mi := &file_TSSArchives_sos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecSetBoolArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecSetBoolArchive) ProtoMessage() {}

func (x *SpecSetBoolArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSSArchives_sos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecSetBoolArchive.ProtoReflect.Descriptor instead.
func (*SpecSetBoolArchive) Descriptor() ([]byte, []int) {
	return file_TSSArchives_sos_proto_rawDescGZIP(), []int{0}
}

func (x *SpecSetBoolArchive) GetValue() bool {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return false
}

func (x *SpecSetBoolArchive) GetUnset() bool {
	if x != nil && x.Unset != nil {
		return *x.Unset
	}
	return false
}

type SpecSetColorArchive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Color         *TSP.Color             `protobuf:"bytes,1,opt,name=color" json:"color,omitempty"`
	Unset         *bool                  `protobuf:"varint,2,req,name=unset" json:"unset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpecSetColorArchive) Reset() {
	*x = SpecSetColorArchive{}
	mi := &file_TSSArchives_sos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecSetColorArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecSetColorArchive) ProtoMessage() {}

func (x *SpecSetColorArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSSArchives_sos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecSetColorArchive.ProtoReflect.Descriptor instead.
func (*SpecSetColorArchive) Descriptor() ([]byte, []int) {
	return file_TSSArchives_sos_proto_rawDescGZIP(), []int{1}
}

func (x *SpecSetColorArchive) GetColor() *TSP.Color {
	if x != nil {
		return x.Color
	}
	return nil
}

func (x *SpecSetColorArchive) GetUnset() bool {
	if x != nil && x.Unset != nil {
		return *x.Unset
	}
	return false
}

type SpecSetDoubleArchive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *float64               `protobuf:"fixed64,1,req,name=value" json:"value,omitempty"`
	Unset         *bool                  `protobuf:"varint,2,req,name=unset" json:"unset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpecSetDoubleArchive) Reset() {
	*x = SpecSetDoubleArchive{}
	mi := &file_TSSArchives_sos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecSetDoubleArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecSetDoubleArchive) ProtoMessage() {}

func (x *SpecSetDoubleArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSSArchives_sos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecSetDoubleArchive.ProtoReflect.Descriptor instead.
func (*SpecSetDoubleArchive) Descriptor() ([]byte, []int) {
	return file_TSSArchives_sos_proto_rawDescGZIP(), []int{2}
}

func (x *SpecSetDoubleArchive) GetValue() float64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *SpecSetDoubleArchive) GetUnset() bool {
	if x != nil && x.Unset != nil {
		return *x.Unset
	}
	return false
}

type SpecSetIntegerArchive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *int32                 `protobuf:"varint,1,req,name=value" json:"value,omitempty"`
	Unset         *bool                  `protobuf:"varint,2,req,name=unset" json:"unset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpecSetIntegerArchive) Reset() {
	*x = SpecSetIntegerArchive{}
	mi := &file_TSSArchives_sos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecSetIntegerArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecSetIntegerArchive) ProtoMessage() {}

func (x *SpecSetIntegerArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSSArchives_sos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecSetIntegerArchive.ProtoReflect.Descriptor instead.
func (*SpecSetIntegerArchive) Descriptor() ([]byte, []int) {
	return file_TSSArchives_sos_proto_rawDescGZIP(), []int{3}
}

func (x *SpecSetIntegerArchive) GetValue() int32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *SpecSetIntegerArchive) GetUnset() bool {
	if x != nil && x.Unset != nil {
		return *x.Unset
	}
	return false
}

type SpecSetStringArchive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *string                `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
	Unset         *bool                  `protobuf:"varint,2,req,name=unset" json:"unset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpecSetStringArchive) Reset() {
	*x = SpecSetStringArchive{}
	mi := &file_TSSArchives_sos_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecSetStringArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecSetStringArchive) ProtoMessage() {}

func (x *SpecSetStringArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSSArchives_sos_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecSetStringArchive.ProtoReflect.Descriptor instead.
func (*SpecSetStringArchive) Descriptor() ([]byte, []int) {
	return file_TSSArchives_sos_proto_rawDescGZIP(), []int{4}
}

func (x *SpecSetStringArchive) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

func (x *SpecSetStringArchive) GetUnset() bool {
	if x != nil && x.Unset != nil {
		return *x.Unset
	}
	return false
}

type SpecBoolArchive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpecSetBool   *SpecSetBoolArchive    `protobuf:"bytes,1,opt,name=spec_set_bool,json=specSetBool" json:"spec_set_bool,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpecBoolArchive) Reset() {
	*x = SpecBoolArchive{}
	mi := &file_TSSArchives_sos_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecBoolArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecBoolArchive) ProtoMessage() {}

func (x *SpecBoolArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSSArchives_sos_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecBoolArchive.ProtoReflect.Descriptor instead.
func (*SpecBoolArchive) Descriptor() ([]byte, []int) {
	return file_TSSArchives_sos_proto_rawDescGZIP(), []int{5}
}

func (x *SpecBoolArchive) GetSpecSetBool() *SpecSetBoolArchive {
	if x != nil {
		return x.SpecSetBool
	}
	return nil
}

type SpecColorArchive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpecSetColor  *SpecSetColorArchive   `protobuf:"bytes,1,opt,name=spec_set_color,json=specSetColor" json:"spec_set_color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpecColorArchive) Reset() {
	*x = SpecColorArchive{}
	mi := &file_TSSArchives_sos_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecColorArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecColorArchive) ProtoMessage() {}

func (x *SpecColorArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSSArchives_sos_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecColorArchive.ProtoReflect.Descriptor instead.
func (*SpecColorArchive) Descriptor() ([]byte, []int) {
	return file_TSSArchives_sos_proto_rawDescGZIP(), []int{6}
}

func (x *SpecColorArchive) GetSpecSetColor() *SpecSetColorArchive {
	if x != nil {
		return x.SpecSetColor
	}
	return nil
}

type SpecDoubleArchive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpecSetDouble *SpecSetDoubleArchive  `protobuf:"bytes,1,opt,name=spec_set_double,json=specSetDouble" json:"spec_set_double,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpecDoubleArchive) Reset() {
	*x = SpecDoubleArchive{}
	mi := &file_TSSArchives_sos_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecDoubleArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecDoubleArchive) ProtoMessage() {}

func (x *SpecDoubleArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSSArchives_sos_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecDoubleArchive.ProtoReflect.Descriptor instead.
func (*SpecDoubleArchive) Descriptor() ([]byte, []int) {
	return file_TSSArchives_sos_proto_rawDescGZIP(), []int{7}
}

func (x *SpecDoubleArchive) GetSpecSetDouble() *SpecSetDoubleArchive {
	if x != nil {
		return x.SpecSetDouble
	}
	return nil
}

type SpecIntegerArchive struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SpecSetInteger *SpecSetIntegerArchive `protobuf:"bytes,1,opt,name=spec_set_integer,json=specSetInteger" json:"spec_set_integer,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SpecIntegerArchive) Reset() {
	*x = SpecIntegerArchive{}
	mi := &file_TSSArchives_sos_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecIntegerArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecIntegerArchive) ProtoMessage() {}

func (x *SpecIntegerArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSSArchives_sos_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecIntegerArchive.ProtoReflect.Descriptor instead.
func (*SpecIntegerArchive) Descriptor() ([]byte, []int) {
	return file_TSSArchives_sos_proto_rawDescGZIP(), []int{8}
}

func (x *SpecIntegerArchive) GetSpecSetInteger() *SpecSetIntegerArchive {
	if x != nil {
		return x.SpecSetInteger
	}
	return nil
}

type SpecStringArchive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpecSetString *SpecSetStringArchive  `protobuf:"bytes,1,opt,name=spec_set_string,json=specSetString" json:"spec_set_string,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpecStringArchive) Reset() {
	*x = SpecStringArchive{}
	mi := &file_TSSArchives_sos_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecStringArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecStringArchive) ProtoMessage() {}

func (x *SpecStringArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSSArchives_sos_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecStringArchive.ProtoReflect.Descriptor instead.
func (*SpecStringArchive) Descriptor() ([]byte, []int) {
	return file_TSSArchives_sos_proto_rawDescGZIP(), []int{9}
}

func (x *SpecStringArchive) GetSpecSetString() *SpecSetStringArchive {
	if x != nil {
		return x.SpecSetString
	}
	return nil
}

var File_TSSArchives_sos_proto protoreflect.FileDescriptor

const file_TSSArchives_sos_proto_rawDesc = "" +
	"\n" +
	"\x15TSSArchives.sos.proto\x12\x03TSS\x1a\x11TSPMessages.proto\"@\n" +
	"\x12SpecSetBoolArchive\x12\x14\n" +
	"\x05value\x18\x01 \x02(\bR\x05value\x12\x14\n" +
	"\x05unset\x18\x02 \x02(\bR\x05unset\"M\n" +
	"\x13SpecSetColorArchive\x12 \n" +
	"\x05color\x18\x01 \x01(\v2\n" +
	".TSP.ColorR\x05color\x12\x14\n" +
	"\x05unset\x18\x02 \x02(\bR\x05unset\"B\n" +
	"\x14SpecSetDoubleArchive\x12\x14\n" +
	"\x05value\x18\x01 \x02(\x01R\x05value\x12\x14\n" +
	"\x05unset\x18\x02 \x02(\bR\x05unset\"C\n" +
	"\x15SpecSetIntegerArchive\x12\x14\n" +
	"\x05value\x18\x01 \x02(\x05R\x05value\x12\x14\n" +
	"\x05unset\x18\x02 \x02(\bR\x05unset\"B\n" +
	"\x14SpecSetStringArchive\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05unset\x18\x02 \x02(\bR\x05unset\"N\n" +
	"\x0fSpecBoolArchive\x12;\n" +
	"\rspec_set_bool\x18\x01 \x01(\v2\x17.TSS.SpecSetBoolArchiveR\vspecSetBool\"R\n" +
	"\x10SpecColorArchive\x12>\n" +
	"\x0espec_set_color\x18\x01 \x01(\v2\x18.TSS.SpecSetColorArchiveR\fspecSetColor\"V\n" +
	"\x11SpecDoubleArchive\x12A\n" +
	"\x0fspec_set_double\x18\x01 \x01(\v2\x19.TSS.SpecSetDoubleArchiveR\rspecSetDouble\"Z\n" +
	"\x12SpecIntegerArchive\x12D\n" +
	"\x10spec_set_integer\x18\x01 \x01(\v2\x1a.TSS.SpecSetIntegerArchiveR\x0especSetInteger\"V\n" +
	"\x11SpecStringArchive\x12A\n" +
	"\x0fspec_set_string\x18\x01 \x01(\v2\x19.TSS.SpecSetStringArchiveR\rspecSetStringB/Z-github.com/orcastor/iwork-converter/proto/TSS"

var (
	file_TSSArchives_sos_proto_rawDescOnce sync.Once
	file_TSSArchives_sos_proto_rawDescData []byte
)

func file_TSSArchives_sos_proto_rawDescGZIP() []byte {
	file_TSSArchives_sos_proto_rawDescOnce.Do(func() {
		file_TSSArchives_sos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_TSSArchives_sos_proto_rawDesc), len(file_TSSArchives_sos_proto_rawDesc)))
	})
	return file_TSSArchives_sos_proto_rawDescData
}

var file_TSSArchives_sos_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_TSSArchives_sos_proto_goTypes = []any{
	(*SpecSetBoolArchive)(nil),    // 0: TSS.SpecSetBoolArchive
	(*SpecSetColorArchive)(nil),   // 1: TSS.SpecSetColorArchive
	(*SpecSetDoubleArchive)(nil),  // 2: TSS.SpecSetDoubleArchive
	(*SpecSetIntegerArchive)(nil), // 3: TSS.SpecSetIntegerArchive
	(*SpecSetStringArchive)(nil),  // 4: TSS.SpecSetStringArchive
	(*SpecBoolArchive)(nil),       // 5: TSS.SpecBoolArchive
	(*SpecColorArchive)(nil),      // 6: TSS.SpecColorArchive
	(*SpecDoubleArchive)(nil),     // 7: TSS.SpecDoubleArchive
	(*SpecIntegerArchive)(nil),    // 8: TSS.SpecIntegerArchive
	(*SpecStringArchive)(nil),     // 9: TSS.SpecStringArchive
	(*TSP.Color)(nil),             // 10: TSP.Color
}
var file_TSSArchives_sos_proto_depIdxs = []int32{
	10, // 0: TSS.SpecSetColorArchive.color:type_name -> TSP.Color
	0,  // 1: TSS.SpecBoolArchive.spec_set_bool:type_name -> TSS.SpecSetBoolArchive
	1,  // 2: TSS.SpecColorArchive.spec_set_color:type_name -> TSS.SpecSetColorArchive
	2,  // 3: TSS.SpecDoubleArchive.spec_set_double:type_name -> TSS.SpecSetDoubleArchive
	3,  // 4: TSS.SpecIntegerArchive.spec_set_integer:type_name -> TSS.SpecSetIntegerArchive
	4,  // 5: TSS.SpecStringArchive.spec_set_string:type_name -> TSS.SpecSetStringArchive
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_TSSArchives_sos_proto_init() }
func file_TSSArchives_sos_proto_init() {
	if File_TSSArchives_sos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_TSSArchives_sos_proto_rawDesc), len(file_TSSArchives_sos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TSSArchives_sos_proto_goTypes,
		DependencyIndexes: file_TSSArchives_sos_proto_depIdxs,
		MessageInfos:      file_TSSArchives_sos_proto_msgTypes,
	}.Build()
	File_TSSArchives_sos_proto = out.File
	file_TSSArchives_sos_proto_goTypes = nil
	file_TSSArchives_sos_proto_depIdxs = nil
}
