// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: TSTArchives.sos.proto

package TST

import (
	TSD "github.com/orcastor/iwork-converter/proto/TSD"
	TSS "github.com/orcastor/iwork-converter/proto/TSS"
	TSWP "github.com/orcastor/iwork-converter/proto/TSWP"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpecSetTableStrokePresetListArchive struct {
	state                 protoimpl.MessageState   `protogen:"open.v1"`
	TableStrokePresetList *StrokePresetListArchive `protobuf:"bytes,1,opt,name=table_stroke_preset_list,json=tableStrokePresetList" json:"table_stroke_preset_list,omitempty"`
	Unset                 *bool                    `protobuf:"varint,2,req,name=unset" json:"unset,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SpecSetTableStrokePresetListArchive) Reset() {
	*x = SpecSetTableStrokePresetListArchive{}
	mi := &file_TSTArchives_sos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecSetTableStrokePresetListArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecSetTableStrokePresetListArchive) ProtoMessage() {}

func (x *SpecSetTableStrokePresetListArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSTArchives_sos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecSetTableStrokePresetListArchive.ProtoReflect.Descriptor instead.
func (*SpecSetTableStrokePresetListArchive) Descriptor() ([]byte, []int) {
	return file_TSTArchives_sos_proto_rawDescGZIP(), []int{0}
}

func (x *SpecSetTableStrokePresetListArchive) GetTableStrokePresetList() *StrokePresetListArchive {
	if x != nil {
		return x.TableStrokePresetList
	}
	return nil
}

func (x *SpecSetTableStrokePresetListArchive) GetUnset() bool {
	if x != nil && x.Unset != nil {
		return *x.Unset
	}
	return false
}

type SpecTableStrokePresetListArchive struct {
	state                        protoimpl.MessageState               `protogen:"open.v1"`
	SpecSetTableStrokePresetList *SpecSetTableStrokePresetListArchive `protobuf:"bytes,1,opt,name=spec_set_table_stroke_preset_list,json=specSetTableStrokePresetList" json:"spec_set_table_stroke_preset_list,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *SpecTableStrokePresetListArchive) Reset() {
	*x = SpecTableStrokePresetListArchive{}
	mi := &file_TSTArchives_sos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpecTableStrokePresetListArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpecTableStrokePresetListArchive) ProtoMessage() {}

func (x *SpecTableStrokePresetListArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSTArchives_sos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpecTableStrokePresetListArchive.ProtoReflect.Descriptor instead.
func (*SpecTableStrokePresetListArchive) Descriptor() ([]byte, []int) {
	return file_TSTArchives_sos_proto_rawDescGZIP(), []int{1}
}

func (x *SpecTableStrokePresetListArchive) GetSpecSetTableStrokePresetList() *SpecSetTableStrokePresetListArchive {
	if x != nil {
		return x.SpecSetTableStrokePresetList
	}
	return nil
}

type TableCellStylePropertyChangeSetArchive struct {
	state                      protoimpl.MessageState   `protogen:"open.v1"`
	TextWrap                   *TSS.SpecBoolArchive     `protobuf:"bytes,1,opt,name=text_wrap,json=textWrap" json:"text_wrap,omitempty"`
	TextWrapUndefined          *bool                    `protobuf:"varint,2,opt,name=text_wrap_undefined,json=textWrapUndefined" json:"text_wrap_undefined,omitempty"`
	Type                       *TSS.SpecIntegerArchive  `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	TypeUndefined              *bool                    `protobuf:"varint,4,opt,name=type_undefined,json=typeUndefined" json:"type_undefined,omitempty"`
	Fill                       *TSD.SpecFillArchive     `protobuf:"bytes,5,opt,name=fill" json:"fill,omitempty"`
	FillUndefined              *bool                    `protobuf:"varint,6,opt,name=fill_undefined,json=fillUndefined" json:"fill_undefined,omitempty"`
	VerticalAlignment          *TSS.SpecIntegerArchive  `protobuf:"bytes,7,opt,name=vertical_alignment,json=verticalAlignment" json:"vertical_alignment,omitempty"`
	VerticalAlignmentUndefined *bool                    `protobuf:"varint,8,opt,name=vertical_alignment_undefined,json=verticalAlignmentUndefined" json:"vertical_alignment_undefined,omitempty"`
	Padding                    *TSWP.SpecPaddingArchive `protobuf:"bytes,9,opt,name=padding" json:"padding,omitempty"`
	PaddingUndefined           *bool                    `protobuf:"varint,10,opt,name=padding_undefined,json=paddingUndefined" json:"padding_undefined,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *TableCellStylePropertyChangeSetArchive) Reset() {
	*x = TableCellStylePropertyChangeSetArchive{}
	mi := &file_TSTArchives_sos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableCellStylePropertyChangeSetArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableCellStylePropertyChangeSetArchive) ProtoMessage() {}

func (x *TableCellStylePropertyChangeSetArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSTArchives_sos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableCellStylePropertyChangeSetArchive.ProtoReflect.Descriptor instead.
func (*TableCellStylePropertyChangeSetArchive) Descriptor() ([]byte, []int) {
	return file_TSTArchives_sos_proto_rawDescGZIP(), []int{2}
}

func (x *TableCellStylePropertyChangeSetArchive) GetTextWrap() *TSS.SpecBoolArchive {
	if x != nil {
		return x.TextWrap
	}
	return nil
}

func (x *TableCellStylePropertyChangeSetArchive) GetTextWrapUndefined() bool {
	if x != nil && x.TextWrapUndefined != nil {
		return *x.TextWrapUndefined
	}
	return false
}

func (x *TableCellStylePropertyChangeSetArchive) GetType() *TSS.SpecIntegerArchive {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *TableCellStylePropertyChangeSetArchive) GetTypeUndefined() bool {
	if x != nil && x.TypeUndefined != nil {
		return *x.TypeUndefined
	}
	return false
}

func (x *TableCellStylePropertyChangeSetArchive) GetFill() *TSD.SpecFillArchive {
	if x != nil {
		return x.Fill
	}
	return nil
}

func (x *TableCellStylePropertyChangeSetArchive) GetFillUndefined() bool {
	if x != nil && x.FillUndefined != nil {
		return *x.FillUndefined
	}
	return false
}

func (x *TableCellStylePropertyChangeSetArchive) GetVerticalAlignment() *TSS.SpecIntegerArchive {
	if x != nil {
		return x.VerticalAlignment
	}
	return nil
}

func (x *TableCellStylePropertyChangeSetArchive) GetVerticalAlignmentUndefined() bool {
	if x != nil && x.VerticalAlignmentUndefined != nil {
		return *x.VerticalAlignmentUndefined
	}
	return false
}

func (x *TableCellStylePropertyChangeSetArchive) GetPadding() *TSWP.SpecPaddingArchive {
	if x != nil {
		return x.Padding
	}
	return nil
}

func (x *TableCellStylePropertyChangeSetArchive) GetPaddingUndefined() bool {
	if x != nil && x.PaddingUndefined != nil {
		return *x.PaddingUndefined
	}
	return false
}

type TableStylePropertyChangeSetArchive struct {
	state                                           protoimpl.MessageState            `protogen:"open.v1"`
	AutoResize                                      *TSS.SpecBoolArchive              `protobuf:"bytes,1,opt,name=auto_resize,json=autoResize" json:"auto_resize,omitempty"`
	AutoResizeUndefined                             *bool                             `protobuf:"varint,2,opt,name=auto_resize_undefined,json=autoResizeUndefined" json:"auto_resize_undefined,omitempty"`
	BandedRows                                      *TSS.SpecBoolArchive              `protobuf:"bytes,3,opt,name=banded_rows,json=bandedRows" json:"banded_rows,omitempty"`
	BandedRowsUndefined                             *bool                             `protobuf:"varint,4,opt,name=banded_rows_undefined,json=bandedRowsUndefined" json:"banded_rows_undefined,omitempty"`
	BandedCellFill                                  *TSD.SpecFillArchive              `protobuf:"bytes,5,opt,name=banded_cell_fill,json=bandedCellFill" json:"banded_cell_fill,omitempty"`
	BandedCellFillUndefined                         *bool                             `protobuf:"varint,6,opt,name=banded_cell_fill_undefined,json=bandedCellFillUndefined" json:"banded_cell_fill_undefined,omitempty"`
	BehavesLikeSpreadsheet                          *TSS.SpecBoolArchive              `protobuf:"bytes,7,opt,name=behaves_like_spreadsheet,json=behavesLikeSpreadsheet" json:"behaves_like_spreadsheet,omitempty"`
	BehavesLikeSpreadsheetUndefined                 *bool                             `protobuf:"varint,8,opt,name=behaves_like_spreadsheet_undefined,json=behavesLikeSpreadsheetUndefined" json:"behaves_like_spreadsheet_undefined,omitempty"`
	BodyHorizontalBorderStroke                      *TSD.SpecStrokeArchive            `protobuf:"bytes,9,opt,name=body_horizontal_border_stroke,json=bodyHorizontalBorderStroke" json:"body_horizontal_border_stroke,omitempty"`
	BodyHorizontalBorderStrokeUndefined             *bool                             `protobuf:"varint,10,opt,name=body_horizontal_border_stroke_undefined,json=bodyHorizontalBorderStrokeUndefined" json:"body_horizontal_border_stroke_undefined,omitempty"`
	BodyVerticalBorderStroke                        *TSD.SpecStrokeArchive            `protobuf:"bytes,11,opt,name=body_vertical_border_stroke,json=bodyVerticalBorderStroke" json:"body_vertical_border_stroke,omitempty"`
	BodyVerticalBorderStrokeUndefined               *bool                             `protobuf:"varint,12,opt,name=body_vertical_border_stroke_undefined,json=bodyVerticalBorderStrokeUndefined" json:"body_vertical_border_stroke_undefined,omitempty"`
	BodyHorizontalStroke                            *TSD.SpecStrokeArchive            `protobuf:"bytes,13,opt,name=body_horizontal_stroke,json=bodyHorizontalStroke" json:"body_horizontal_stroke,omitempty"`
	BodyHorizontalStrokeUndefined                   *bool                             `protobuf:"varint,14,opt,name=body_horizontal_stroke_undefined,json=bodyHorizontalStrokeUndefined" json:"body_horizontal_stroke_undefined,omitempty"`
	BodyVerticalStroke                              *TSD.SpecStrokeArchive            `protobuf:"bytes,15,opt,name=body_vertical_stroke,json=bodyVerticalStroke" json:"body_vertical_stroke,omitempty"`
	BodyVerticalStrokeUndefined                     *bool                             `protobuf:"varint,16,opt,name=body_vertical_stroke_undefined,json=bodyVerticalStrokeUndefined" json:"body_vertical_stroke_undefined,omitempty"`
	HeaderColumnBorderStroke                        *TSD.SpecStrokeArchive            `protobuf:"bytes,17,opt,name=header_column_border_stroke,json=headerColumnBorderStroke" json:"header_column_border_stroke,omitempty"`
	HeaderColumnBorderStrokeUndefined               *bool                             `protobuf:"varint,18,opt,name=header_column_border_stroke_undefined,json=headerColumnBorderStrokeUndefined" json:"header_column_border_stroke_undefined,omitempty"`
	HeaderColumnVerticalStroke                      *TSD.SpecStrokeArchive            `protobuf:"bytes,19,opt,name=header_column_vertical_stroke,json=headerColumnVerticalStroke" json:"header_column_vertical_stroke,omitempty"`
	HeaderColumnVerticalStrokeUndefined             *bool                             `protobuf:"varint,20,opt,name=header_column_vertical_stroke_undefined,json=headerColumnVerticalStrokeUndefined" json:"header_column_vertical_stroke_undefined,omitempty"`
	HeaderColumnHorizontalStroke                    *TSD.SpecStrokeArchive            `protobuf:"bytes,21,opt,name=header_column_horizontal_stroke,json=headerColumnHorizontalStroke" json:"header_column_horizontal_stroke,omitempty"`
	HeaderColumnHorizontalStrokeUndefined           *bool                             `protobuf:"varint,22,opt,name=header_column_horizontal_stroke_undefined,json=headerColumnHorizontalStrokeUndefined" json:"header_column_horizontal_stroke_undefined,omitempty"`
	HeaderColumnSeparatorStroke                     *TSD.SpecStrokeArchive            `protobuf:"bytes,23,opt,name=header_column_separator_stroke,json=headerColumnSeparatorStroke" json:"header_column_separator_stroke,omitempty"`
	HeaderColumnSeparatorStrokeUndefined            *bool                             `protobuf:"varint,24,opt,name=header_column_separator_stroke_undefined,json=headerColumnSeparatorStrokeUndefined" json:"header_column_separator_stroke_undefined,omitempty"`
	HeaderRowBorderStroke                           *TSD.SpecStrokeArchive            `protobuf:"bytes,25,opt,name=header_row_border_stroke,json=headerRowBorderStroke" json:"header_row_border_stroke,omitempty"`
	HeaderRowBorderStrokeUndefined                  *bool                             `protobuf:"varint,26,opt,name=header_row_border_stroke_undefined,json=headerRowBorderStrokeUndefined" json:"header_row_border_stroke_undefined,omitempty"`
	HeaderRowHorizontalStroke                       *TSD.SpecStrokeArchive            `protobuf:"bytes,27,opt,name=header_row_horizontal_stroke,json=headerRowHorizontalStroke" json:"header_row_horizontal_stroke,omitempty"`
	HeaderRowHorizontalStrokeUndefined              *bool                             `protobuf:"varint,28,opt,name=header_row_horizontal_stroke_undefined,json=headerRowHorizontalStrokeUndefined" json:"header_row_horizontal_stroke_undefined,omitempty"`
	HeaderRowVerticalStroke                         *TSD.SpecStrokeArchive            `protobuf:"bytes,29,opt,name=header_row_vertical_stroke,json=headerRowVerticalStroke" json:"header_row_vertical_stroke,omitempty"`
	HeaderRowVerticalStrokeUndefined                *bool                             `protobuf:"varint,30,opt,name=header_row_vertical_stroke_undefined,json=headerRowVerticalStrokeUndefined" json:"header_row_vertical_stroke_undefined,omitempty"`
	HeaderRowSeparatorStroke                        *TSD.SpecStrokeArchive            `protobuf:"bytes,31,opt,name=header_row_separator_stroke,json=headerRowSeparatorStroke" json:"header_row_separator_stroke,omitempty"`
	HeaderRowSeparatorStrokeUndefined               *bool                             `protobuf:"varint,32,opt,name=header_row_separator_stroke_undefined,json=headerRowSeparatorStrokeUndefined" json:"header_row_separator_stroke_undefined,omitempty"`
	FooterRowBorderStroke                           *TSD.SpecStrokeArchive            `protobuf:"bytes,33,opt,name=footer_row_border_stroke,json=footerRowBorderStroke" json:"footer_row_border_stroke,omitempty"`
	FooterRowBorderStrokeUndefined                  *bool                             `protobuf:"varint,34,opt,name=footer_row_border_stroke_undefined,json=footerRowBorderStrokeUndefined" json:"footer_row_border_stroke_undefined,omitempty"`
	FooterRowHorizontalStroke                       *TSD.SpecStrokeArchive            `protobuf:"bytes,35,opt,name=footer_row_horizontal_stroke,json=footerRowHorizontalStroke" json:"footer_row_horizontal_stroke,omitempty"`
	FooterRowHorizontalStrokeUndefined              *bool                             `protobuf:"varint,36,opt,name=footer_row_horizontal_stroke_undefined,json=footerRowHorizontalStrokeUndefined" json:"footer_row_horizontal_stroke_undefined,omitempty"`
	FooterRowVerticalStroke                         *TSD.SpecStrokeArchive            `protobuf:"bytes,37,opt,name=footer_row_vertical_stroke,json=footerRowVerticalStroke" json:"footer_row_vertical_stroke,omitempty"`
	FooterRowVerticalStrokeUndefined                *bool                             `protobuf:"varint,38,opt,name=footer_row_vertical_stroke_undefined,json=footerRowVerticalStrokeUndefined" json:"footer_row_vertical_stroke_undefined,omitempty"`
	FooterRowSeparatorStroke                        *TSD.SpecStrokeArchive            `protobuf:"bytes,39,opt,name=footer_row_separator_stroke,json=footerRowSeparatorStroke" json:"footer_row_separator_stroke,omitempty"`
	FooterRowSeparatorStrokeUndefined               *bool                             `protobuf:"varint,40,opt,name=footer_row_separator_stroke_undefined,json=footerRowSeparatorStrokeUndefined" json:"footer_row_separator_stroke_undefined,omitempty"`
	StrokePresetListObject                          *SpecTableStrokePresetListArchive `protobuf:"bytes,41,opt,name=stroke_preset_list_object,json=strokePresetListObject" json:"stroke_preset_list_object,omitempty"`
	StrokePresetListObjectUndefined                 *bool                             `protobuf:"varint,42,opt,name=stroke_preset_list_object_undefined,json=strokePresetListObjectUndefined" json:"stroke_preset_list_object_undefined,omitempty"`
	VerticalStrokesVisible                          *TSS.SpecBoolArchive              `protobuf:"bytes,43,opt,name=vertical_strokes_visible,json=verticalStrokesVisible" json:"vertical_strokes_visible,omitempty"`
	VerticalStrokesVisibleUndefined                 *bool                             `protobuf:"varint,44,opt,name=vertical_strokes_visible_undefined,json=verticalStrokesVisibleUndefined" json:"vertical_strokes_visible_undefined,omitempty"`
	HorizontalStrokesVisible                        *TSS.SpecBoolArchive              `protobuf:"bytes,45,opt,name=horizontal_strokes_visible,json=horizontalStrokesVisible" json:"horizontal_strokes_visible,omitempty"`
	HorizontalStrokesVisibleUndefined               *bool                             `protobuf:"varint,46,opt,name=horizontal_strokes_visible_undefined,json=horizontalStrokesVisibleUndefined" json:"horizontal_strokes_visible_undefined,omitempty"`
	HeaderRowSepVisible                             *TSS.SpecBoolArchive              `protobuf:"bytes,47,opt,name=header_row_sep_visible,json=headerRowSepVisible" json:"header_row_sep_visible,omitempty"`
	HeaderRowSepVisibleUndefined                    *bool                             `protobuf:"varint,48,opt,name=header_row_sep_visible_undefined,json=headerRowSepVisibleUndefined" json:"header_row_sep_visible_undefined,omitempty"`
	HeaderRowVerticalsVisible                       *TSS.SpecBoolArchive              `protobuf:"bytes,49,opt,name=header_row_verticals_visible,json=headerRowVerticalsVisible" json:"header_row_verticals_visible,omitempty"`
	HeaderRowVerticalsVisibleUndefined              *bool                             `protobuf:"varint,50,opt,name=header_row_verticals_visible_undefined,json=headerRowVerticalsVisibleUndefined" json:"header_row_verticals_visible_undefined,omitempty"`
	HeaderColSepVisible                             *TSS.SpecBoolArchive              `protobuf:"bytes,51,opt,name=header_col_sep_visible,json=headerColSepVisible" json:"header_col_sep_visible,omitempty"`
	HeaderColSepVisibleUndefined                    *bool                             `protobuf:"varint,52,opt,name=header_col_sep_visible_undefined,json=headerColSepVisibleUndefined" json:"header_col_sep_visible_undefined,omitempty"`
	HeaderColHorizontalsVisible                     *TSS.SpecBoolArchive              `protobuf:"bytes,53,opt,name=header_col_horizontals_visible,json=headerColHorizontalsVisible" json:"header_col_horizontals_visible,omitempty"`
	HeaderColHorizontalsVisibleUndefined            *bool                             `protobuf:"varint,54,opt,name=header_col_horizontals_visible_undefined,json=headerColHorizontalsVisibleUndefined" json:"header_col_horizontals_visible_undefined,omitempty"`
	FooterSepVisible                                *TSS.SpecBoolArchive              `protobuf:"bytes,55,opt,name=footer_sep_visible,json=footerSepVisible" json:"footer_sep_visible,omitempty"`
	FooterSepVisibleUndefined                       *bool                             `protobuf:"varint,56,opt,name=footer_sep_visible_undefined,json=footerSepVisibleUndefined" json:"footer_sep_visible_undefined,omitempty"`
	FooterVerticalsVisible                          *TSS.SpecBoolArchive              `protobuf:"bytes,57,opt,name=footer_verticals_visible,json=footerVerticalsVisible" json:"footer_verticals_visible,omitempty"`
	FooterVerticalsVisibleUndefined                 *bool                             `protobuf:"varint,58,opt,name=footer_verticals_visible_undefined,json=footerVerticalsVisibleUndefined" json:"footer_verticals_visible_undefined,omitempty"`
	BorderStrokesVisible                            *TSS.SpecBoolArchive              `protobuf:"bytes,59,opt,name=border_strokes_visible,json=borderStrokesVisible" json:"border_strokes_visible,omitempty"`
	BorderStrokesVisibleUndefined                   *bool                             `protobuf:"varint,60,opt,name=border_strokes_visible_undefined,json=borderStrokesVisibleUndefined" json:"border_strokes_visible_undefined,omitempty"`
	MasterFontFamily                                *TSS.SpecStringArchive            `protobuf:"bytes,61,opt,name=master_font_family,json=masterFontFamily" json:"master_font_family,omitempty"`
	MasterFontFamilyUndefined                       *bool                             `protobuf:"varint,62,opt,name=master_font_family_undefined,json=masterFontFamilyUndefined" json:"master_font_family_undefined,omitempty"`
	WritingDirection                                *TSS.SpecIntegerArchive           `protobuf:"bytes,63,opt,name=writing_direction,json=writingDirection" json:"writing_direction,omitempty"`
	WritingDirectionUndefined                       *bool                             `protobuf:"varint,64,opt,name=writing_direction_undefined,json=writingDirectionUndefined" json:"writing_direction_undefined,omitempty"`
	CategoryLevel1TopStroke                         *TSD.SpecStrokeArchive            `protobuf:"bytes,65,opt,name=category_level1_top_stroke,json=categoryLevel1TopStroke" json:"category_level1_top_stroke,omitempty"`
	CategoryLevel1TopStrokeUndefined                *bool                             `protobuf:"varint,66,opt,name=category_level1_top_stroke_undefined,json=categoryLevel1TopStrokeUndefined" json:"category_level1_top_stroke_undefined,omitempty"`
	CategoryLevel2TopStroke                         *TSD.SpecStrokeArchive            `protobuf:"bytes,67,opt,name=category_level2_top_stroke,json=categoryLevel2TopStroke" json:"category_level2_top_stroke,omitempty"`
	CategoryLevel2TopStrokeUndefined                *bool                             `protobuf:"varint,68,opt,name=category_level2_top_stroke_undefined,json=categoryLevel2TopStrokeUndefined" json:"category_level2_top_stroke_undefined,omitempty"`
	CategoryLevel3TopStroke                         *TSD.SpecStrokeArchive            `protobuf:"bytes,69,opt,name=category_level3_top_stroke,json=categoryLevel3TopStroke" json:"category_level3_top_stroke,omitempty"`
	CategoryLevel3TopStrokeUndefined                *bool                             `protobuf:"varint,70,opt,name=category_level3_top_stroke_undefined,json=categoryLevel3TopStrokeUndefined" json:"category_level3_top_stroke_undefined,omitempty"`
	CategoryLevel4TopStroke                         *TSD.SpecStrokeArchive            `protobuf:"bytes,71,opt,name=category_level4_top_stroke,json=categoryLevel4TopStroke" json:"category_level4_top_stroke,omitempty"`
	CategoryLevel4TopStrokeUndefined                *bool                             `protobuf:"varint,72,opt,name=category_level4_top_stroke_undefined,json=categoryLevel4TopStrokeUndefined" json:"category_level4_top_stroke_undefined,omitempty"`
	CategoryLevel5TopStroke                         *TSD.SpecStrokeArchive            `protobuf:"bytes,73,opt,name=category_level5_top_stroke,json=categoryLevel5TopStroke" json:"category_level5_top_stroke,omitempty"`
	CategoryLevel5TopStrokeUndefined                *bool                             `protobuf:"varint,74,opt,name=category_level5_top_stroke_undefined,json=categoryLevel5TopStrokeUndefined" json:"category_level5_top_stroke_undefined,omitempty"`
	CategoryLevel1LabelSeparatorStroke              *TSD.SpecStrokeArchive            `protobuf:"bytes,75,opt,name=category_level1_label_separator_stroke,json=categoryLevel1LabelSeparatorStroke" json:"category_level1_label_separator_stroke,omitempty"`
	CategoryLevel1LabelSeparatorStrokeUndefined     *bool                             `protobuf:"varint,76,opt,name=category_level1_label_separator_stroke_undefined,json=categoryLevel1LabelSeparatorStrokeUndefined" json:"category_level1_label_separator_stroke_undefined,omitempty"`
	CategoryLevel2LabelSeparatorStroke              *TSD.SpecStrokeArchive            `protobuf:"bytes,77,opt,name=category_level2_label_separator_stroke,json=categoryLevel2LabelSeparatorStroke" json:"category_level2_label_separator_stroke,omitempty"`
	CategoryLevel2LabelSeparatorStrokeUndefined     *bool                             `protobuf:"varint,78,opt,name=category_level2_label_separator_stroke_undefined,json=categoryLevel2LabelSeparatorStrokeUndefined" json:"category_level2_label_separator_stroke_undefined,omitempty"`
	CategoryLevel3LabelSeparatorStroke              *TSD.SpecStrokeArchive            `protobuf:"bytes,79,opt,name=category_level3_label_separator_stroke,json=categoryLevel3LabelSeparatorStroke" json:"category_level3_label_separator_stroke,omitempty"`
	CategoryLevel3LabelSeparatorStrokeUndefined     *bool                             `protobuf:"varint,80,opt,name=category_level3_label_separator_stroke_undefined,json=categoryLevel3LabelSeparatorStrokeUndefined" json:"category_level3_label_separator_stroke_undefined,omitempty"`
	CategoryLevel4LabelSeparatorStroke              *TSD.SpecStrokeArchive            `protobuf:"bytes,81,opt,name=category_level4_label_separator_stroke,json=categoryLevel4LabelSeparatorStroke" json:"category_level4_label_separator_stroke,omitempty"`
	CategoryLevel4LabelSeparatorStrokeUndefined     *bool                             `protobuf:"varint,82,opt,name=category_level4_label_separator_stroke_undefined,json=categoryLevel4LabelSeparatorStrokeUndefined" json:"category_level4_label_separator_stroke_undefined,omitempty"`
	CategoryLevel5LabelSeparatorStroke              *TSD.SpecStrokeArchive            `protobuf:"bytes,83,opt,name=category_level5_label_separator_stroke,json=categoryLevel5LabelSeparatorStroke" json:"category_level5_label_separator_stroke,omitempty"`
	CategoryLevel5LabelSeparatorStrokeUndefined     *bool                             `protobuf:"varint,84,opt,name=category_level5_label_separator_stroke_undefined,json=categoryLevel5LabelSeparatorStrokeUndefined" json:"category_level5_label_separator_stroke_undefined,omitempty"`
	CategoryLevel1BottomStroke                      *TSD.SpecStrokeArchive            `protobuf:"bytes,85,opt,name=category_level1_bottom_stroke,json=categoryLevel1BottomStroke" json:"category_level1_bottom_stroke,omitempty"`
	CategoryLevel1BottomStrokeUndefined             *bool                             `protobuf:"varint,86,opt,name=category_level1_bottom_stroke_undefined,json=categoryLevel1BottomStrokeUndefined" json:"category_level1_bottom_stroke_undefined,omitempty"`
	CategoryLevel2BottomStroke                      *TSD.SpecStrokeArchive            `protobuf:"bytes,87,opt,name=category_level2_bottom_stroke,json=categoryLevel2BottomStroke" json:"category_level2_bottom_stroke,omitempty"`
	CategoryLevel2BottomStrokeUndefined             *bool                             `protobuf:"varint,88,opt,name=category_level2_bottom_stroke_undefined,json=categoryLevel2BottomStrokeUndefined" json:"category_level2_bottom_stroke_undefined,omitempty"`
	CategoryLevel3BottomStroke                      *TSD.SpecStrokeArchive            `protobuf:"bytes,89,opt,name=category_level3_bottom_stroke,json=categoryLevel3BottomStroke" json:"category_level3_bottom_stroke,omitempty"`
	CategoryLevel3BottomStrokeUndefined             *bool                             `protobuf:"varint,90,opt,name=category_level3_bottom_stroke_undefined,json=categoryLevel3BottomStrokeUndefined" json:"category_level3_bottom_stroke_undefined,omitempty"`
	CategoryLevel4BottomStroke                      *TSD.SpecStrokeArchive            `protobuf:"bytes,91,opt,name=category_level4_bottom_stroke,json=categoryLevel4BottomStroke" json:"category_level4_bottom_stroke,omitempty"`
	CategoryLevel4BottomStrokeUndefined             *bool                             `protobuf:"varint,92,opt,name=category_level4_bottom_stroke_undefined,json=categoryLevel4BottomStrokeUndefined" json:"category_level4_bottom_stroke_undefined,omitempty"`
	CategoryLevel5BottomStroke                      *TSD.SpecStrokeArchive            `protobuf:"bytes,93,opt,name=category_level5_bottom_stroke,json=categoryLevel5BottomStroke" json:"category_level5_bottom_stroke,omitempty"`
	CategoryLevel5BottomStrokeUndefined             *bool                             `protobuf:"varint,94,opt,name=category_level5_bottom_stroke_undefined,json=categoryLevel5BottomStrokeUndefined" json:"category_level5_bottom_stroke_undefined,omitempty"`
	CategoryLevel1InteriorStroke                    *TSD.SpecStrokeArchive            `protobuf:"bytes,95,opt,name=category_level1_interior_stroke,json=categoryLevel1InteriorStroke" json:"category_level1_interior_stroke,omitempty"`
	CategoryLevel1InteriorStrokeUndefined           *bool                             `protobuf:"varint,96,opt,name=category_level1_interior_stroke_undefined,json=categoryLevel1InteriorStrokeUndefined" json:"category_level1_interior_stroke_undefined,omitempty"`
	CategoryLevel2InteriorStroke                    *TSD.SpecStrokeArchive            `protobuf:"bytes,97,opt,name=category_level2_interior_stroke,json=categoryLevel2InteriorStroke" json:"category_level2_interior_stroke,omitempty"`
	CategoryLevel2InteriorStrokeUndefined           *bool                             `protobuf:"varint,98,opt,name=category_level2_interior_stroke_undefined,json=categoryLevel2InteriorStrokeUndefined" json:"category_level2_interior_stroke_undefined,omitempty"`
	CategoryLevel3InteriorStroke                    *TSD.SpecStrokeArchive            `protobuf:"bytes,99,opt,name=category_level3_interior_stroke,json=categoryLevel3InteriorStroke" json:"category_level3_interior_stroke,omitempty"`
	CategoryLevel3InteriorStrokeUndefined           *bool                             `protobuf:"varint,100,opt,name=category_level3_interior_stroke_undefined,json=categoryLevel3InteriorStrokeUndefined" json:"category_level3_interior_stroke_undefined,omitempty"`
	CategoryLevel4InteriorStroke                    *TSD.SpecStrokeArchive            `protobuf:"bytes,101,opt,name=category_level4_interior_stroke,json=categoryLevel4InteriorStroke" json:"category_level4_interior_stroke,omitempty"`
	CategoryLevel4InteriorStrokeUndefined           *bool                             `protobuf:"varint,102,opt,name=category_level4_interior_stroke_undefined,json=categoryLevel4InteriorStrokeUndefined" json:"category_level4_interior_stroke_undefined,omitempty"`
	CategoryLevel5InteriorStroke                    *TSD.SpecStrokeArchive            `protobuf:"bytes,103,opt,name=category_level5_interior_stroke,json=categoryLevel5InteriorStroke" json:"category_level5_interior_stroke,omitempty"`
	CategoryLevel5InteriorStrokeUndefined           *bool                             `protobuf:"varint,104,opt,name=category_level5_interior_stroke_undefined,json=categoryLevel5InteriorStrokeUndefined" json:"category_level5_interior_stroke_undefined,omitempty"`
	BodyPivotGroupHorizontalStroke                  *TSD.SpecStrokeArchive            `protobuf:"bytes,105,opt,name=body_pivot_group_horizontal_stroke,json=bodyPivotGroupHorizontalStroke" json:"body_pivot_group_horizontal_stroke,omitempty"`
	BodyPivotGroupHorizontalStrokeUndefined         *bool                             `protobuf:"varint,106,opt,name=body_pivot_group_horizontal_stroke_undefined,json=bodyPivotGroupHorizontalStrokeUndefined" json:"body_pivot_group_horizontal_stroke_undefined,omitempty"`
	BodyPivotGroupVerticalStroke                    *TSD.SpecStrokeArchive            `protobuf:"bytes,107,opt,name=body_pivot_group_vertical_stroke,json=bodyPivotGroupVerticalStroke" json:"body_pivot_group_vertical_stroke,omitempty"`
	BodyPivotGroupVerticalStrokeUndefined           *bool                             `protobuf:"varint,108,opt,name=body_pivot_group_vertical_stroke_undefined,json=bodyPivotGroupVerticalStrokeUndefined" json:"body_pivot_group_vertical_stroke_undefined,omitempty"`
	BodyPivotDeEmphasisHorizontalStroke             *TSD.SpecStrokeArchive            `protobuf:"bytes,109,opt,name=body_pivot_de_emphasis_horizontal_stroke,json=bodyPivotDeEmphasisHorizontalStroke" json:"body_pivot_de_emphasis_horizontal_stroke,omitempty"`
	BodyPivotDeEmphasisHorizontalStrokeUndefined    *bool                             `protobuf:"varint,110,opt,name=body_pivot_de_emphasis_horizontal_stroke_undefined,json=bodyPivotDeEmphasisHorizontalStrokeUndefined" json:"body_pivot_de_emphasis_horizontal_stroke_undefined,omitempty"`
	BodyPivotEmphasisVerticalStroke                 *TSD.SpecStrokeArchive            `protobuf:"bytes,111,opt,name=body_pivot_emphasis_vertical_stroke,json=bodyPivotEmphasisVerticalStroke" json:"body_pivot_emphasis_vertical_stroke,omitempty"`
	BodyPivotEmphasisVerticalStrokeUndefined        *bool                             `protobuf:"varint,112,opt,name=body_pivot_emphasis_vertical_stroke_undefined,json=bodyPivotEmphasisVerticalStrokeUndefined" json:"body_pivot_emphasis_vertical_stroke_undefined,omitempty"`
	HeaderColumnPivotGroupHorizontalStroke          *TSD.SpecStrokeArchive            `protobuf:"bytes,113,opt,name=header_column_pivot_group_horizontal_stroke,json=headerColumnPivotGroupHorizontalStroke" json:"header_column_pivot_group_horizontal_stroke,omitempty"`
	HeaderColumnPivotGroupHorizontalStrokeUndefined *bool                             `protobuf:"varint,114,opt,name=header_column_pivot_group_horizontal_stroke_undefined,json=headerColumnPivotGroupHorizontalStrokeUndefined" json:"header_column_pivot_group_horizontal_stroke_undefined,omitempty"`
	HeaderColumnPivotGroupDeEmphasisStroke          *TSD.SpecStrokeArchive            `protobuf:"bytes,115,opt,name=header_column_pivot_group_de_emphasis_stroke,json=headerColumnPivotGroupDeEmphasisStroke" json:"header_column_pivot_group_de_emphasis_stroke,omitempty"`
	HeaderColumnPivotGroupDeEmphasisStrokeUndefined *bool                             `protobuf:"varint,116,opt,name=header_column_pivot_group_de_emphasis_stroke_undefined,json=headerColumnPivotGroupDeEmphasisStrokeUndefined" json:"header_column_pivot_group_de_emphasis_stroke_undefined,omitempty"`
	HeaderColumnPivotSeparatorStroke                *TSD.SpecStrokeArchive            `protobuf:"bytes,117,opt,name=header_column_pivot_separator_stroke,json=headerColumnPivotSeparatorStroke" json:"header_column_pivot_separator_stroke,omitempty"`
	HeaderColumnPivotSeparatorStrokeUndefined       *bool                             `protobuf:"varint,118,opt,name=header_column_pivot_separator_stroke_undefined,json=headerColumnPivotSeparatorStrokeUndefined" json:"header_column_pivot_separator_stroke_undefined,omitempty"`
	HeaderRowPivotGroupVerticalStroke               *TSD.SpecStrokeArchive            `protobuf:"bytes,119,opt,name=header_row_pivot_group_vertical_stroke,json=headerRowPivotGroupVerticalStroke" json:"header_row_pivot_group_vertical_stroke,omitempty"`
	HeaderRowPivotGroupVerticalStrokeUndefined      *bool                             `protobuf:"varint,120,opt,name=header_row_pivot_group_vertical_stroke_undefined,json=headerRowPivotGroupVerticalStrokeUndefined" json:"header_row_pivot_group_vertical_stroke_undefined,omitempty"`
	HeaderRowPivotGroupDeEmphasisStroke             *TSD.SpecStrokeArchive            `protobuf:"bytes,121,opt,name=header_row_pivot_group_de_emphasis_stroke,json=headerRowPivotGroupDeEmphasisStroke" json:"header_row_pivot_group_de_emphasis_stroke,omitempty"`
	HeaderRowPivotGroupDeEmphasisStrokeUndefined    *bool                             `protobuf:"varint,122,opt,name=header_row_pivot_group_de_emphasis_stroke_undefined,json=headerRowPivotGroupDeEmphasisStrokeUndefined" json:"header_row_pivot_group_de_emphasis_stroke_undefined,omitempty"`
	HeaderRowPivotTitleStroke                       *TSD.SpecStrokeArchive            `protobuf:"bytes,123,opt,name=header_row_pivot_title_stroke,json=headerRowPivotTitleStroke" json:"header_row_pivot_title_stroke,omitempty"`
	HeaderRowPivotTitleStrokeUndefined              *bool                             `protobuf:"varint,124,opt,name=header_row_pivot_title_stroke_undefined,json=headerRowPivotTitleStrokeUndefined" json:"header_row_pivot_title_stroke_undefined,omitempty"`
	FooterRowPivotGroupVerticalStroke               *TSD.SpecStrokeArchive            `protobuf:"bytes,125,opt,name=footer_row_pivot_group_vertical_stroke,json=footerRowPivotGroupVerticalStroke" json:"footer_row_pivot_group_vertical_stroke,omitempty"`
	FooterRowPivotGroupVerticalStrokeUndefined      *bool                             `protobuf:"varint,126,opt,name=footer_row_pivot_group_vertical_stroke_undefined,json=footerRowPivotGroupVerticalStrokeUndefined" json:"footer_row_pivot_group_vertical_stroke_undefined,omitempty"`
	unknownFields                                   protoimpl.UnknownFields
	sizeCache                                       protoimpl.SizeCache
}

func (x *TableStylePropertyChangeSetArchive) Reset() {
	*x = TableStylePropertyChangeSetArchive{}
	mi := &file_TSTArchives_sos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableStylePropertyChangeSetArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableStylePropertyChangeSetArchive) ProtoMessage() {}

func (x *TableStylePropertyChangeSetArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSTArchives_sos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableStylePropertyChangeSetArchive.ProtoReflect.Descriptor instead.
func (*TableStylePropertyChangeSetArchive) Descriptor() ([]byte, []int) {
	return file_TSTArchives_sos_proto_rawDescGZIP(), []int{3}
}

func (x *TableStylePropertyChangeSetArchive) GetAutoResize() *TSS.SpecBoolArchive {
	if x != nil {
		return x.AutoResize
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetAutoResizeUndefined() bool {
	if x != nil && x.AutoResizeUndefined != nil {
		return *x.AutoResizeUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetBandedRows() *TSS.SpecBoolArchive {
	if x != nil {
		return x.BandedRows
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetBandedRowsUndefined() bool {
	if x != nil && x.BandedRowsUndefined != nil {
		return *x.BandedRowsUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetBandedCellFill() *TSD.SpecFillArchive {
	if x != nil {
		return x.BandedCellFill
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetBandedCellFillUndefined() bool {
	if x != nil && x.BandedCellFillUndefined != nil {
		return *x.BandedCellFillUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetBehavesLikeSpreadsheet() *TSS.SpecBoolArchive {
	if x != nil {
		return x.BehavesLikeSpreadsheet
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetBehavesLikeSpreadsheetUndefined() bool {
	if x != nil && x.BehavesLikeSpreadsheetUndefined != nil {
		return *x.BehavesLikeSpreadsheetUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetBodyHorizontalBorderStroke() *TSD.SpecStrokeArchive {
	if x != nil {
		return x.BodyHorizontalBorderStroke
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetBodyHorizontalBorderStrokeUndefined() bool {
	if x != nil && x.BodyHorizontalBorderStrokeUndefined != nil {
		return *x.BodyHorizontalBorderStrokeUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetBodyVerticalBorderStroke() *TSD.SpecStrokeArchive {
	if x != nil {
		return x.BodyVerticalBorderStroke
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetBodyVerticalBorderStrokeUndefined() bool {
	if x != nil && x.BodyVerticalBorderStrokeUndefined != nil {
		return *x.BodyVerticalBorderStrokeUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetBodyHorizontalStroke() *TSD.SpecStrokeArchive {
	if x != nil {
		return x.BodyHorizontalStroke
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetBodyHorizontalStrokeUndefined() bool {
	if x != nil && x.BodyHorizontalStrokeUndefined != nil {
		return *x.BodyHorizontalStrokeUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetBodyVerticalStroke() *TSD.SpecStrokeArchive {
	if x != nil {
		return x.BodyVerticalStroke
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetBodyVerticalStrokeUndefined() bool {
	if x != nil && x.BodyVerticalStrokeUndefined != nil {
		return *x.BodyVerticalStrokeUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetHeaderColumnBorderStroke() *TSD.SpecStrokeArchive {
	if x != nil {
		return x.HeaderColumnBorderStroke
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetHeaderColumnBorderStrokeUndefined() bool {
	if x != nil && x.HeaderColumnBorderStrokeUndefined != nil {
		return *x.HeaderColumnBorderStrokeUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetHeaderColumnVerticalStroke() *TSD.SpecStrokeArchive {
	if x != nil {
		return x.HeaderColumnVerticalStroke
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetHeaderColumnVerticalStrokeUndefined() bool {
	if x != nil && x.HeaderColumnVerticalStrokeUndefined != nil {
		return *x.HeaderColumnVerticalStrokeUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetHeaderColumnHorizontalStroke() *TSD.SpecStrokeArchive {
	if x != nil {
		return x.HeaderColumnHorizontalStroke
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetHeaderColumnHorizontalStrokeUndefined() bool {
	if x != nil && x.HeaderColumnHorizontalStrokeUndefined != nil {
		return *x.HeaderColumnHorizontalStrokeUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetHeaderColumnSeparatorStroke() *TSD.SpecStrokeArchive {
	if x != nil {
		return x.HeaderColumnSeparatorStroke
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetHeaderColumnSeparatorStrokeUndefined() bool {
	if x != nil && x.HeaderColumnSeparatorStrokeUndefined != nil {
		return *x.HeaderColumnSeparatorStrokeUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetHeaderRowBorderStroke() *TSD.SpecStrokeArchive {
	if x != nil {
		return x.HeaderRowBorderStroke
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetHeaderRowBorderStrokeUndefined() bool {
	if x != nil && x.HeaderRowBorderStrokeUndefined != nil {
		return *x.HeaderRowBorderStrokeUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetHeaderRowHorizontalStroke() *TSD.SpecStrokeArchive {
	if x != nil {
		return x.HeaderRowHorizontalStroke
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetHeaderRowHorizontalStrokeUndefined() bool {
	if x != nil && x.HeaderRowHorizontalStrokeUndefined != nil {
		return *x.HeaderRowHorizontalStrokeUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetHeaderRowVerticalStroke() *TSD.SpecStrokeArchive {
	if x != nil {
		return x.HeaderRowVerticalStroke
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetHeaderRowVerticalStrokeUndefined() bool {
	if x != nil && x.HeaderRowVerticalStrokeUndefined != nil {
		return *x.HeaderRowVerticalStrokeUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetHeaderRowSeparatorStroke() *TSD.SpecStrokeArchive {
	if x != nil {
		return x.HeaderRowSeparatorStroke
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetHeaderRowSeparatorStrokeUndefined() bool {
	if x != nil && x.HeaderRowSeparatorStrokeUndefined != nil {
		return *x.HeaderRowSeparatorStrokeUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetFooterRowBorderStroke() *TSD.SpecStrokeArchive {
	if x != nil {
		return x.FooterRowBorderStroke
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetFooterRowBorderStrokeUndefined() bool {
	if x != nil && x.FooterRowBorderStrokeUndefined != nil {
		return *x.FooterRowBorderStrokeUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetFooterRowHorizontalStroke() *TSD.SpecStrokeArchive {
	if x != nil {
		return x.FooterRowHorizontalStroke
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetFooterRowHorizontalStrokeUndefined() bool {
	if x != nil && x.FooterRowHorizontalStrokeUndefined != nil {
		return *x.FooterRowHorizontalStrokeUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetFooterRowVerticalStroke() *TSD.SpecStrokeArchive {
	if x != nil {
		return x.FooterRowVerticalStroke
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetFooterRowVerticalStrokeUndefined() bool {
	if x != nil && x.FooterRowVerticalStrokeUndefined != nil {
		return *x.FooterRowVerticalStrokeUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetFooterRowSeparatorStroke() *TSD.SpecStrokeArchive {
	if x != nil {
		return x.FooterRowSeparatorStroke
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetFooterRowSeparatorStrokeUndefined() bool {
	if x != nil && x.FooterRowSeparatorStrokeUndefined != nil {
		return *x.FooterRowSeparatorStrokeUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetStrokePresetListObject() *SpecTableStrokePresetListArchive {
	if x != nil {
		return x.StrokePresetListObject
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetStrokePresetListObjectUndefined() bool {
	if x != nil && x.StrokePresetListObjectUndefined != nil {
		return *x.StrokePresetListObjectUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetVerticalStrokesVisible() *TSS.SpecBoolArchive {
	if x != nil {
		return x.VerticalStrokesVisible
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetVerticalStrokesVisibleUndefined() bool {
	if x != nil && x.VerticalStrokesVisibleUndefined != nil {
		return *x.VerticalStrokesVisibleUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetHorizontalStrokesVisible() *TSS.SpecBoolArchive {
	if x != nil {
		return x.HorizontalStrokesVisible
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetHorizontalStrokesVisibleUndefined() bool {
	if x != nil && x.HorizontalStrokesVisibleUndefined != nil {
		return *x.HorizontalStrokesVisibleUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetHeaderRowSepVisible() *TSS.SpecBoolArchive {
	if x != nil {
		return x.HeaderRowSepVisible
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetHeaderRowSepVisibleUndefined() bool {
	if x != nil && x.HeaderRowSepVisibleUndefined != nil {
		return *x.HeaderRowSepVisibleUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetHeaderRowVerticalsVisible() *TSS.SpecBoolArchive {
	if x != nil {
		return x.HeaderRowVerticalsVisible
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetHeaderRowVerticalsVisibleUndefined() bool {
	if x != nil && x.HeaderRowVerticalsVisibleUndefined != nil {
		return *x.HeaderRowVerticalsVisibleUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetHeaderColSepVisible() *TSS.SpecBoolArchive {
	if x != nil {
		return x.HeaderColSepVisible
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetHeaderColSepVisibleUndefined() bool {
	if x != nil && x.HeaderColSepVisibleUndefined != nil {
		return *x.HeaderColSepVisibleUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetHeaderColHorizontalsVisible() *TSS.SpecBoolArchive {
	if x != nil {
		return x.HeaderColHorizontalsVisible
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetHeaderColHorizontalsVisibleUndefined() bool {
	if x != nil && x.HeaderColHorizontalsVisibleUndefined != nil {
		return *x.HeaderColHorizontalsVisibleUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetFooterSepVisible() *TSS.SpecBoolArchive {
	if x != nil {
		return x.FooterSepVisible
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetFooterSepVisibleUndefined() bool {
	if x != nil && x.FooterSepVisibleUndefined != nil {
		return *x.FooterSepVisibleUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetFooterVerticalsVisible() *TSS.SpecBoolArchive {
	if x != nil {
		return x.FooterVerticalsVisible
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetFooterVerticalsVisibleUndefined() bool {
	if x != nil && x.FooterVerticalsVisibleUndefined != nil {
		return *x.FooterVerticalsVisibleUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetBorderStrokesVisible() *TSS.SpecBoolArchive {
	if x != nil {
		return x.BorderStrokesVisible
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetBorderStrokesVisibleUndefined() bool {
	if x != nil && x.BorderStrokesVisibleUndefined != nil {
		return *x.BorderStrokesVisibleUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetMasterFontFamily() *TSS.SpecStringArchive {
	if x != nil {
		return x.MasterFontFamily
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetMasterFontFamilyUndefined() bool {
	if x != nil && x.MasterFontFamilyUndefined != nil {
		return *x.MasterFontFamilyUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetWritingDirection() *TSS.SpecIntegerArchive {
	if x != nil {
		return x.WritingDirection
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetWritingDirectionUndefined() bool {
	if x != nil && x.WritingDirectionUndefined != nil {
		return *x.WritingDirectionUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetCategoryLevel1TopStroke() *TSD.SpecStrokeArchive {
	if x != nil {
		return x.CategoryLevel1TopStroke
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetCategoryLevel1TopStrokeUndefined() bool {
	if x != nil && x.CategoryLevel1TopStrokeUndefined != nil {
		return *x.CategoryLevel1TopStrokeUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetCategoryLevel2TopStroke() *TSD.SpecStrokeArchive {
	if x != nil {
		return x.CategoryLevel2TopStroke
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetCategoryLevel2TopStrokeUndefined() bool {
	if x != nil && x.CategoryLevel2TopStrokeUndefined != nil {
		return *x.CategoryLevel2TopStrokeUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetCategoryLevel3TopStroke() *TSD.SpecStrokeArchive {
	if x != nil {
		return x.CategoryLevel3TopStroke
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetCategoryLevel3TopStrokeUndefined() bool {
	if x != nil && x.CategoryLevel3TopStrokeUndefined != nil {
		return *x.CategoryLevel3TopStrokeUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetCategoryLevel4TopStroke() *TSD.SpecStrokeArchive {
	if x != nil {
		return x.CategoryLevel4TopStroke
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetCategoryLevel4TopStrokeUndefined() bool {
	if x != nil && x.CategoryLevel4TopStrokeUndefined != nil {
		return *x.CategoryLevel4TopStrokeUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetCategoryLevel5TopStroke() *TSD.SpecStrokeArchive {
	if x != nil {
		return x.CategoryLevel5TopStroke
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetCategoryLevel5TopStrokeUndefined() bool {
	if x != nil && x.CategoryLevel5TopStrokeUndefined != nil {
		return *x.CategoryLevel5TopStrokeUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetCategoryLevel1LabelSeparatorStroke() *TSD.SpecStrokeArchive {
	if x != nil {
		return x.CategoryLevel1LabelSeparatorStroke
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetCategoryLevel1LabelSeparatorStrokeUndefined() bool {
	if x != nil && x.CategoryLevel1LabelSeparatorStrokeUndefined != nil {
		return *x.CategoryLevel1LabelSeparatorStrokeUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetCategoryLevel2LabelSeparatorStroke() *TSD.SpecStrokeArchive {
	if x != nil {
		return x.CategoryLevel2LabelSeparatorStroke
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetCategoryLevel2LabelSeparatorStrokeUndefined() bool {
	if x != nil && x.CategoryLevel2LabelSeparatorStrokeUndefined != nil {
		return *x.CategoryLevel2LabelSeparatorStrokeUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetCategoryLevel3LabelSeparatorStroke() *TSD.SpecStrokeArchive {
	if x != nil {
		return x.CategoryLevel3LabelSeparatorStroke
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetCategoryLevel3LabelSeparatorStrokeUndefined() bool {
	if x != nil && x.CategoryLevel3LabelSeparatorStrokeUndefined != nil {
		return *x.CategoryLevel3LabelSeparatorStrokeUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetCategoryLevel4LabelSeparatorStroke() *TSD.SpecStrokeArchive {
	if x != nil {
		return x.CategoryLevel4LabelSeparatorStroke
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetCategoryLevel4LabelSeparatorStrokeUndefined() bool {
	if x != nil && x.CategoryLevel4LabelSeparatorStrokeUndefined != nil {
		return *x.CategoryLevel4LabelSeparatorStrokeUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetCategoryLevel5LabelSeparatorStroke() *TSD.SpecStrokeArchive {
	if x != nil {
		return x.CategoryLevel5LabelSeparatorStroke
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetCategoryLevel5LabelSeparatorStrokeUndefined() bool {
	if x != nil && x.CategoryLevel5LabelSeparatorStrokeUndefined != nil {
		return *x.CategoryLevel5LabelSeparatorStrokeUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetCategoryLevel1BottomStroke() *TSD.SpecStrokeArchive {
	if x != nil {
		return x.CategoryLevel1BottomStroke
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetCategoryLevel1BottomStrokeUndefined() bool {
	if x != nil && x.CategoryLevel1BottomStrokeUndefined != nil {
		return *x.CategoryLevel1BottomStrokeUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetCategoryLevel2BottomStroke() *TSD.SpecStrokeArchive {
	if x != nil {
		return x.CategoryLevel2BottomStroke
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetCategoryLevel2BottomStrokeUndefined() bool {
	if x != nil && x.CategoryLevel2BottomStrokeUndefined != nil {
		return *x.CategoryLevel2BottomStrokeUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetCategoryLevel3BottomStroke() *TSD.SpecStrokeArchive {
	if x != nil {
		return x.CategoryLevel3BottomStroke
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetCategoryLevel3BottomStrokeUndefined() bool {
	if x != nil && x.CategoryLevel3BottomStrokeUndefined != nil {
		return *x.CategoryLevel3BottomStrokeUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetCategoryLevel4BottomStroke() *TSD.SpecStrokeArchive {
	if x != nil {
		return x.CategoryLevel4BottomStroke
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetCategoryLevel4BottomStrokeUndefined() bool {
	if x != nil && x.CategoryLevel4BottomStrokeUndefined != nil {
		return *x.CategoryLevel4BottomStrokeUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetCategoryLevel5BottomStroke() *TSD.SpecStrokeArchive {
	if x != nil {
		return x.CategoryLevel5BottomStroke
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetCategoryLevel5BottomStrokeUndefined() bool {
	if x != nil && x.CategoryLevel5BottomStrokeUndefined != nil {
		return *x.CategoryLevel5BottomStrokeUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetCategoryLevel1InteriorStroke() *TSD.SpecStrokeArchive {
	if x != nil {
		return x.CategoryLevel1InteriorStroke
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetCategoryLevel1InteriorStrokeUndefined() bool {
	if x != nil && x.CategoryLevel1InteriorStrokeUndefined != nil {
		return *x.CategoryLevel1InteriorStrokeUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetCategoryLevel2InteriorStroke() *TSD.SpecStrokeArchive {
	if x != nil {
		return x.CategoryLevel2InteriorStroke
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetCategoryLevel2InteriorStrokeUndefined() bool {
	if x != nil && x.CategoryLevel2InteriorStrokeUndefined != nil {
		return *x.CategoryLevel2InteriorStrokeUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetCategoryLevel3InteriorStroke() *TSD.SpecStrokeArchive {
	if x != nil {
		return x.CategoryLevel3InteriorStroke
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetCategoryLevel3InteriorStrokeUndefined() bool {
	if x != nil && x.CategoryLevel3InteriorStrokeUndefined != nil {
		return *x.CategoryLevel3InteriorStrokeUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetCategoryLevel4InteriorStroke() *TSD.SpecStrokeArchive {
	if x != nil {
		return x.CategoryLevel4InteriorStroke
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetCategoryLevel4InteriorStrokeUndefined() bool {
	if x != nil && x.CategoryLevel4InteriorStrokeUndefined != nil {
		return *x.CategoryLevel4InteriorStrokeUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetCategoryLevel5InteriorStroke() *TSD.SpecStrokeArchive {
	if x != nil {
		return x.CategoryLevel5InteriorStroke
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetCategoryLevel5InteriorStrokeUndefined() bool {
	if x != nil && x.CategoryLevel5InteriorStrokeUndefined != nil {
		return *x.CategoryLevel5InteriorStrokeUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetBodyPivotGroupHorizontalStroke() *TSD.SpecStrokeArchive {
	if x != nil {
		return x.BodyPivotGroupHorizontalStroke
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetBodyPivotGroupHorizontalStrokeUndefined() bool {
	if x != nil && x.BodyPivotGroupHorizontalStrokeUndefined != nil {
		return *x.BodyPivotGroupHorizontalStrokeUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetBodyPivotGroupVerticalStroke() *TSD.SpecStrokeArchive {
	if x != nil {
		return x.BodyPivotGroupVerticalStroke
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetBodyPivotGroupVerticalStrokeUndefined() bool {
	if x != nil && x.BodyPivotGroupVerticalStrokeUndefined != nil {
		return *x.BodyPivotGroupVerticalStrokeUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetBodyPivotDeEmphasisHorizontalStroke() *TSD.SpecStrokeArchive {
	if x != nil {
		return x.BodyPivotDeEmphasisHorizontalStroke
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetBodyPivotDeEmphasisHorizontalStrokeUndefined() bool {
	if x != nil && x.BodyPivotDeEmphasisHorizontalStrokeUndefined != nil {
		return *x.BodyPivotDeEmphasisHorizontalStrokeUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetBodyPivotEmphasisVerticalStroke() *TSD.SpecStrokeArchive {
	if x != nil {
		return x.BodyPivotEmphasisVerticalStroke
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetBodyPivotEmphasisVerticalStrokeUndefined() bool {
	if x != nil && x.BodyPivotEmphasisVerticalStrokeUndefined != nil {
		return *x.BodyPivotEmphasisVerticalStrokeUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetHeaderColumnPivotGroupHorizontalStroke() *TSD.SpecStrokeArchive {
	if x != nil {
		return x.HeaderColumnPivotGroupHorizontalStroke
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetHeaderColumnPivotGroupHorizontalStrokeUndefined() bool {
	if x != nil && x.HeaderColumnPivotGroupHorizontalStrokeUndefined != nil {
		return *x.HeaderColumnPivotGroupHorizontalStrokeUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetHeaderColumnPivotGroupDeEmphasisStroke() *TSD.SpecStrokeArchive {
	if x != nil {
		return x.HeaderColumnPivotGroupDeEmphasisStroke
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetHeaderColumnPivotGroupDeEmphasisStrokeUndefined() bool {
	if x != nil && x.HeaderColumnPivotGroupDeEmphasisStrokeUndefined != nil {
		return *x.HeaderColumnPivotGroupDeEmphasisStrokeUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetHeaderColumnPivotSeparatorStroke() *TSD.SpecStrokeArchive {
	if x != nil {
		return x.HeaderColumnPivotSeparatorStroke
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetHeaderColumnPivotSeparatorStrokeUndefined() bool {
	if x != nil && x.HeaderColumnPivotSeparatorStrokeUndefined != nil {
		return *x.HeaderColumnPivotSeparatorStrokeUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetHeaderRowPivotGroupVerticalStroke() *TSD.SpecStrokeArchive {
	if x != nil {
		return x.HeaderRowPivotGroupVerticalStroke
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetHeaderRowPivotGroupVerticalStrokeUndefined() bool {
	if x != nil && x.HeaderRowPivotGroupVerticalStrokeUndefined != nil {
		return *x.HeaderRowPivotGroupVerticalStrokeUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetHeaderRowPivotGroupDeEmphasisStroke() *TSD.SpecStrokeArchive {
	if x != nil {
		return x.HeaderRowPivotGroupDeEmphasisStroke
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetHeaderRowPivotGroupDeEmphasisStrokeUndefined() bool {
	if x != nil && x.HeaderRowPivotGroupDeEmphasisStrokeUndefined != nil {
		return *x.HeaderRowPivotGroupDeEmphasisStrokeUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetHeaderRowPivotTitleStroke() *TSD.SpecStrokeArchive {
	if x != nil {
		return x.HeaderRowPivotTitleStroke
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetHeaderRowPivotTitleStrokeUndefined() bool {
	if x != nil && x.HeaderRowPivotTitleStrokeUndefined != nil {
		return *x.HeaderRowPivotTitleStrokeUndefined
	}
	return false
}

func (x *TableStylePropertyChangeSetArchive) GetFooterRowPivotGroupVerticalStroke() *TSD.SpecStrokeArchive {
	if x != nil {
		return x.FooterRowPivotGroupVerticalStroke
	}
	return nil
}

func (x *TableStylePropertyChangeSetArchive) GetFooterRowPivotGroupVerticalStrokeUndefined() bool {
	if x != nil && x.FooterRowPivotGroupVerticalStrokeUndefined != nil {
		return *x.FooterRowPivotGroupVerticalStrokeUndefined
	}
	return false
}

var File_TSTArchives_sos_proto protoreflect.FileDescriptor

const file_TSTArchives_sos_proto_rawDesc = "" +
	"\n" +
	"\x15TSTArchives.sos.proto\x12\x03TST\x1a\x15TSDArchives.sos.proto\x1a\x15TSSArchives.sos.proto\x1a\x1fTSTStylePropertyArchiving.proto\x1a\x16TSWPArchives.sos.proto\"\x92\x01\n" +
	"#SpecSetTableStrokePresetListArchive\x12U\n" +
	"\x18table_stroke_preset_list\x18\x01 \x01(\v2\x1c.TST.StrokePresetListArchiveR\x15tableStrokePresetList\x12\x14\n" +
	"\x05unset\x18\x02 \x02(\bR\x05unset\"\x95\x01\n" +
	" SpecTableStrokePresetListArchive\x12q\n" +
	"!spec_set_table_stroke_preset_list\x18\x01 \x01(\v2(.TST.SpecSetTableStrokePresetListArchiveR\x1cspecSetTableStrokePresetList\"\x9b\x04\n" +
	"&TableCellStylePropertyChangeSetArchive\x121\n" +
	"\ttext_wrap\x18\x01 \x01(\v2\x14.TSS.SpecBoolArchiveR\btextWrap\x12.\n" +
	"\x13text_wrap_undefined\x18\x02 \x01(\bR\x11textWrapUndefined\x12+\n" +
	"\x04type\x18\x03 \x01(\v2\x17.TSS.SpecIntegerArchiveR\x04type\x12%\n" +
	"\x0etype_undefined\x18\x04 \x01(\bR\rtypeUndefined\x12(\n" +
	"\x04fill\x18\x05 \x01(\v2\x14.TSD.SpecFillArchiveR\x04fill\x12%\n" +
	"\x0efill_undefined\x18\x06 \x01(\bR\rfillUndefined\x12F\n" +
	"\x12vertical_alignment\x18\a \x01(\v2\x17.TSS.SpecIntegerArchiveR\x11verticalAlignment\x12@\n" +
	"\x1cvertical_alignment_undefined\x18\b \x01(\bR\x1averticalAlignmentUndefined\x122\n" +
	"\apadding\x18\t \x01(\v2\x18.TSWP.SpecPaddingArchiveR\apadding\x12+\n" +
	"\x11padding_undefined\x18\n" +
	" \x01(\bR\x10paddingUndefined\"\x91V\n" +
	"\"TableStylePropertyChangeSetArchive\x125\n" +
	"\vauto_resize\x18\x01 \x01(\v2\x14.TSS.SpecBoolArchiveR\n" +
	"autoResize\x122\n" +
	"\x15auto_resize_undefined\x18\x02 \x01(\bR\x13autoResizeUndefined\x125\n" +
	"\vbanded_rows\x18\x03 \x01(\v2\x14.TSS.SpecBoolArchiveR\n" +
	"bandedRows\x122\n" +
	"\x15banded_rows_undefined\x18\x04 \x01(\bR\x13bandedRowsUndefined\x12>\n" +
	"\x10banded_cell_fill\x18\x05 \x01(\v2\x14.TSD.SpecFillArchiveR\x0ebandedCellFill\x12;\n" +
	"\x1abanded_cell_fill_undefined\x18\x06 \x01(\bR\x17bandedCellFillUndefined\x12N\n" +
	"\x18behaves_like_spreadsheet\x18\a \x01(\v2\x14.TSS.SpecBoolArchiveR\x16behavesLikeSpreadsheet\x12K\n" +
	"\"behaves_like_spreadsheet_undefined\x18\b \x01(\bR\x1fbehavesLikeSpreadsheetUndefined\x12Y\n" +
	"\x1dbody_horizontal_border_stroke\x18\t \x01(\v2\x16.TSD.SpecStrokeArchiveR\x1abodyHorizontalBorderStroke\x12T\n" +
	"'body_horizontal_border_stroke_undefined\x18\n" +
	" \x01(\bR#bodyHorizontalBorderStrokeUndefined\x12U\n" +
	"\x1bbody_vertical_border_stroke\x18\v \x01(\v2\x16.TSD.SpecStrokeArchiveR\x18bodyVerticalBorderStroke\x12P\n" +
	"%body_vertical_border_stroke_undefined\x18\f \x01(\bR!bodyVerticalBorderStrokeUndefined\x12L\n" +
	"\x16body_horizontal_stroke\x18\r \x01(\v2\x16.TSD.SpecStrokeArchiveR\x14bodyHorizontalStroke\x12G\n" +
	" body_horizontal_stroke_undefined\x18\x0e \x01(\bR\x1dbodyHorizontalStrokeUndefined\x12H\n" +
	"\x14body_vertical_stroke\x18\x0f \x01(\v2\x16.TSD.SpecStrokeArchiveR\x12bodyVerticalStroke\x12C\n" +
	"\x1ebody_vertical_stroke_undefined\x18\x10 \x01(\bR\x1bbodyVerticalStrokeUndefined\x12U\n" +
	"\x1bheader_column_border_stroke\x18\x11 \x01(\v2\x16.TSD.SpecStrokeArchiveR\x18headerColumnBorderStroke\x12P\n" +
	"%header_column_border_stroke_undefined\x18\x12 \x01(\bR!headerColumnBorderStrokeUndefined\x12Y\n" +
	"\x1dheader_column_vertical_stroke\x18\x13 \x01(\v2\x16.TSD.SpecStrokeArchiveR\x1aheaderColumnVerticalStroke\x12T\n" +
	"'header_column_vertical_stroke_undefined\x18\x14 \x01(\bR#headerColumnVerticalStrokeUndefined\x12]\n" +
	"\x1fheader_column_horizontal_stroke\x18\x15 \x01(\v2\x16.TSD.SpecStrokeArchiveR\x1cheaderColumnHorizontalStroke\x12X\n" +
	")header_column_horizontal_stroke_undefined\x18\x16 \x01(\bR%headerColumnHorizontalStrokeUndefined\x12[\n" +
	"\x1eheader_column_separator_stroke\x18\x17 \x01(\v2\x16.TSD.SpecStrokeArchiveR\x1bheaderColumnSeparatorStroke\x12V\n" +
	"(header_column_separator_stroke_undefined\x18\x18 \x01(\bR$headerColumnSeparatorStrokeUndefined\x12O\n" +
	"\x18header_row_border_stroke\x18\x19 \x01(\v2\x16.TSD.SpecStrokeArchiveR\x15headerRowBorderStroke\x12J\n" +
	"\"header_row_border_stroke_undefined\x18\x1a \x01(\bR\x1eheaderRowBorderStrokeUndefined\x12W\n" +
	"\x1cheader_row_horizontal_stroke\x18\x1b \x01(\v2\x16.TSD.SpecStrokeArchiveR\x19headerRowHorizontalStroke\x12R\n" +
	"&header_row_horizontal_stroke_undefined\x18\x1c \x01(\bR\"headerRowHorizontalStrokeUndefined\x12S\n" +
	"\x1aheader_row_vertical_stroke\x18\x1d \x01(\v2\x16.TSD.SpecStrokeArchiveR\x17headerRowVerticalStroke\x12N\n" +
	"$header_row_vertical_stroke_undefined\x18\x1e \x01(\bR headerRowVerticalStrokeUndefined\x12U\n" +
	"\x1bheader_row_separator_stroke\x18\x1f \x01(\v2\x16.TSD.SpecStrokeArchiveR\x18headerRowSeparatorStroke\x12P\n" +
	"%header_row_separator_stroke_undefined\x18  \x01(\bR!headerRowSeparatorStrokeUndefined\x12O\n" +
	"\x18footer_row_border_stroke\x18! \x01(\v2\x16.TSD.SpecStrokeArchiveR\x15footerRowBorderStroke\x12J\n" +
	"\"footer_row_border_stroke_undefined\x18\" \x01(\bR\x1efooterRowBorderStrokeUndefined\x12W\n" +
	"\x1cfooter_row_horizontal_stroke\x18# \x01(\v2\x16.TSD.SpecStrokeArchiveR\x19footerRowHorizontalStroke\x12R\n" +
	"&footer_row_horizontal_stroke_undefined\x18$ \x01(\bR\"footerRowHorizontalStrokeUndefined\x12S\n" +
	"\x1afooter_row_vertical_stroke\x18% \x01(\v2\x16.TSD.SpecStrokeArchiveR\x17footerRowVerticalStroke\x12N\n" +
	"$footer_row_vertical_stroke_undefined\x18& \x01(\bR footerRowVerticalStrokeUndefined\x12U\n" +
	"\x1bfooter_row_separator_stroke\x18' \x01(\v2\x16.TSD.SpecStrokeArchiveR\x18footerRowSeparatorStroke\x12P\n" +
	"%footer_row_separator_stroke_undefined\x18( \x01(\bR!footerRowSeparatorStrokeUndefined\x12`\n" +
	"\x19stroke_preset_list_object\x18) \x01(\v2%.TST.SpecTableStrokePresetListArchiveR\x16strokePresetListObject\x12L\n" +
	"#stroke_preset_list_object_undefined\x18* \x01(\bR\x1fstrokePresetListObjectUndefined\x12N\n" +
	"\x18vertical_strokes_visible\x18+ \x01(\v2\x14.TSS.SpecBoolArchiveR\x16verticalStrokesVisible\x12K\n" +
	"\"vertical_strokes_visible_undefined\x18, \x01(\bR\x1fverticalStrokesVisibleUndefined\x12R\n" +
	"\x1ahorizontal_strokes_visible\x18- \x01(\v2\x14.TSS.SpecBoolArchiveR\x18horizontalStrokesVisible\x12O\n" +
	"$horizontal_strokes_visible_undefined\x18. \x01(\bR!horizontalStrokesVisibleUndefined\x12I\n" +
	"\x16header_row_sep_visible\x18/ \x01(\v2\x14.TSS.SpecBoolArchiveR\x13headerRowSepVisible\x12F\n" +
	" header_row_sep_visible_undefined\x180 \x01(\bR\x1cheaderRowSepVisibleUndefined\x12U\n" +
	"\x1cheader_row_verticals_visible\x181 \x01(\v2\x14.TSS.SpecBoolArchiveR\x19headerRowVerticalsVisible\x12R\n" +
	"&header_row_verticals_visible_undefined\x182 \x01(\bR\"headerRowVerticalsVisibleUndefined\x12I\n" +
	"\x16header_col_sep_visible\x183 \x01(\v2\x14.TSS.SpecBoolArchiveR\x13headerColSepVisible\x12F\n" +
	" header_col_sep_visible_undefined\x184 \x01(\bR\x1cheaderColSepVisibleUndefined\x12Y\n" +
	"\x1eheader_col_horizontals_visible\x185 \x01(\v2\x14.TSS.SpecBoolArchiveR\x1bheaderColHorizontalsVisible\x12V\n" +
	"(header_col_horizontals_visible_undefined\x186 \x01(\bR$headerColHorizontalsVisibleUndefined\x12B\n" +
	"\x12footer_sep_visible\x187 \x01(\v2\x14.TSS.SpecBoolArchiveR\x10footerSepVisible\x12?\n" +
	"\x1cfooter_sep_visible_undefined\x188 \x01(\bR\x19footerSepVisibleUndefined\x12N\n" +
	"\x18footer_verticals_visible\x189 \x01(\v2\x14.TSS.SpecBoolArchiveR\x16footerVerticalsVisible\x12K\n" +
	"\"footer_verticals_visible_undefined\x18: \x01(\bR\x1ffooterVerticalsVisibleUndefined\x12J\n" +
	"\x16border_strokes_visible\x18; \x01(\v2\x14.TSS.SpecBoolArchiveR\x14borderStrokesVisible\x12G\n" +
	" border_strokes_visible_undefined\x18< \x01(\bR\x1dborderStrokesVisibleUndefined\x12D\n" +
	"\x12master_font_family\x18= \x01(\v2\x16.TSS.SpecStringArchiveR\x10masterFontFamily\x12?\n" +
	"\x1cmaster_font_family_undefined\x18> \x01(\bR\x19masterFontFamilyUndefined\x12D\n" +
	"\x11writing_direction\x18? \x01(\v2\x17.TSS.SpecIntegerArchiveR\x10writingDirection\x12>\n" +
	"\x1bwriting_direction_undefined\x18@ \x01(\bR\x19writingDirectionUndefined\x12S\n" +
	"\x1acategory_level1_top_stroke\x18A \x01(\v2\x16.TSD.SpecStrokeArchiveR\x17categoryLevel1TopStroke\x12N\n" +
	"$category_level1_top_stroke_undefined\x18B \x01(\bR categoryLevel1TopStrokeUndefined\x12S\n" +
	"\x1acategory_level2_top_stroke\x18C \x01(\v2\x16.TSD.SpecStrokeArchiveR\x17categoryLevel2TopStroke\x12N\n" +
	"$category_level2_top_stroke_undefined\x18D \x01(\bR categoryLevel2TopStrokeUndefined\x12S\n" +
	"\x1acategory_level3_top_stroke\x18E \x01(\v2\x16.TSD.SpecStrokeArchiveR\x17categoryLevel3TopStroke\x12N\n" +
	"$category_level3_top_stroke_undefined\x18F \x01(\bR categoryLevel3TopStrokeUndefined\x12S\n" +
	"\x1acategory_level4_top_stroke\x18G \x01(\v2\x16.TSD.SpecStrokeArchiveR\x17categoryLevel4TopStroke\x12N\n" +
	"$category_level4_top_stroke_undefined\x18H \x01(\bR categoryLevel4TopStrokeUndefined\x12S\n" +
	"\x1acategory_level5_top_stroke\x18I \x01(\v2\x16.TSD.SpecStrokeArchiveR\x17categoryLevel5TopStroke\x12N\n" +
	"$category_level5_top_stroke_undefined\x18J \x01(\bR categoryLevel5TopStrokeUndefined\x12j\n" +
	"&category_level1_label_separator_stroke\x18K \x01(\v2\x16.TSD.SpecStrokeArchiveR\"categoryLevel1LabelSeparatorStroke\x12e\n" +
	"0category_level1_label_separator_stroke_undefined\x18L \x01(\bR+categoryLevel1LabelSeparatorStrokeUndefined\x12j\n" +
	"&category_level2_label_separator_stroke\x18M \x01(\v2\x16.TSD.SpecStrokeArchiveR\"categoryLevel2LabelSeparatorStroke\x12e\n" +
	"0category_level2_label_separator_stroke_undefined\x18N \x01(\bR+categoryLevel2LabelSeparatorStrokeUndefined\x12j\n" +
	"&category_level3_label_separator_stroke\x18O \x01(\v2\x16.TSD.SpecStrokeArchiveR\"categoryLevel3LabelSeparatorStroke\x12e\n" +
	"0category_level3_label_separator_stroke_undefined\x18P \x01(\bR+categoryLevel3LabelSeparatorStrokeUndefined\x12j\n" +
	"&category_level4_label_separator_stroke\x18Q \x01(\v2\x16.TSD.SpecStrokeArchiveR\"categoryLevel4LabelSeparatorStroke\x12e\n" +
	"0category_level4_label_separator_stroke_undefined\x18R \x01(\bR+categoryLevel4LabelSeparatorStrokeUndefined\x12j\n" +
	"&category_level5_label_separator_stroke\x18S \x01(\v2\x16.TSD.SpecStrokeArchiveR\"categoryLevel5LabelSeparatorStroke\x12e\n" +
	"0category_level5_label_separator_stroke_undefined\x18T \x01(\bR+categoryLevel5LabelSeparatorStrokeUndefined\x12Y\n" +
	"\x1dcategory_level1_bottom_stroke\x18U \x01(\v2\x16.TSD.SpecStrokeArchiveR\x1acategoryLevel1BottomStroke\x12T\n" +
	"'category_level1_bottom_stroke_undefined\x18V \x01(\bR#categoryLevel1BottomStrokeUndefined\x12Y\n" +
	"\x1dcategory_level2_bottom_stroke\x18W \x01(\v2\x16.TSD.SpecStrokeArchiveR\x1acategoryLevel2BottomStroke\x12T\n" +
	"'category_level2_bottom_stroke_undefined\x18X \x01(\bR#categoryLevel2BottomStrokeUndefined\x12Y\n" +
	"\x1dcategory_level3_bottom_stroke\x18Y \x01(\v2\x16.TSD.SpecStrokeArchiveR\x1acategoryLevel3BottomStroke\x12T\n" +
	"'category_level3_bottom_stroke_undefined\x18Z \x01(\bR#categoryLevel3BottomStrokeUndefined\x12Y\n" +
	"\x1dcategory_level4_bottom_stroke\x18[ \x01(\v2\x16.TSD.SpecStrokeArchiveR\x1acategoryLevel4BottomStroke\x12T\n" +
	"'category_level4_bottom_stroke_undefined\x18\\ \x01(\bR#categoryLevel4BottomStrokeUndefined\x12Y\n" +
	"\x1dcategory_level5_bottom_stroke\x18] \x01(\v2\x16.TSD.SpecStrokeArchiveR\x1acategoryLevel5BottomStroke\x12T\n" +
	"'category_level5_bottom_stroke_undefined\x18^ \x01(\bR#categoryLevel5BottomStrokeUndefined\x12]\n" +
	"\x1fcategory_level1_interior_stroke\x18_ \x01(\v2\x16.TSD.SpecStrokeArchiveR\x1ccategoryLevel1InteriorStroke\x12X\n" +
	")category_level1_interior_stroke_undefined\x18` \x01(\bR%categoryLevel1InteriorStrokeUndefined\x12]\n" +
	"\x1fcategory_level2_interior_stroke\x18a \x01(\v2\x16.TSD.SpecStrokeArchiveR\x1ccategoryLevel2InteriorStroke\x12X\n" +
	")category_level2_interior_stroke_undefined\x18b \x01(\bR%categoryLevel2InteriorStrokeUndefined\x12]\n" +
	"\x1fcategory_level3_interior_stroke\x18c \x01(\v2\x16.TSD.SpecStrokeArchiveR\x1ccategoryLevel3InteriorStroke\x12X\n" +
	")category_level3_interior_stroke_undefined\x18d \x01(\bR%categoryLevel3InteriorStrokeUndefined\x12]\n" +
	"\x1fcategory_level4_interior_stroke\x18e \x01(\v2\x16.TSD.SpecStrokeArchiveR\x1ccategoryLevel4InteriorStroke\x12X\n" +
	")category_level4_interior_stroke_undefined\x18f \x01(\bR%categoryLevel4InteriorStrokeUndefined\x12]\n" +
	"\x1fcategory_level5_interior_stroke\x18g \x01(\v2\x16.TSD.SpecStrokeArchiveR\x1ccategoryLevel5InteriorStroke\x12X\n" +
	")category_level5_interior_stroke_undefined\x18h \x01(\bR%categoryLevel5InteriorStrokeUndefined\x12b\n" +
	"\"body_pivot_group_horizontal_stroke\x18i \x01(\v2\x16.TSD.SpecStrokeArchiveR\x1ebodyPivotGroupHorizontalStroke\x12]\n" +
	",body_pivot_group_horizontal_stroke_undefined\x18j \x01(\bR'bodyPivotGroupHorizontalStrokeUndefined\x12^\n" +
	" body_pivot_group_vertical_stroke\x18k \x01(\v2\x16.TSD.SpecStrokeArchiveR\x1cbodyPivotGroupVerticalStroke\x12Y\n" +
	"*body_pivot_group_vertical_stroke_undefined\x18l \x01(\bR%bodyPivotGroupVerticalStrokeUndefined\x12m\n" +
	"(body_pivot_de_emphasis_horizontal_stroke\x18m \x01(\v2\x16.TSD.SpecStrokeArchiveR#bodyPivotDeEmphasisHorizontalStroke\x12h\n" +
	"2body_pivot_de_emphasis_horizontal_stroke_undefined\x18n \x01(\bR,bodyPivotDeEmphasisHorizontalStrokeUndefined\x12d\n" +
	"#body_pivot_emphasis_vertical_stroke\x18o \x01(\v2\x16.TSD.SpecStrokeArchiveR\x1fbodyPivotEmphasisVerticalStroke\x12_\n" +
	"-body_pivot_emphasis_vertical_stroke_undefined\x18p \x01(\bR(bodyPivotEmphasisVerticalStrokeUndefined\x12s\n" +
	"+header_column_pivot_group_horizontal_stroke\x18q \x01(\v2\x16.TSD.SpecStrokeArchiveR&headerColumnPivotGroupHorizontalStroke\x12n\n" +
	"5header_column_pivot_group_horizontal_stroke_undefined\x18r \x01(\bR/headerColumnPivotGroupHorizontalStrokeUndefined\x12t\n" +
	",header_column_pivot_group_de_emphasis_stroke\x18s \x01(\v2\x16.TSD.SpecStrokeArchiveR&headerColumnPivotGroupDeEmphasisStroke\x12o\n" +
	"6header_column_pivot_group_de_emphasis_stroke_undefined\x18t \x01(\bR/headerColumnPivotGroupDeEmphasisStrokeUndefined\x12f\n" +
	"$header_column_pivot_separator_stroke\x18u \x01(\v2\x16.TSD.SpecStrokeArchiveR headerColumnPivotSeparatorStroke\x12a\n" +
	".header_column_pivot_separator_stroke_undefined\x18v \x01(\bR)headerColumnPivotSeparatorStrokeUndefined\x12i\n" +
	"&header_row_pivot_group_vertical_stroke\x18w \x01(\v2\x16.TSD.SpecStrokeArchiveR!headerRowPivotGroupVerticalStroke\x12d\n" +
	"0header_row_pivot_group_vertical_stroke_undefined\x18x \x01(\bR*headerRowPivotGroupVerticalStrokeUndefined\x12n\n" +
	")header_row_pivot_group_de_emphasis_stroke\x18y \x01(\v2\x16.TSD.SpecStrokeArchiveR#headerRowPivotGroupDeEmphasisStroke\x12i\n" +
	"3header_row_pivot_group_de_emphasis_stroke_undefined\x18z \x01(\bR,headerRowPivotGroupDeEmphasisStrokeUndefined\x12X\n" +
	"\x1dheader_row_pivot_title_stroke\x18{ \x01(\v2\x16.TSD.SpecStrokeArchiveR\x19headerRowPivotTitleStroke\x12S\n" +
	"'header_row_pivot_title_stroke_undefined\x18| \x01(\bR\"headerRowPivotTitleStrokeUndefined\x12i\n" +
	"&footer_row_pivot_group_vertical_stroke\x18} \x01(\v2\x16.TSD.SpecStrokeArchiveR!footerRowPivotGroupVerticalStroke\x12d\n" +
	"0footer_row_pivot_group_vertical_stroke_undefined\x18~ \x01(\bR*footerRowPivotGroupVerticalStrokeUndefinedB/Z-github.com/orcastor/iwork-converter/proto/TST"

var (
	file_TSTArchives_sos_proto_rawDescOnce sync.Once
	file_TSTArchives_sos_proto_rawDescData []byte
)

func file_TSTArchives_sos_proto_rawDescGZIP() []byte {
	file_TSTArchives_sos_proto_rawDescOnce.Do(func() {
		file_TSTArchives_sos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_TSTArchives_sos_proto_rawDesc), len(file_TSTArchives_sos_proto_rawDesc)))
	})
	return file_TSTArchives_sos_proto_rawDescData
}

var file_TSTArchives_sos_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_TSTArchives_sos_proto_goTypes = []any{
	(*SpecSetTableStrokePresetListArchive)(nil),    // 0: TST.SpecSetTableStrokePresetListArchive
	(*SpecTableStrokePresetListArchive)(nil),       // 1: TST.SpecTableStrokePresetListArchive
	(*TableCellStylePropertyChangeSetArchive)(nil), // 2: TST.TableCellStylePropertyChangeSetArchive
	(*TableStylePropertyChangeSetArchive)(nil),     // 3: TST.TableStylePropertyChangeSetArchive
	(*StrokePresetListArchive)(nil),                // 4: TST.StrokePresetListArchive
	(*TSS.SpecBoolArchive)(nil),                    // 5: TSS.SpecBoolArchive
	(*TSS.SpecIntegerArchive)(nil),                 // 6: TSS.SpecIntegerArchive
	(*TSD.SpecFillArchive)(nil),                    // 7: TSD.SpecFillArchive
	(*TSWP.SpecPaddingArchive)(nil),                // 8: TSWP.SpecPaddingArchive
	(*TSD.SpecStrokeArchive)(nil),                  // 9: TSD.SpecStrokeArchive
	(*TSS.SpecStringArchive)(nil),                  // 10: TSS.SpecStringArchive
}
var file_TSTArchives_sos_proto_depIdxs = []int32{
	4,  // 0: TST.SpecSetTableStrokePresetListArchive.table_stroke_preset_list:type_name -> TST.StrokePresetListArchive
	0,  // 1: TST.SpecTableStrokePresetListArchive.spec_set_table_stroke_preset_list:type_name -> TST.SpecSetTableStrokePresetListArchive
	5,  // 2: TST.TableCellStylePropertyChangeSetArchive.text_wrap:type_name -> TSS.SpecBoolArchive
	6,  // 3: TST.TableCellStylePropertyChangeSetArchive.type:type_name -> TSS.SpecIntegerArchive
	7,  // 4: TST.TableCellStylePropertyChangeSetArchive.fill:type_name -> TSD.SpecFillArchive
	6,  // 5: TST.TableCellStylePropertyChangeSetArchive.vertical_alignment:type_name -> TSS.SpecIntegerArchive
	8,  // 6: TST.TableCellStylePropertyChangeSetArchive.padding:type_name -> TSWP.SpecPaddingArchive
	5,  // 7: TST.TableStylePropertyChangeSetArchive.auto_resize:type_name -> TSS.SpecBoolArchive
	5,  // 8: TST.TableStylePropertyChangeSetArchive.banded_rows:type_name -> TSS.SpecBoolArchive
	7,  // 9: TST.TableStylePropertyChangeSetArchive.banded_cell_fill:type_name -> TSD.SpecFillArchive
	5,  // 10: TST.TableStylePropertyChangeSetArchive.behaves_like_spreadsheet:type_name -> TSS.SpecBoolArchive
	9,  // 11: TST.TableStylePropertyChangeSetArchive.body_horizontal_border_stroke:type_name -> TSD.SpecStrokeArchive
	9,  // 12: TST.TableStylePropertyChangeSetArchive.body_vertical_border_stroke:type_name -> TSD.SpecStrokeArchive
	9,  // 13: TST.TableStylePropertyChangeSetArchive.body_horizontal_stroke:type_name -> TSD.SpecStrokeArchive
	9,  // 14: TST.TableStylePropertyChangeSetArchive.body_vertical_stroke:type_name -> TSD.SpecStrokeArchive
	9,  // 15: TST.TableStylePropertyChangeSetArchive.header_column_border_stroke:type_name -> TSD.SpecStrokeArchive
	9,  // 16: TST.TableStylePropertyChangeSetArchive.header_column_vertical_stroke:type_name -> TSD.SpecStrokeArchive
	9,  // 17: TST.TableStylePropertyChangeSetArchive.header_column_horizontal_stroke:type_name -> TSD.SpecStrokeArchive
	9,  // 18: TST.TableStylePropertyChangeSetArchive.header_column_separator_stroke:type_name -> TSD.SpecStrokeArchive
	9,  // 19: TST.TableStylePropertyChangeSetArchive.header_row_border_stroke:type_name -> TSD.SpecStrokeArchive
	9,  // 20: TST.TableStylePropertyChangeSetArchive.header_row_horizontal_stroke:type_name -> TSD.SpecStrokeArchive
	9,  // 21: TST.TableStylePropertyChangeSetArchive.header_row_vertical_stroke:type_name -> TSD.SpecStrokeArchive
	9,  // 22: TST.TableStylePropertyChangeSetArchive.header_row_separator_stroke:type_name -> TSD.SpecStrokeArchive
	9,  // 23: TST.TableStylePropertyChangeSetArchive.footer_row_border_stroke:type_name -> TSD.SpecStrokeArchive
	9,  // 24: TST.TableStylePropertyChangeSetArchive.footer_row_horizontal_stroke:type_name -> TSD.SpecStrokeArchive
	9,  // 25: TST.TableStylePropertyChangeSetArchive.footer_row_vertical_stroke:type_name -> TSD.SpecStrokeArchive
	9,  // 26: TST.TableStylePropertyChangeSetArchive.footer_row_separator_stroke:type_name -> TSD.SpecStrokeArchive
	1,  // 27: TST.TableStylePropertyChangeSetArchive.stroke_preset_list_object:type_name -> TST.SpecTableStrokePresetListArchive
	5,  // 28: TST.TableStylePropertyChangeSetArchive.vertical_strokes_visible:type_name -> TSS.SpecBoolArchive
	5,  // 29: TST.TableStylePropertyChangeSetArchive.horizontal_strokes_visible:type_name -> TSS.SpecBoolArchive
	5,  // 30: TST.TableStylePropertyChangeSetArchive.header_row_sep_visible:type_name -> TSS.SpecBoolArchive
	5,  // 31: TST.TableStylePropertyChangeSetArchive.header_row_verticals_visible:type_name -> TSS.SpecBoolArchive
	5,  // 32: TST.TableStylePropertyChangeSetArchive.header_col_sep_visible:type_name -> TSS.SpecBoolArchive
	5,  // 33: TST.TableStylePropertyChangeSetArchive.header_col_horizontals_visible:type_name -> TSS.SpecBoolArchive
	5,  // 34: TST.TableStylePropertyChangeSetArchive.footer_sep_visible:type_name -> TSS.SpecBoolArchive
	5,  // 35: TST.TableStylePropertyChangeSetArchive.footer_verticals_visible:type_name -> TSS.SpecBoolArchive
	5,  // 36: TST.TableStylePropertyChangeSetArchive.border_strokes_visible:type_name -> TSS.SpecBoolArchive
	10, // 37: TST.TableStylePropertyChangeSetArchive.master_font_family:type_name -> TSS.SpecStringArchive
	6,  // 38: TST.TableStylePropertyChangeSetArchive.writing_direction:type_name -> TSS.SpecIntegerArchive
	9,  // 39: TST.TableStylePropertyChangeSetArchive.category_level1_top_stroke:type_name -> TSD.SpecStrokeArchive
	9,  // 40: TST.TableStylePropertyChangeSetArchive.category_level2_top_stroke:type_name -> TSD.SpecStrokeArchive
	9,  // 41: TST.TableStylePropertyChangeSetArchive.category_level3_top_stroke:type_name -> TSD.SpecStrokeArchive
	9,  // 42: TST.TableStylePropertyChangeSetArchive.category_level4_top_stroke:type_name -> TSD.SpecStrokeArchive
	9,  // 43: TST.TableStylePropertyChangeSetArchive.category_level5_top_stroke:type_name -> TSD.SpecStrokeArchive
	9,  // 44: TST.TableStylePropertyChangeSetArchive.category_level1_label_separator_stroke:type_name -> TSD.SpecStrokeArchive
	9,  // 45: TST.TableStylePropertyChangeSetArchive.category_level2_label_separator_stroke:type_name -> TSD.SpecStrokeArchive
	9,  // 46: TST.TableStylePropertyChangeSetArchive.category_level3_label_separator_stroke:type_name -> TSD.SpecStrokeArchive
	9,  // 47: TST.TableStylePropertyChangeSetArchive.category_level4_label_separator_stroke:type_name -> TSD.SpecStrokeArchive
	9,  // 48: TST.TableStylePropertyChangeSetArchive.category_level5_label_separator_stroke:type_name -> TSD.SpecStrokeArchive
	9,  // 49: TST.TableStylePropertyChangeSetArchive.category_level1_bottom_stroke:type_name -> TSD.SpecStrokeArchive
	9,  // 50: TST.TableStylePropertyChangeSetArchive.category_level2_bottom_stroke:type_name -> TSD.SpecStrokeArchive
	9,  // 51: TST.TableStylePropertyChangeSetArchive.category_level3_bottom_stroke:type_name -> TSD.SpecStrokeArchive
	9,  // 52: TST.TableStylePropertyChangeSetArchive.category_level4_bottom_stroke:type_name -> TSD.SpecStrokeArchive
	9,  // 53: TST.TableStylePropertyChangeSetArchive.category_level5_bottom_stroke:type_name -> TSD.SpecStrokeArchive
	9,  // 54: TST.TableStylePropertyChangeSetArchive.category_level1_interior_stroke:type_name -> TSD.SpecStrokeArchive
	9,  // 55: TST.TableStylePropertyChangeSetArchive.category_level2_interior_stroke:type_name -> TSD.SpecStrokeArchive
	9,  // 56: TST.TableStylePropertyChangeSetArchive.category_level3_interior_stroke:type_name -> TSD.SpecStrokeArchive
	9,  // 57: TST.TableStylePropertyChangeSetArchive.category_level4_interior_stroke:type_name -> TSD.SpecStrokeArchive
	9,  // 58: TST.TableStylePropertyChangeSetArchive.category_level5_interior_stroke:type_name -> TSD.SpecStrokeArchive
	9,  // 59: TST.TableStylePropertyChangeSetArchive.body_pivot_group_horizontal_stroke:type_name -> TSD.SpecStrokeArchive
	9,  // 60: TST.TableStylePropertyChangeSetArchive.body_pivot_group_vertical_stroke:type_name -> TSD.SpecStrokeArchive
	9,  // 61: TST.TableStylePropertyChangeSetArchive.body_pivot_de_emphasis_horizontal_stroke:type_name -> TSD.SpecStrokeArchive
	9,  // 62: TST.TableStylePropertyChangeSetArchive.body_pivot_emphasis_vertical_stroke:type_name -> TSD.SpecStrokeArchive
	9,  // 63: TST.TableStylePropertyChangeSetArchive.header_column_pivot_group_horizontal_stroke:type_name -> TSD.SpecStrokeArchive
	9,  // 64: TST.TableStylePropertyChangeSetArchive.header_column_pivot_group_de_emphasis_stroke:type_name -> TSD.SpecStrokeArchive
	9,  // 65: TST.TableStylePropertyChangeSetArchive.header_column_pivot_separator_stroke:type_name -> TSD.SpecStrokeArchive
	9,  // 66: TST.TableStylePropertyChangeSetArchive.header_row_pivot_group_vertical_stroke:type_name -> TSD.SpecStrokeArchive
	9,  // 67: TST.TableStylePropertyChangeSetArchive.header_row_pivot_group_de_emphasis_stroke:type_name -> TSD.SpecStrokeArchive
	9,  // 68: TST.TableStylePropertyChangeSetArchive.header_row_pivot_title_stroke:type_name -> TSD.SpecStrokeArchive
	9,  // 69: TST.TableStylePropertyChangeSetArchive.footer_row_pivot_group_vertical_stroke:type_name -> TSD.SpecStrokeArchive
	70, // [70:70] is the sub-list for method output_type
	70, // [70:70] is the sub-list for method input_type
	70, // [70:70] is the sub-list for extension type_name
	70, // [70:70] is the sub-list for extension extendee
	0,  // [0:70] is the sub-list for field type_name
}

func init() { file_TSTArchives_sos_proto_init() }
func file_TSTArchives_sos_proto_init() {
	if File_TSTArchives_sos_proto != nil {
		return
	}
	file_TSTStylePropertyArchiving_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_TSTArchives_sos_proto_rawDesc), len(file_TSTArchives_sos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TSTArchives_sos_proto_goTypes,
		DependencyIndexes: file_TSTArchives_sos_proto_depIdxs,
		MessageInfos:      file_TSTArchives_sos_proto_msgTypes,
	}.Build()
	File_TSTArchives_sos_proto = out.File
	file_TSTArchives_sos_proto_goTypes = nil
	file_TSTArchives_sos_proto_depIdxs = nil
}
