// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: TSTStylePropertyArchiving.proto

package TST

import (
	TSD "github.com/orcastor/iwork-converter/proto/TSD"
	_ "github.com/orcastor/iwork-converter/proto/TSK"
	TSP "github.com/orcastor/iwork-converter/proto/TSP"
	_ "github.com/orcastor/iwork-converter/proto/TSS"
	TSWP "github.com/orcastor/iwork-converter/proto/TSWP"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Deprecated_TableStrokeArchive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stroke        *TSD.StrokeArchive     `protobuf:"bytes,1,opt,name=stroke" json:"stroke,omitempty"`
	Background    *bool                  `protobuf:"varint,2,opt,name=background" json:"background,omitempty"`
	Opacity       *float32               `protobuf:"fixed32,3,opt,name=opacity" json:"opacity,omitempty"`
	Empty         *bool                  `protobuf:"varint,4,opt,name=empty" json:"empty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Deprecated_TableStrokeArchive) Reset() {
	*x = Deprecated_TableStrokeArchive{}
	mi := &file_TSTStylePropertyArchiving_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deprecated_TableStrokeArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deprecated_TableStrokeArchive) ProtoMessage() {}

func (x *Deprecated_TableStrokeArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSTStylePropertyArchiving_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deprecated_TableStrokeArchive.ProtoReflect.Descriptor instead.
func (*Deprecated_TableStrokeArchive) Descriptor() ([]byte, []int) {
	return file_TSTStylePropertyArchiving_proto_rawDescGZIP(), []int{0}
}

func (x *Deprecated_TableStrokeArchive) GetStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.Stroke
	}
	return nil
}

func (x *Deprecated_TableStrokeArchive) GetBackground() bool {
	if x != nil && x.Background != nil {
		return *x.Background
	}
	return false
}

func (x *Deprecated_TableStrokeArchive) GetOpacity() float32 {
	if x != nil && x.Opacity != nil {
		return *x.Opacity
	}
	return 0
}

func (x *Deprecated_TableStrokeArchive) GetEmpty() bool {
	if x != nil && x.Empty != nil {
		return *x.Empty
	}
	return false
}

type CellStylePropertiesArchive struct {
	state                  protoimpl.MessageState         `protogen:"open.v1"`
	CellFill               *TSD.FillArchive               `protobuf:"bytes,1,opt,name=cell_fill,json=cellFill" json:"cell_fill,omitempty"`
	TextWrap               *bool                          `protobuf:"varint,3,opt,name=text_wrap,json=textWrap" json:"text_wrap,omitempty"`
	DeprecatedTopStroke    *Deprecated_TableStrokeArchive `protobuf:"bytes,4,opt,name=deprecated_top_stroke,json=deprecatedTopStroke" json:"deprecated_top_stroke,omitempty"`
	DeprecatedRightStroke  *Deprecated_TableStrokeArchive `protobuf:"bytes,5,opt,name=deprecated_right_stroke,json=deprecatedRightStroke" json:"deprecated_right_stroke,omitempty"`
	DeprecatedBottomStroke *Deprecated_TableStrokeArchive `protobuf:"bytes,6,opt,name=deprecated_bottom_stroke,json=deprecatedBottomStroke" json:"deprecated_bottom_stroke,omitempty"`
	DeprecatedLeftStroke   *Deprecated_TableStrokeArchive `protobuf:"bytes,7,opt,name=deprecated_left_stroke,json=deprecatedLeftStroke" json:"deprecated_left_stroke,omitempty"`
	VerticalAlignment      *int32                         `protobuf:"varint,8,opt,name=vertical_alignment,json=verticalAlignment" json:"vertical_alignment,omitempty"`
	Padding                *TSWP.PaddingArchive           `protobuf:"bytes,9,opt,name=padding" json:"padding,omitempty"`
	TopStroke              *TSD.StrokeArchive             `protobuf:"bytes,10,opt,name=top_stroke,json=topStroke" json:"top_stroke,omitempty"`
	RightStroke            *TSD.StrokeArchive             `protobuf:"bytes,11,opt,name=right_stroke,json=rightStroke" json:"right_stroke,omitempty"`
	BottomStroke           *TSD.StrokeArchive             `protobuf:"bytes,12,opt,name=bottom_stroke,json=bottomStroke" json:"bottom_stroke,omitempty"`
	LeftStroke             *TSD.StrokeArchive             `protobuf:"bytes,13,opt,name=left_stroke,json=leftStroke" json:"left_stroke,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CellStylePropertiesArchive) Reset() {
	*x = CellStylePropertiesArchive{}
	mi := &file_TSTStylePropertyArchiving_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellStylePropertiesArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellStylePropertiesArchive) ProtoMessage() {}

func (x *CellStylePropertiesArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSTStylePropertyArchiving_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellStylePropertiesArchive.ProtoReflect.Descriptor instead.
func (*CellStylePropertiesArchive) Descriptor() ([]byte, []int) {
	return file_TSTStylePropertyArchiving_proto_rawDescGZIP(), []int{1}
}

func (x *CellStylePropertiesArchive) GetCellFill() *TSD.FillArchive {
	if x != nil {
		return x.CellFill
	}
	return nil
}

func (x *CellStylePropertiesArchive) GetTextWrap() bool {
	if x != nil && x.TextWrap != nil {
		return *x.TextWrap
	}
	return false
}

func (x *CellStylePropertiesArchive) GetDeprecatedTopStroke() *Deprecated_TableStrokeArchive {
	if x != nil {
		return x.DeprecatedTopStroke
	}
	return nil
}

func (x *CellStylePropertiesArchive) GetDeprecatedRightStroke() *Deprecated_TableStrokeArchive {
	if x != nil {
		return x.DeprecatedRightStroke
	}
	return nil
}

func (x *CellStylePropertiesArchive) GetDeprecatedBottomStroke() *Deprecated_TableStrokeArchive {
	if x != nil {
		return x.DeprecatedBottomStroke
	}
	return nil
}

func (x *CellStylePropertiesArchive) GetDeprecatedLeftStroke() *Deprecated_TableStrokeArchive {
	if x != nil {
		return x.DeprecatedLeftStroke
	}
	return nil
}

func (x *CellStylePropertiesArchive) GetVerticalAlignment() int32 {
	if x != nil && x.VerticalAlignment != nil {
		return *x.VerticalAlignment
	}
	return 0
}

func (x *CellStylePropertiesArchive) GetPadding() *TSWP.PaddingArchive {
	if x != nil {
		return x.Padding
	}
	return nil
}

func (x *CellStylePropertiesArchive) GetTopStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.TopStroke
	}
	return nil
}

func (x *CellStylePropertiesArchive) GetRightStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.RightStroke
	}
	return nil
}

func (x *CellStylePropertiesArchive) GetBottomStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.BottomStroke
	}
	return nil
}

func (x *CellStylePropertiesArchive) GetLeftStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.LeftStroke
	}
	return nil
}

type Deprecated_StrokePresetDataArchive struct {
	state                      protoimpl.MessageState         `protogen:"open.v1"`
	DeprecatedHorizontalStroke *Deprecated_TableStrokeArchive `protobuf:"bytes,2,req,name=deprecated_horizontal_stroke,json=deprecatedHorizontalStroke" json:"deprecated_horizontal_stroke,omitempty"`
	DeprecatedVerticalStroke   *Deprecated_TableStrokeArchive `protobuf:"bytes,1,req,name=deprecated_vertical_stroke,json=deprecatedVerticalStroke" json:"deprecated_vertical_stroke,omitempty"`
	DeprecatedExteriorStroke   *Deprecated_TableStrokeArchive `protobuf:"bytes,3,req,name=deprecated_exterior_stroke,json=deprecatedExteriorStroke" json:"deprecated_exterior_stroke,omitempty"`
	DeprecatedVisibleMask      *int32                         `protobuf:"varint,5,req,name=deprecated_visible_mask,json=deprecatedVisibleMask" json:"deprecated_visible_mask,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *Deprecated_StrokePresetDataArchive) Reset() {
	*x = Deprecated_StrokePresetDataArchive{}
	mi := &file_TSTStylePropertyArchiving_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deprecated_StrokePresetDataArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deprecated_StrokePresetDataArchive) ProtoMessage() {}

func (x *Deprecated_StrokePresetDataArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSTStylePropertyArchiving_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deprecated_StrokePresetDataArchive.ProtoReflect.Descriptor instead.
func (*Deprecated_StrokePresetDataArchive) Descriptor() ([]byte, []int) {
	return file_TSTStylePropertyArchiving_proto_rawDescGZIP(), []int{2}
}

func (x *Deprecated_StrokePresetDataArchive) GetDeprecatedHorizontalStroke() *Deprecated_TableStrokeArchive {
	if x != nil {
		return x.DeprecatedHorizontalStroke
	}
	return nil
}

func (x *Deprecated_StrokePresetDataArchive) GetDeprecatedVerticalStroke() *Deprecated_TableStrokeArchive {
	if x != nil {
		return x.DeprecatedVerticalStroke
	}
	return nil
}

func (x *Deprecated_StrokePresetDataArchive) GetDeprecatedExteriorStroke() *Deprecated_TableStrokeArchive {
	if x != nil {
		return x.DeprecatedExteriorStroke
	}
	return nil
}

func (x *Deprecated_StrokePresetDataArchive) GetDeprecatedVisibleMask() int32 {
	if x != nil && x.DeprecatedVisibleMask != nil {
		return *x.DeprecatedVisibleMask
	}
	return 0
}

type StrokePresetDataArchive struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	HorizontalStroke *TSD.StrokeArchive     `protobuf:"bytes,1,opt,name=horizontal_stroke,json=horizontalStroke" json:"horizontal_stroke,omitempty"`
	VerticalStroke   *TSD.StrokeArchive     `protobuf:"bytes,2,opt,name=vertical_stroke,json=verticalStroke" json:"vertical_stroke,omitempty"`
	ExteriorStroke   *TSD.StrokeArchive     `protobuf:"bytes,3,opt,name=exterior_stroke,json=exteriorStroke" json:"exterior_stroke,omitempty"`
	VisibleMask      *int32                 `protobuf:"varint,4,opt,name=visible_mask,json=visibleMask" json:"visible_mask,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StrokePresetDataArchive) Reset() {
	*x = StrokePresetDataArchive{}
	mi := &file_TSTStylePropertyArchiving_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StrokePresetDataArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrokePresetDataArchive) ProtoMessage() {}

func (x *StrokePresetDataArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSTStylePropertyArchiving_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrokePresetDataArchive.ProtoReflect.Descriptor instead.
func (*StrokePresetDataArchive) Descriptor() ([]byte, []int) {
	return file_TSTStylePropertyArchiving_proto_rawDescGZIP(), []int{3}
}

func (x *StrokePresetDataArchive) GetHorizontalStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.HorizontalStroke
	}
	return nil
}

func (x *StrokePresetDataArchive) GetVerticalStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.VerticalStroke
	}
	return nil
}

func (x *StrokePresetDataArchive) GetExteriorStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.ExteriorStroke
	}
	return nil
}

func (x *StrokePresetDataArchive) GetVisibleMask() int32 {
	if x != nil && x.VisibleMask != nil {
		return *x.VisibleMask
	}
	return 0
}

type StrokePresetListArchive struct {
	state            protoimpl.MessageState                `protogen:"open.v1"`
	Count            *int32                                `protobuf:"varint,1,req,name=count" json:"count,omitempty"`
	DeprecatedPreset []*Deprecated_StrokePresetDataArchive `protobuf:"bytes,2,rep,name=deprecated_preset,json=deprecatedPreset" json:"deprecated_preset,omitempty"`
	Preset           []*StrokePresetDataArchive            `protobuf:"bytes,3,rep,name=preset" json:"preset,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StrokePresetListArchive) Reset() {
	*x = StrokePresetListArchive{}
	mi := &file_TSTStylePropertyArchiving_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StrokePresetListArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrokePresetListArchive) ProtoMessage() {}

func (x *StrokePresetListArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSTStylePropertyArchiving_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrokePresetListArchive.ProtoReflect.Descriptor instead.
func (*StrokePresetListArchive) Descriptor() ([]byte, []int) {
	return file_TSTStylePropertyArchiving_proto_rawDescGZIP(), []int{4}
}

func (x *StrokePresetListArchive) GetCount() int32 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

func (x *StrokePresetListArchive) GetDeprecatedPreset() []*Deprecated_StrokePresetDataArchive {
	if x != nil {
		return x.DeprecatedPreset
	}
	return nil
}

func (x *StrokePresetListArchive) GetPreset() []*StrokePresetDataArchive {
	if x != nil {
		return x.Preset
	}
	return nil
}

type TableStylePropertiesArchive struct {
	state                                     protoimpl.MessageState         `protogen:"open.v1"`
	BandedRows                                *bool                          `protobuf:"varint,1,opt,name=banded_rows,json=bandedRows" json:"banded_rows,omitempty"`
	BandedFill                                *TSD.FillArchive               `protobuf:"bytes,2,opt,name=banded_fill,json=bandedFill" json:"banded_fill,omitempty"`
	BehavesLikeSpreadsheet                    *bool                          `protobuf:"varint,21,opt,name=behaves_like_spreadsheet,json=behavesLikeSpreadsheet" json:"behaves_like_spreadsheet,omitempty"`
	AutoResize                                *bool                          `protobuf:"varint,22,opt,name=auto_resize,json=autoResize" json:"auto_resize,omitempty"`
	DeprecatedHeaderRowSeparatorStroke        *Deprecated_TableStrokeArchive `protobuf:"bytes,4,opt,name=deprecated_header_row_separator_stroke,json=deprecatedHeaderRowSeparatorStroke" json:"deprecated_header_row_separator_stroke,omitempty"`
	DeprecatedHeaderRowBorderStroke           *Deprecated_TableStrokeArchive `protobuf:"bytes,5,opt,name=deprecated_header_row_border_stroke,json=deprecatedHeaderRowBorderStroke" json:"deprecated_header_row_border_stroke,omitempty"`
	DeprecatedHeaderRowHorizontalStroke       *Deprecated_TableStrokeArchive `protobuf:"bytes,23,opt,name=deprecated_header_row_horizontal_stroke,json=deprecatedHeaderRowHorizontalStroke" json:"deprecated_header_row_horizontal_stroke,omitempty"`
	DeprecatedHeaderRowVerticalStroke         *Deprecated_TableStrokeArchive `protobuf:"bytes,24,opt,name=deprecated_header_row_vertical_stroke,json=deprecatedHeaderRowVerticalStroke" json:"deprecated_header_row_vertical_stroke,omitempty"`
	DeprecatedHeaderColumnBorderStroke        *Deprecated_TableStrokeArchive `protobuf:"bytes,7,opt,name=deprecated_header_column_border_stroke,json=deprecatedHeaderColumnBorderStroke" json:"deprecated_header_column_border_stroke,omitempty"`
	DeprecatedHeaderColumnSeparatorStroke     *Deprecated_TableStrokeArchive `protobuf:"bytes,8,opt,name=deprecated_header_column_separator_stroke,json=deprecatedHeaderColumnSeparatorStroke" json:"deprecated_header_column_separator_stroke,omitempty"`
	DeprecatedHeaderColumnHorizontalStroke    *Deprecated_TableStrokeArchive `protobuf:"bytes,25,opt,name=deprecated_header_column_horizontal_stroke,json=deprecatedHeaderColumnHorizontalStroke" json:"deprecated_header_column_horizontal_stroke,omitempty"`
	DeprecatedHeaderColumnVerticalStroke      *Deprecated_TableStrokeArchive `protobuf:"bytes,26,opt,name=deprecated_header_column_vertical_stroke,json=deprecatedHeaderColumnVerticalStroke" json:"deprecated_header_column_vertical_stroke,omitempty"`
	DeprecatedFooterRowSeparatorStroke        *Deprecated_TableStrokeArchive `protobuf:"bytes,10,opt,name=deprecated_footer_row_separator_stroke,json=deprecatedFooterRowSeparatorStroke" json:"deprecated_footer_row_separator_stroke,omitempty"`
	DeprecatedFooterRowBorderStroke           *Deprecated_TableStrokeArchive `protobuf:"bytes,11,opt,name=deprecated_footer_row_border_stroke,json=deprecatedFooterRowBorderStroke" json:"deprecated_footer_row_border_stroke,omitempty"`
	DeprecatedFooterRowHorizontalStroke       *Deprecated_TableStrokeArchive `protobuf:"bytes,27,opt,name=deprecated_footer_row_horizontal_stroke,json=deprecatedFooterRowHorizontalStroke" json:"deprecated_footer_row_horizontal_stroke,omitempty"`
	DeprecatedFooterRowVerticalStroke         *Deprecated_TableStrokeArchive `protobuf:"bytes,28,opt,name=deprecated_footer_row_vertical_stroke,json=deprecatedFooterRowVerticalStroke" json:"deprecated_footer_row_vertical_stroke,omitempty"`
	DeprecatedTableBodyHorizontalBorderStroke *Deprecated_TableStrokeArchive `protobuf:"bytes,12,opt,name=deprecated_table_body_horizontal_border_stroke,json=deprecatedTableBodyHorizontalBorderStroke" json:"deprecated_table_body_horizontal_border_stroke,omitempty"`
	DeprecatedTableBodyVerticalBorderStroke   *Deprecated_TableStrokeArchive `protobuf:"bytes,29,opt,name=deprecated_table_body_vertical_border_stroke,json=deprecatedTableBodyVerticalBorderStroke" json:"deprecated_table_body_vertical_border_stroke,omitempty"`
	DeprecatedTableBodyHorizontalStroke       *Deprecated_TableStrokeArchive `protobuf:"bytes,30,opt,name=deprecated_table_body_horizontal_stroke,json=deprecatedTableBodyHorizontalStroke" json:"deprecated_table_body_horizontal_stroke,omitempty"`
	DeprecatedTableBodyVerticalStroke         *Deprecated_TableStrokeArchive `protobuf:"bytes,31,opt,name=deprecated_table_body_vertical_stroke,json=deprecatedTableBodyVerticalStroke" json:"deprecated_table_body_vertical_stroke,omitempty"`
	StrokePresetList                          *StrokePresetListArchive       `protobuf:"bytes,32,opt,name=stroke_preset_list,json=strokePresetList" json:"stroke_preset_list,omitempty"`
	VStrokesVisible                           *bool                          `protobuf:"varint,33,opt,name=v_strokes_visible,json=vStrokesVisible" json:"v_strokes_visible,omitempty"`
	HStrokesVisible                           *bool                          `protobuf:"varint,34,opt,name=h_strokes_visible,json=hStrokesVisible" json:"h_strokes_visible,omitempty"`
	HrSeparatorVisible                        *bool                          `protobuf:"varint,35,opt,name=hr_separator_visible,json=hrSeparatorVisible" json:"hr_separator_visible,omitempty"`
	HcSeparatorVisible                        *bool                          `protobuf:"varint,36,opt,name=hc_separator_visible,json=hcSeparatorVisible" json:"hc_separator_visible,omitempty"`
	FooterSeparatorVisible                    *bool                          `protobuf:"varint,37,opt,name=footer_separator_visible,json=footerSeparatorVisible" json:"footer_separator_visible,omitempty"`
	TableBorderVisible                        *bool                          `protobuf:"varint,38,opt,name=table_border_visible,json=tableBorderVisible" json:"table_border_visible,omitempty"`
	TableHeaderBorderVisible                  *bool                          `protobuf:"varint,39,opt,name=table_header_border_visible,json=tableHeaderBorderVisible" json:"table_header_border_visible,omitempty"`
	TableHcDividerVisible                     *bool                          `protobuf:"varint,42,opt,name=table_hc_divider_visible,json=tableHcDividerVisible" json:"table_hc_divider_visible,omitempty"`
	TableHrDividerVisible                     *bool                          `protobuf:"varint,43,opt,name=table_hr_divider_visible,json=tableHrDividerVisible" json:"table_hr_divider_visible,omitempty"`
	TableFooterDividerVisible                 *bool                          `protobuf:"varint,44,opt,name=table_footer_divider_visible,json=tableFooterDividerVisible" json:"table_footer_divider_visible,omitempty"`
	OBSOLETEMasterFontSize                    *int32                         `protobuf:"varint,40,opt,name=OBSOLETE_master_font_size,json=OBSOLETEMasterFontSize" json:"OBSOLETE_master_font_size,omitempty"`
	MasterFontFamily                          *string                        `protobuf:"bytes,41,opt,name=master_font_family,json=masterFontFamily" json:"master_font_family,omitempty"`
	WritingDirection                          *TSWP.WritingDirectionType     `protobuf:"varint,45,opt,name=writing_direction,json=writingDirection,enum=TSWP.WritingDirectionType" json:"writing_direction,omitempty"`
	HeaderRowSeparatorStroke                  *TSD.StrokeArchive             `protobuf:"bytes,46,opt,name=header_row_separator_stroke,json=headerRowSeparatorStroke" json:"header_row_separator_stroke,omitempty"`
	HeaderRowBorderStroke                     *TSD.StrokeArchive             `protobuf:"bytes,47,opt,name=header_row_border_stroke,json=headerRowBorderStroke" json:"header_row_border_stroke,omitempty"`
	HeaderRowHorizontalStroke                 *TSD.StrokeArchive             `protobuf:"bytes,48,opt,name=header_row_horizontal_stroke,json=headerRowHorizontalStroke" json:"header_row_horizontal_stroke,omitempty"`
	HeaderRowVerticalStroke                   *TSD.StrokeArchive             `protobuf:"bytes,49,opt,name=header_row_vertical_stroke,json=headerRowVerticalStroke" json:"header_row_vertical_stroke,omitempty"`
	HeaderColumnBorderStroke                  *TSD.StrokeArchive             `protobuf:"bytes,50,opt,name=header_column_border_stroke,json=headerColumnBorderStroke" json:"header_column_border_stroke,omitempty"`
	HeaderColumnSeparatorStroke               *TSD.StrokeArchive             `protobuf:"bytes,51,opt,name=header_column_separator_stroke,json=headerColumnSeparatorStroke" json:"header_column_separator_stroke,omitempty"`
	HeaderColumnHorizontalStroke              *TSD.StrokeArchive             `protobuf:"bytes,52,opt,name=header_column_horizontal_stroke,json=headerColumnHorizontalStroke" json:"header_column_horizontal_stroke,omitempty"`
	HeaderColumnVerticalStroke                *TSD.StrokeArchive             `protobuf:"bytes,53,opt,name=header_column_vertical_stroke,json=headerColumnVerticalStroke" json:"header_column_vertical_stroke,omitempty"`
	FooterRowSeparatorStroke                  *TSD.StrokeArchive             `protobuf:"bytes,54,opt,name=footer_row_separator_stroke,json=footerRowSeparatorStroke" json:"footer_row_separator_stroke,omitempty"`
	FooterRowBorderStroke                     *TSD.StrokeArchive             `protobuf:"bytes,55,opt,name=footer_row_border_stroke,json=footerRowBorderStroke" json:"footer_row_border_stroke,omitempty"`
	FooterRowHorizontalStroke                 *TSD.StrokeArchive             `protobuf:"bytes,56,opt,name=footer_row_horizontal_stroke,json=footerRowHorizontalStroke" json:"footer_row_horizontal_stroke,omitempty"`
	FooterRowVerticalStroke                   *TSD.StrokeArchive             `protobuf:"bytes,57,opt,name=footer_row_vertical_stroke,json=footerRowVerticalStroke" json:"footer_row_vertical_stroke,omitempty"`
	TableBodyHorizontalBorderStroke           *TSD.StrokeArchive             `protobuf:"bytes,58,opt,name=table_body_horizontal_border_stroke,json=tableBodyHorizontalBorderStroke" json:"table_body_horizontal_border_stroke,omitempty"`
	TableBodyVerticalBorderStroke             *TSD.StrokeArchive             `protobuf:"bytes,59,opt,name=table_body_vertical_border_stroke,json=tableBodyVerticalBorderStroke" json:"table_body_vertical_border_stroke,omitempty"`
	TableBodyHorizontalStroke                 *TSD.StrokeArchive             `protobuf:"bytes,60,opt,name=table_body_horizontal_stroke,json=tableBodyHorizontalStroke" json:"table_body_horizontal_stroke,omitempty"`
	TableBodyVerticalStroke                   *TSD.StrokeArchive             `protobuf:"bytes,61,opt,name=table_body_vertical_stroke,json=tableBodyVerticalStroke" json:"table_body_vertical_stroke,omitempty"`
	CategoryLevel1TopStroke                   *TSD.StrokeArchive             `protobuf:"bytes,62,opt,name=category_level1_top_stroke,json=categoryLevel1TopStroke" json:"category_level1_top_stroke,omitempty"`
	CategoryLevel2TopStroke                   *TSD.StrokeArchive             `protobuf:"bytes,63,opt,name=category_level2_top_stroke,json=categoryLevel2TopStroke" json:"category_level2_top_stroke,omitempty"`
	CategoryLevel3TopStroke                   *TSD.StrokeArchive             `protobuf:"bytes,64,opt,name=category_level3_top_stroke,json=categoryLevel3TopStroke" json:"category_level3_top_stroke,omitempty"`
	CategoryLevel4TopStroke                   *TSD.StrokeArchive             `protobuf:"bytes,65,opt,name=category_level4_top_stroke,json=categoryLevel4TopStroke" json:"category_level4_top_stroke,omitempty"`
	CategoryLevel5TopStroke                   *TSD.StrokeArchive             `protobuf:"bytes,66,opt,name=category_level5_top_stroke,json=categoryLevel5TopStroke" json:"category_level5_top_stroke,omitempty"`
	CategoryLevel1BottomStroke                *TSD.StrokeArchive             `protobuf:"bytes,67,opt,name=category_level1_bottom_stroke,json=categoryLevel1BottomStroke" json:"category_level1_bottom_stroke,omitempty"`
	CategoryLevel2BottomStroke                *TSD.StrokeArchive             `protobuf:"bytes,68,opt,name=category_level2_bottom_stroke,json=categoryLevel2BottomStroke" json:"category_level2_bottom_stroke,omitempty"`
	CategoryLevel3BottomStroke                *TSD.StrokeArchive             `protobuf:"bytes,69,opt,name=category_level3_bottom_stroke,json=categoryLevel3BottomStroke" json:"category_level3_bottom_stroke,omitempty"`
	CategoryLevel4BottomStroke                *TSD.StrokeArchive             `protobuf:"bytes,70,opt,name=category_level4_bottom_stroke,json=categoryLevel4BottomStroke" json:"category_level4_bottom_stroke,omitempty"`
	CategoryLevel5BottomStroke                *TSD.StrokeArchive             `protobuf:"bytes,71,opt,name=category_level5_bottom_stroke,json=categoryLevel5BottomStroke" json:"category_level5_bottom_stroke,omitempty"`
	CategoryLevel1InteriorStroke              *TSD.StrokeArchive             `protobuf:"bytes,72,opt,name=category_level1_interior_stroke,json=categoryLevel1InteriorStroke" json:"category_level1_interior_stroke,omitempty"`
	CategoryLevel2InteriorStroke              *TSD.StrokeArchive             `protobuf:"bytes,73,opt,name=category_level2_interior_stroke,json=categoryLevel2InteriorStroke" json:"category_level2_interior_stroke,omitempty"`
	CategoryLevel3InteriorStroke              *TSD.StrokeArchive             `protobuf:"bytes,74,opt,name=category_level3_interior_stroke,json=categoryLevel3InteriorStroke" json:"category_level3_interior_stroke,omitempty"`
	CategoryLevel4InteriorStroke              *TSD.StrokeArchive             `protobuf:"bytes,75,opt,name=category_level4_interior_stroke,json=categoryLevel4InteriorStroke" json:"category_level4_interior_stroke,omitempty"`
	CategoryLevel5InteriorStroke              *TSD.StrokeArchive             `protobuf:"bytes,76,opt,name=category_level5_interior_stroke,json=categoryLevel5InteriorStroke" json:"category_level5_interior_stroke,omitempty"`
	CategoryLevel1LabelSeparatorStroke        *TSD.StrokeArchive             `protobuf:"bytes,77,opt,name=category_level1_label_separator_stroke,json=categoryLevel1LabelSeparatorStroke" json:"category_level1_label_separator_stroke,omitempty"`
	CategoryLevel2LabelSeparatorStroke        *TSD.StrokeArchive             `protobuf:"bytes,78,opt,name=category_level2_label_separator_stroke,json=categoryLevel2LabelSeparatorStroke" json:"category_level2_label_separator_stroke,omitempty"`
	CategoryLevel3LabelSeparatorStroke        *TSD.StrokeArchive             `protobuf:"bytes,79,opt,name=category_level3_label_separator_stroke,json=categoryLevel3LabelSeparatorStroke" json:"category_level3_label_separator_stroke,omitempty"`
	CategoryLevel4LabelSeparatorStroke        *TSD.StrokeArchive             `protobuf:"bytes,80,opt,name=category_level4_label_separator_stroke,json=categoryLevel4LabelSeparatorStroke" json:"category_level4_label_separator_stroke,omitempty"`
	CategoryLevel5LabelSeparatorStroke        *TSD.StrokeArchive             `protobuf:"bytes,81,opt,name=category_level5_label_separator_stroke,json=categoryLevel5LabelSeparatorStroke" json:"category_level5_label_separator_stroke,omitempty"`
	TableBodyPivotGroupHorizontalStroke       *TSD.StrokeArchive             `protobuf:"bytes,82,opt,name=table_body_pivot_group_horizontal_stroke,json=tableBodyPivotGroupHorizontalStroke" json:"table_body_pivot_group_horizontal_stroke,omitempty"`
	TableBodyPivotGroupVerticalStroke         *TSD.StrokeArchive             `protobuf:"bytes,83,opt,name=table_body_pivot_group_vertical_stroke,json=tableBodyPivotGroupVerticalStroke" json:"table_body_pivot_group_vertical_stroke,omitempty"`
	TableBodyPivotDeemphasisHorizontalStroke  *TSD.StrokeArchive             `protobuf:"bytes,84,opt,name=table_body_pivot_deemphasis_horizontal_stroke,json=tableBodyPivotDeemphasisHorizontalStroke" json:"table_body_pivot_deemphasis_horizontal_stroke,omitempty"`
	TableBodyPivotEmphasisVerticalStroke      *TSD.StrokeArchive             `protobuf:"bytes,85,opt,name=table_body_pivot_emphasis_vertical_stroke,json=tableBodyPivotEmphasisVerticalStroke" json:"table_body_pivot_emphasis_vertical_stroke,omitempty"`
	HeaderColumnPivotGroupHorizontalStroke    *TSD.StrokeArchive             `protobuf:"bytes,86,opt,name=header_column_pivot_group_horizontal_stroke,json=headerColumnPivotGroupHorizontalStroke" json:"header_column_pivot_group_horizontal_stroke,omitempty"`
	HeaderColumnPivotGroupDeemphasisStroke    *TSD.StrokeArchive             `protobuf:"bytes,87,opt,name=header_column_pivot_group_deemphasis_stroke,json=headerColumnPivotGroupDeemphasisStroke" json:"header_column_pivot_group_deemphasis_stroke,omitempty"`
	HeaderColumnPivotSeparatorStroke          *TSD.StrokeArchive             `protobuf:"bytes,88,opt,name=header_column_pivot_separator_stroke,json=headerColumnPivotSeparatorStroke" json:"header_column_pivot_separator_stroke,omitempty"`
	HeaderRowPivotGroupVerticalStroke         *TSD.StrokeArchive             `protobuf:"bytes,89,opt,name=header_row_pivot_group_vertical_stroke,json=headerRowPivotGroupVerticalStroke" json:"header_row_pivot_group_vertical_stroke,omitempty"`
	HeaderRowPivotGroupDeemphasisStroke       *TSD.StrokeArchive             `protobuf:"bytes,90,opt,name=header_row_pivot_group_deemphasis_stroke,json=headerRowPivotGroupDeemphasisStroke" json:"header_row_pivot_group_deemphasis_stroke,omitempty"`
	HeaderRowPivotTitleStroke                 *TSD.StrokeArchive             `protobuf:"bytes,91,opt,name=header_row_pivot_title_stroke,json=headerRowPivotTitleStroke" json:"header_row_pivot_title_stroke,omitempty"`
	FooterRowPivotGroupVerticalStroke         *TSD.StrokeArchive             `protobuf:"bytes,92,opt,name=footer_row_pivot_group_vertical_stroke,json=footerRowPivotGroupVerticalStroke" json:"footer_row_pivot_group_vertical_stroke,omitempty"`
	unknownFields                             protoimpl.UnknownFields
	sizeCache                                 protoimpl.SizeCache
}

func (x *TableStylePropertiesArchive) Reset() {
	*x = TableStylePropertiesArchive{}
	mi := &file_TSTStylePropertyArchiving_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableStylePropertiesArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableStylePropertiesArchive) ProtoMessage() {}

func (x *TableStylePropertiesArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSTStylePropertyArchiving_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableStylePropertiesArchive.ProtoReflect.Descriptor instead.
func (*TableStylePropertiesArchive) Descriptor() ([]byte, []int) {
	return file_TSTStylePropertyArchiving_proto_rawDescGZIP(), []int{5}
}

func (x *TableStylePropertiesArchive) GetBandedRows() bool {
	if x != nil && x.BandedRows != nil {
		return *x.BandedRows
	}
	return false
}

func (x *TableStylePropertiesArchive) GetBandedFill() *TSD.FillArchive {
	if x != nil {
		return x.BandedFill
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetBehavesLikeSpreadsheet() bool {
	if x != nil && x.BehavesLikeSpreadsheet != nil {
		return *x.BehavesLikeSpreadsheet
	}
	return false
}

func (x *TableStylePropertiesArchive) GetAutoResize() bool {
	if x != nil && x.AutoResize != nil {
		return *x.AutoResize
	}
	return false
}

func (x *TableStylePropertiesArchive) GetDeprecatedHeaderRowSeparatorStroke() *Deprecated_TableStrokeArchive {
	if x != nil {
		return x.DeprecatedHeaderRowSeparatorStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetDeprecatedHeaderRowBorderStroke() *Deprecated_TableStrokeArchive {
	if x != nil {
		return x.DeprecatedHeaderRowBorderStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetDeprecatedHeaderRowHorizontalStroke() *Deprecated_TableStrokeArchive {
	if x != nil {
		return x.DeprecatedHeaderRowHorizontalStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetDeprecatedHeaderRowVerticalStroke() *Deprecated_TableStrokeArchive {
	if x != nil {
		return x.DeprecatedHeaderRowVerticalStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetDeprecatedHeaderColumnBorderStroke() *Deprecated_TableStrokeArchive {
	if x != nil {
		return x.DeprecatedHeaderColumnBorderStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetDeprecatedHeaderColumnSeparatorStroke() *Deprecated_TableStrokeArchive {
	if x != nil {
		return x.DeprecatedHeaderColumnSeparatorStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetDeprecatedHeaderColumnHorizontalStroke() *Deprecated_TableStrokeArchive {
	if x != nil {
		return x.DeprecatedHeaderColumnHorizontalStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetDeprecatedHeaderColumnVerticalStroke() *Deprecated_TableStrokeArchive {
	if x != nil {
		return x.DeprecatedHeaderColumnVerticalStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetDeprecatedFooterRowSeparatorStroke() *Deprecated_TableStrokeArchive {
	if x != nil {
		return x.DeprecatedFooterRowSeparatorStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetDeprecatedFooterRowBorderStroke() *Deprecated_TableStrokeArchive {
	if x != nil {
		return x.DeprecatedFooterRowBorderStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetDeprecatedFooterRowHorizontalStroke() *Deprecated_TableStrokeArchive {
	if x != nil {
		return x.DeprecatedFooterRowHorizontalStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetDeprecatedFooterRowVerticalStroke() *Deprecated_TableStrokeArchive {
	if x != nil {
		return x.DeprecatedFooterRowVerticalStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetDeprecatedTableBodyHorizontalBorderStroke() *Deprecated_TableStrokeArchive {
	if x != nil {
		return x.DeprecatedTableBodyHorizontalBorderStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetDeprecatedTableBodyVerticalBorderStroke() *Deprecated_TableStrokeArchive {
	if x != nil {
		return x.DeprecatedTableBodyVerticalBorderStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetDeprecatedTableBodyHorizontalStroke() *Deprecated_TableStrokeArchive {
	if x != nil {
		return x.DeprecatedTableBodyHorizontalStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetDeprecatedTableBodyVerticalStroke() *Deprecated_TableStrokeArchive {
	if x != nil {
		return x.DeprecatedTableBodyVerticalStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetStrokePresetList() *StrokePresetListArchive {
	if x != nil {
		return x.StrokePresetList
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetVStrokesVisible() bool {
	if x != nil && x.VStrokesVisible != nil {
		return *x.VStrokesVisible
	}
	return false
}

func (x *TableStylePropertiesArchive) GetHStrokesVisible() bool {
	if x != nil && x.HStrokesVisible != nil {
		return *x.HStrokesVisible
	}
	return false
}

func (x *TableStylePropertiesArchive) GetHrSeparatorVisible() bool {
	if x != nil && x.HrSeparatorVisible != nil {
		return *x.HrSeparatorVisible
	}
	return false
}

func (x *TableStylePropertiesArchive) GetHcSeparatorVisible() bool {
	if x != nil && x.HcSeparatorVisible != nil {
		return *x.HcSeparatorVisible
	}
	return false
}

func (x *TableStylePropertiesArchive) GetFooterSeparatorVisible() bool {
	if x != nil && x.FooterSeparatorVisible != nil {
		return *x.FooterSeparatorVisible
	}
	return false
}

func (x *TableStylePropertiesArchive) GetTableBorderVisible() bool {
	if x != nil && x.TableBorderVisible != nil {
		return *x.TableBorderVisible
	}
	return false
}

func (x *TableStylePropertiesArchive) GetTableHeaderBorderVisible() bool {
	if x != nil && x.TableHeaderBorderVisible != nil {
		return *x.TableHeaderBorderVisible
	}
	return false
}

func (x *TableStylePropertiesArchive) GetTableHcDividerVisible() bool {
	if x != nil && x.TableHcDividerVisible != nil {
		return *x.TableHcDividerVisible
	}
	return false
}

func (x *TableStylePropertiesArchive) GetTableHrDividerVisible() bool {
	if x != nil && x.TableHrDividerVisible != nil {
		return *x.TableHrDividerVisible
	}
	return false
}

func (x *TableStylePropertiesArchive) GetTableFooterDividerVisible() bool {
	if x != nil && x.TableFooterDividerVisible != nil {
		return *x.TableFooterDividerVisible
	}
	return false
}

func (x *TableStylePropertiesArchive) GetOBSOLETEMasterFontSize() int32 {
	if x != nil && x.OBSOLETEMasterFontSize != nil {
		return *x.OBSOLETEMasterFontSize
	}
	return 0
}

func (x *TableStylePropertiesArchive) GetMasterFontFamily() string {
	if x != nil && x.MasterFontFamily != nil {
		return *x.MasterFontFamily
	}
	return ""
}

func (x *TableStylePropertiesArchive) GetWritingDirection() TSWP.WritingDirectionType {
	if x != nil && x.WritingDirection != nil {
		return *x.WritingDirection
	}
	return TSWP.WritingDirectionType(-1)
}

func (x *TableStylePropertiesArchive) GetHeaderRowSeparatorStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.HeaderRowSeparatorStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetHeaderRowBorderStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.HeaderRowBorderStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetHeaderRowHorizontalStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.HeaderRowHorizontalStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetHeaderRowVerticalStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.HeaderRowVerticalStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetHeaderColumnBorderStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.HeaderColumnBorderStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetHeaderColumnSeparatorStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.HeaderColumnSeparatorStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetHeaderColumnHorizontalStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.HeaderColumnHorizontalStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetHeaderColumnVerticalStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.HeaderColumnVerticalStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetFooterRowSeparatorStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.FooterRowSeparatorStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetFooterRowBorderStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.FooterRowBorderStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetFooterRowHorizontalStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.FooterRowHorizontalStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetFooterRowVerticalStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.FooterRowVerticalStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetTableBodyHorizontalBorderStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.TableBodyHorizontalBorderStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetTableBodyVerticalBorderStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.TableBodyVerticalBorderStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetTableBodyHorizontalStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.TableBodyHorizontalStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetTableBodyVerticalStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.TableBodyVerticalStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetCategoryLevel1TopStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.CategoryLevel1TopStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetCategoryLevel2TopStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.CategoryLevel2TopStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetCategoryLevel3TopStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.CategoryLevel3TopStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetCategoryLevel4TopStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.CategoryLevel4TopStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetCategoryLevel5TopStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.CategoryLevel5TopStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetCategoryLevel1BottomStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.CategoryLevel1BottomStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetCategoryLevel2BottomStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.CategoryLevel2BottomStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetCategoryLevel3BottomStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.CategoryLevel3BottomStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetCategoryLevel4BottomStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.CategoryLevel4BottomStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetCategoryLevel5BottomStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.CategoryLevel5BottomStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetCategoryLevel1InteriorStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.CategoryLevel1InteriorStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetCategoryLevel2InteriorStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.CategoryLevel2InteriorStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetCategoryLevel3InteriorStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.CategoryLevel3InteriorStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetCategoryLevel4InteriorStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.CategoryLevel4InteriorStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetCategoryLevel5InteriorStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.CategoryLevel5InteriorStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetCategoryLevel1LabelSeparatorStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.CategoryLevel1LabelSeparatorStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetCategoryLevel2LabelSeparatorStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.CategoryLevel2LabelSeparatorStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetCategoryLevel3LabelSeparatorStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.CategoryLevel3LabelSeparatorStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetCategoryLevel4LabelSeparatorStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.CategoryLevel4LabelSeparatorStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetCategoryLevel5LabelSeparatorStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.CategoryLevel5LabelSeparatorStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetTableBodyPivotGroupHorizontalStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.TableBodyPivotGroupHorizontalStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetTableBodyPivotGroupVerticalStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.TableBodyPivotGroupVerticalStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetTableBodyPivotDeemphasisHorizontalStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.TableBodyPivotDeemphasisHorizontalStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetTableBodyPivotEmphasisVerticalStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.TableBodyPivotEmphasisVerticalStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetHeaderColumnPivotGroupHorizontalStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.HeaderColumnPivotGroupHorizontalStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetHeaderColumnPivotGroupDeemphasisStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.HeaderColumnPivotGroupDeemphasisStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetHeaderColumnPivotSeparatorStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.HeaderColumnPivotSeparatorStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetHeaderRowPivotGroupVerticalStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.HeaderRowPivotGroupVerticalStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetHeaderRowPivotGroupDeemphasisStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.HeaderRowPivotGroupDeemphasisStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetHeaderRowPivotTitleStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.HeaderRowPivotTitleStroke
	}
	return nil
}

func (x *TableStylePropertiesArchive) GetFooterRowPivotGroupVerticalStroke() *TSD.StrokeArchive {
	if x != nil {
		return x.FooterRowPivotGroupVerticalStroke
	}
	return nil
}

type TableStylePresetArchive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         *int32                 `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	Image         *TSP.Reference         `protobuf:"bytes,2,opt,name=image" json:"image,omitempty"`
	StyleNetwork  *TSP.Reference         `protobuf:"bytes,3,opt,name=style_network,json=styleNetwork" json:"style_network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableStylePresetArchive) Reset() {
	*x = TableStylePresetArchive{}
	mi := &file_TSTStylePropertyArchiving_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableStylePresetArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableStylePresetArchive) ProtoMessage() {}

func (x *TableStylePresetArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSTStylePropertyArchiving_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableStylePresetArchive.ProtoReflect.Descriptor instead.
func (*TableStylePresetArchive) Descriptor() ([]byte, []int) {
	return file_TSTStylePropertyArchiving_proto_rawDescGZIP(), []int{6}
}

func (x *TableStylePresetArchive) GetIndex() int32 {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return 0
}

func (x *TableStylePresetArchive) GetImage() *TSP.Reference {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *TableStylePresetArchive) GetStyleNetwork() *TSP.Reference {
	if x != nil {
		return x.StyleNetwork
	}
	return nil
}

type TableStrokePresetArchive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         *int32                 `protobuf:"varint,1,req,name=index" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableStrokePresetArchive) Reset() {
	*x = TableStrokePresetArchive{}
	mi := &file_TSTStylePropertyArchiving_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableStrokePresetArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableStrokePresetArchive) ProtoMessage() {}

func (x *TableStrokePresetArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSTStylePropertyArchiving_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableStrokePresetArchive.ProtoReflect.Descriptor instead.
func (*TableStrokePresetArchive) Descriptor() ([]byte, []int) {
	return file_TSTStylePropertyArchiving_proto_rawDescGZIP(), []int{7}
}

func (x *TableStrokePresetArchive) GetIndex() int32 {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return 0
}

type ThemePresetsArchive struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TableStylePresets      []*TSP.Reference       `protobuf:"bytes,1,rep,name=table_style_presets,json=tableStylePresets" json:"table_style_presets,omitempty"`
	TableCellStrokePresets []*TSP.Reference       `protobuf:"bytes,2,rep,name=table_cell_stroke_presets,json=tableCellStrokePresets" json:"table_cell_stroke_presets,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ThemePresetsArchive) Reset() {
	*x = ThemePresetsArchive{}
	mi := &file_TSTStylePropertyArchiving_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThemePresetsArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThemePresetsArchive) ProtoMessage() {}

func (x *ThemePresetsArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSTStylePropertyArchiving_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThemePresetsArchive.ProtoReflect.Descriptor instead.
func (*ThemePresetsArchive) Descriptor() ([]byte, []int) {
	return file_TSTStylePropertyArchiving_proto_rawDescGZIP(), []int{8}
}

func (x *ThemePresetsArchive) GetTableStylePresets() []*TSP.Reference {
	if x != nil {
		return x.TableStylePresets
	}
	return nil
}

func (x *ThemePresetsArchive) GetTableCellStrokePresets() []*TSP.Reference {
	if x != nil {
		return x.TableCellStrokePresets
	}
	return nil
}

var File_TSTStylePropertyArchiving_proto protoreflect.FileDescriptor

const file_TSTStylePropertyArchiving_proto_rawDesc = "" +
	"\n" +
	"\x1fTSTStylePropertyArchiving.proto\x12\x03TST\x1a\x11TSPMessages.proto\x1a\x11TSDArchives.proto\x1a\x11TSKArchives.proto\x1a\x11TSSArchives.proto\x1a\x12TSWPArchives.proto\"\x9b\x01\n" +
	"\x1dDeprecated_TableStrokeArchive\x12*\n" +
	"\x06stroke\x18\x01 \x01(\v2\x12.TSD.StrokeArchiveR\x06stroke\x12\x1e\n" +
	"\n" +
	"background\x18\x02 \x01(\bR\n" +
	"background\x12\x18\n" +
	"\aopacity\x18\x03 \x01(\x02R\aopacity\x12\x14\n" +
	"\x05empty\x18\x04 \x01(\bR\x05empty\"\x8b\x06\n" +
	"\x1aCellStylePropertiesArchive\x12-\n" +
	"\tcell_fill\x18\x01 \x01(\v2\x10.TSD.FillArchiveR\bcellFill\x12\x1b\n" +
	"\ttext_wrap\x18\x03 \x01(\bR\btextWrap\x12V\n" +
	"\x15deprecated_top_stroke\x18\x04 \x01(\v2\".TST.Deprecated_TableStrokeArchiveR\x13deprecatedTopStroke\x12Z\n" +
	"\x17deprecated_right_stroke\x18\x05 \x01(\v2\".TST.Deprecated_TableStrokeArchiveR\x15deprecatedRightStroke\x12\\\n" +
	"\x18deprecated_bottom_stroke\x18\x06 \x01(\v2\".TST.Deprecated_TableStrokeArchiveR\x16deprecatedBottomStroke\x12X\n" +
	"\x16deprecated_left_stroke\x18\a \x01(\v2\".TST.Deprecated_TableStrokeArchiveR\x14deprecatedLeftStroke\x12-\n" +
	"\x12vertical_alignment\x18\b \x01(\x05R\x11verticalAlignment\x12.\n" +
	"\apadding\x18\t \x01(\v2\x14.TSWP.PaddingArchiveR\apadding\x121\n" +
	"\n" +
	"top_stroke\x18\n" +
	" \x01(\v2\x12.TSD.StrokeArchiveR\ttopStroke\x125\n" +
	"\fright_stroke\x18\v \x01(\v2\x12.TSD.StrokeArchiveR\vrightStroke\x127\n" +
	"\rbottom_stroke\x18\f \x01(\v2\x12.TSD.StrokeArchiveR\fbottomStroke\x123\n" +
	"\vleft_stroke\x18\r \x01(\v2\x12.TSD.StrokeArchiveR\n" +
	"leftStroke\"\x86\x03\n" +
	"\"Deprecated_StrokePresetDataArchive\x12d\n" +
	"\x1cdeprecated_horizontal_stroke\x18\x02 \x02(\v2\".TST.Deprecated_TableStrokeArchiveR\x1adeprecatedHorizontalStroke\x12`\n" +
	"\x1adeprecated_vertical_stroke\x18\x01 \x02(\v2\".TST.Deprecated_TableStrokeArchiveR\x18deprecatedVerticalStroke\x12`\n" +
	"\x1adeprecated_exterior_stroke\x18\x03 \x02(\v2\".TST.Deprecated_TableStrokeArchiveR\x18deprecatedExteriorStroke\x126\n" +
	"\x17deprecated_visible_mask\x18\x05 \x02(\x05R\x15deprecatedVisibleMask\"\xf7\x01\n" +
	"\x17StrokePresetDataArchive\x12?\n" +
	"\x11horizontal_stroke\x18\x01 \x01(\v2\x12.TSD.StrokeArchiveR\x10horizontalStroke\x12;\n" +
	"\x0fvertical_stroke\x18\x02 \x01(\v2\x12.TSD.StrokeArchiveR\x0everticalStroke\x12;\n" +
	"\x0fexterior_stroke\x18\x03 \x01(\v2\x12.TSD.StrokeArchiveR\x0eexteriorStroke\x12!\n" +
	"\fvisible_mask\x18\x04 \x01(\x05R\vvisibleMask\"\xbb\x01\n" +
	"\x17StrokePresetListArchive\x12\x14\n" +
	"\x05count\x18\x01 \x02(\x05R\x05count\x12T\n" +
	"\x11deprecated_preset\x18\x02 \x03(\v2'.TST.Deprecated_StrokePresetDataArchiveR\x10deprecatedPreset\x124\n" +
	"\x06preset\x18\x03 \x03(\v2\x1c.TST.StrokePresetDataArchiveR\x06preset\"\xf68\n" +
	"\x1bTableStylePropertiesArchive\x12\x1f\n" +
	"\vbanded_rows\x18\x01 \x01(\bR\n" +
	"bandedRows\x121\n" +
	"\vbanded_fill\x18\x02 \x01(\v2\x10.TSD.FillArchiveR\n" +
	"bandedFill\x128\n" +
	"\x18behaves_like_spreadsheet\x18\x15 \x01(\bR\x16behavesLikeSpreadsheet\x12\x1f\n" +
	"\vauto_resize\x18\x16 \x01(\bR\n" +
	"autoResize\x12v\n" +
	"&deprecated_header_row_separator_stroke\x18\x04 \x01(\v2\".TST.Deprecated_TableStrokeArchiveR\"deprecatedHeaderRowSeparatorStroke\x12p\n" +
	"#deprecated_header_row_border_stroke\x18\x05 \x01(\v2\".TST.Deprecated_TableStrokeArchiveR\x1fdeprecatedHeaderRowBorderStroke\x12x\n" +
	"'deprecated_header_row_horizontal_stroke\x18\x17 \x01(\v2\".TST.Deprecated_TableStrokeArchiveR#deprecatedHeaderRowHorizontalStroke\x12t\n" +
	"%deprecated_header_row_vertical_stroke\x18\x18 \x01(\v2\".TST.Deprecated_TableStrokeArchiveR!deprecatedHeaderRowVerticalStroke\x12v\n" +
	"&deprecated_header_column_border_stroke\x18\a \x01(\v2\".TST.Deprecated_TableStrokeArchiveR\"deprecatedHeaderColumnBorderStroke\x12|\n" +
	")deprecated_header_column_separator_stroke\x18\b \x01(\v2\".TST.Deprecated_TableStrokeArchiveR%deprecatedHeaderColumnSeparatorStroke\x12~\n" +
	"*deprecated_header_column_horizontal_stroke\x18\x19 \x01(\v2\".TST.Deprecated_TableStrokeArchiveR&deprecatedHeaderColumnHorizontalStroke\x12z\n" +
	"(deprecated_header_column_vertical_stroke\x18\x1a \x01(\v2\".TST.Deprecated_TableStrokeArchiveR$deprecatedHeaderColumnVerticalStroke\x12v\n" +
	"&deprecated_footer_row_separator_stroke\x18\n" +
	" \x01(\v2\".TST.Deprecated_TableStrokeArchiveR\"deprecatedFooterRowSeparatorStroke\x12p\n" +
	"#deprecated_footer_row_border_stroke\x18\v \x01(\v2\".TST.Deprecated_TableStrokeArchiveR\x1fdeprecatedFooterRowBorderStroke\x12x\n" +
	"'deprecated_footer_row_horizontal_stroke\x18\x1b \x01(\v2\".TST.Deprecated_TableStrokeArchiveR#deprecatedFooterRowHorizontalStroke\x12t\n" +
	"%deprecated_footer_row_vertical_stroke\x18\x1c \x01(\v2\".TST.Deprecated_TableStrokeArchiveR!deprecatedFooterRowVerticalStroke\x12\x85\x01\n" +
	".deprecated_table_body_horizontal_border_stroke\x18\f \x01(\v2\".TST.Deprecated_TableStrokeArchiveR)deprecatedTableBodyHorizontalBorderStroke\x12\x81\x01\n" +
	",deprecated_table_body_vertical_border_stroke\x18\x1d \x01(\v2\".TST.Deprecated_TableStrokeArchiveR'deprecatedTableBodyVerticalBorderStroke\x12x\n" +
	"'deprecated_table_body_horizontal_stroke\x18\x1e \x01(\v2\".TST.Deprecated_TableStrokeArchiveR#deprecatedTableBodyHorizontalStroke\x12t\n" +
	"%deprecated_table_body_vertical_stroke\x18\x1f \x01(\v2\".TST.Deprecated_TableStrokeArchiveR!deprecatedTableBodyVerticalStroke\x12J\n" +
	"\x12stroke_preset_list\x18  \x01(\v2\x1c.TST.StrokePresetListArchiveR\x10strokePresetList\x12*\n" +
	"\x11v_strokes_visible\x18! \x01(\bR\x0fvStrokesVisible\x12*\n" +
	"\x11h_strokes_visible\x18\" \x01(\bR\x0fhStrokesVisible\x120\n" +
	"\x14hr_separator_visible\x18# \x01(\bR\x12hrSeparatorVisible\x120\n" +
	"\x14hc_separator_visible\x18$ \x01(\bR\x12hcSeparatorVisible\x128\n" +
	"\x18footer_separator_visible\x18% \x01(\bR\x16footerSeparatorVisible\x120\n" +
	"\x14table_border_visible\x18& \x01(\bR\x12tableBorderVisible\x12=\n" +
	"\x1btable_header_border_visible\x18' \x01(\bR\x18tableHeaderBorderVisible\x127\n" +
	"\x18table_hc_divider_visible\x18* \x01(\bR\x15tableHcDividerVisible\x127\n" +
	"\x18table_hr_divider_visible\x18+ \x01(\bR\x15tableHrDividerVisible\x12?\n" +
	"\x1ctable_footer_divider_visible\x18, \x01(\bR\x19tableFooterDividerVisible\x129\n" +
	"\x19OBSOLETE_master_font_size\x18( \x01(\x05R\x16OBSOLETEMasterFontSize\x12,\n" +
	"\x12master_font_family\x18) \x01(\tR\x10masterFontFamily\x12G\n" +
	"\x11writing_direction\x18- \x01(\x0e2\x1a.TSWP.WritingDirectionTypeR\x10writingDirection\x12Q\n" +
	"\x1bheader_row_separator_stroke\x18. \x01(\v2\x12.TSD.StrokeArchiveR\x18headerRowSeparatorStroke\x12K\n" +
	"\x18header_row_border_stroke\x18/ \x01(\v2\x12.TSD.StrokeArchiveR\x15headerRowBorderStroke\x12S\n" +
	"\x1cheader_row_horizontal_stroke\x180 \x01(\v2\x12.TSD.StrokeArchiveR\x19headerRowHorizontalStroke\x12O\n" +
	"\x1aheader_row_vertical_stroke\x181 \x01(\v2\x12.TSD.StrokeArchiveR\x17headerRowVerticalStroke\x12Q\n" +
	"\x1bheader_column_border_stroke\x182 \x01(\v2\x12.TSD.StrokeArchiveR\x18headerColumnBorderStroke\x12W\n" +
	"\x1eheader_column_separator_stroke\x183 \x01(\v2\x12.TSD.StrokeArchiveR\x1bheaderColumnSeparatorStroke\x12Y\n" +
	"\x1fheader_column_horizontal_stroke\x184 \x01(\v2\x12.TSD.StrokeArchiveR\x1cheaderColumnHorizontalStroke\x12U\n" +
	"\x1dheader_column_vertical_stroke\x185 \x01(\v2\x12.TSD.StrokeArchiveR\x1aheaderColumnVerticalStroke\x12Q\n" +
	"\x1bfooter_row_separator_stroke\x186 \x01(\v2\x12.TSD.StrokeArchiveR\x18footerRowSeparatorStroke\x12K\n" +
	"\x18footer_row_border_stroke\x187 \x01(\v2\x12.TSD.StrokeArchiveR\x15footerRowBorderStroke\x12S\n" +
	"\x1cfooter_row_horizontal_stroke\x188 \x01(\v2\x12.TSD.StrokeArchiveR\x19footerRowHorizontalStroke\x12O\n" +
	"\x1afooter_row_vertical_stroke\x189 \x01(\v2\x12.TSD.StrokeArchiveR\x17footerRowVerticalStroke\x12`\n" +
	"#table_body_horizontal_border_stroke\x18: \x01(\v2\x12.TSD.StrokeArchiveR\x1ftableBodyHorizontalBorderStroke\x12\\\n" +
	"!table_body_vertical_border_stroke\x18; \x01(\v2\x12.TSD.StrokeArchiveR\x1dtableBodyVerticalBorderStroke\x12S\n" +
	"\x1ctable_body_horizontal_stroke\x18< \x01(\v2\x12.TSD.StrokeArchiveR\x19tableBodyHorizontalStroke\x12O\n" +
	"\x1atable_body_vertical_stroke\x18= \x01(\v2\x12.TSD.StrokeArchiveR\x17tableBodyVerticalStroke\x12O\n" +
	"\x1acategory_level1_top_stroke\x18> \x01(\v2\x12.TSD.StrokeArchiveR\x17categoryLevel1TopStroke\x12O\n" +
	"\x1acategory_level2_top_stroke\x18? \x01(\v2\x12.TSD.StrokeArchiveR\x17categoryLevel2TopStroke\x12O\n" +
	"\x1acategory_level3_top_stroke\x18@ \x01(\v2\x12.TSD.StrokeArchiveR\x17categoryLevel3TopStroke\x12O\n" +
	"\x1acategory_level4_top_stroke\x18A \x01(\v2\x12.TSD.StrokeArchiveR\x17categoryLevel4TopStroke\x12O\n" +
	"\x1acategory_level5_top_stroke\x18B \x01(\v2\x12.TSD.StrokeArchiveR\x17categoryLevel5TopStroke\x12U\n" +
	"\x1dcategory_level1_bottom_stroke\x18C \x01(\v2\x12.TSD.StrokeArchiveR\x1acategoryLevel1BottomStroke\x12U\n" +
	"\x1dcategory_level2_bottom_stroke\x18D \x01(\v2\x12.TSD.StrokeArchiveR\x1acategoryLevel2BottomStroke\x12U\n" +
	"\x1dcategory_level3_bottom_stroke\x18E \x01(\v2\x12.TSD.StrokeArchiveR\x1acategoryLevel3BottomStroke\x12U\n" +
	"\x1dcategory_level4_bottom_stroke\x18F \x01(\v2\x12.TSD.StrokeArchiveR\x1acategoryLevel4BottomStroke\x12U\n" +
	"\x1dcategory_level5_bottom_stroke\x18G \x01(\v2\x12.TSD.StrokeArchiveR\x1acategoryLevel5BottomStroke\x12Y\n" +
	"\x1fcategory_level1_interior_stroke\x18H \x01(\v2\x12.TSD.StrokeArchiveR\x1ccategoryLevel1InteriorStroke\x12Y\n" +
	"\x1fcategory_level2_interior_stroke\x18I \x01(\v2\x12.TSD.StrokeArchiveR\x1ccategoryLevel2InteriorStroke\x12Y\n" +
	"\x1fcategory_level3_interior_stroke\x18J \x01(\v2\x12.TSD.StrokeArchiveR\x1ccategoryLevel3InteriorStroke\x12Y\n" +
	"\x1fcategory_level4_interior_stroke\x18K \x01(\v2\x12.TSD.StrokeArchiveR\x1ccategoryLevel4InteriorStroke\x12Y\n" +
	"\x1fcategory_level5_interior_stroke\x18L \x01(\v2\x12.TSD.StrokeArchiveR\x1ccategoryLevel5InteriorStroke\x12f\n" +
	"&category_level1_label_separator_stroke\x18M \x01(\v2\x12.TSD.StrokeArchiveR\"categoryLevel1LabelSeparatorStroke\x12f\n" +
	"&category_level2_label_separator_stroke\x18N \x01(\v2\x12.TSD.StrokeArchiveR\"categoryLevel2LabelSeparatorStroke\x12f\n" +
	"&category_level3_label_separator_stroke\x18O \x01(\v2\x12.TSD.StrokeArchiveR\"categoryLevel3LabelSeparatorStroke\x12f\n" +
	"&category_level4_label_separator_stroke\x18P \x01(\v2\x12.TSD.StrokeArchiveR\"categoryLevel4LabelSeparatorStroke\x12f\n" +
	"&category_level5_label_separator_stroke\x18Q \x01(\v2\x12.TSD.StrokeArchiveR\"categoryLevel5LabelSeparatorStroke\x12i\n" +
	"(table_body_pivot_group_horizontal_stroke\x18R \x01(\v2\x12.TSD.StrokeArchiveR#tableBodyPivotGroupHorizontalStroke\x12e\n" +
	"&table_body_pivot_group_vertical_stroke\x18S \x01(\v2\x12.TSD.StrokeArchiveR!tableBodyPivotGroupVerticalStroke\x12s\n" +
	"-table_body_pivot_deemphasis_horizontal_stroke\x18T \x01(\v2\x12.TSD.StrokeArchiveR(tableBodyPivotDeemphasisHorizontalStroke\x12k\n" +
	")table_body_pivot_emphasis_vertical_stroke\x18U \x01(\v2\x12.TSD.StrokeArchiveR$tableBodyPivotEmphasisVerticalStroke\x12o\n" +
	"+header_column_pivot_group_horizontal_stroke\x18V \x01(\v2\x12.TSD.StrokeArchiveR&headerColumnPivotGroupHorizontalStroke\x12o\n" +
	"+header_column_pivot_group_deemphasis_stroke\x18W \x01(\v2\x12.TSD.StrokeArchiveR&headerColumnPivotGroupDeemphasisStroke\x12b\n" +
	"$header_column_pivot_separator_stroke\x18X \x01(\v2\x12.TSD.StrokeArchiveR headerColumnPivotSeparatorStroke\x12e\n" +
	"&header_row_pivot_group_vertical_stroke\x18Y \x01(\v2\x12.TSD.StrokeArchiveR!headerRowPivotGroupVerticalStroke\x12i\n" +
	"(header_row_pivot_group_deemphasis_stroke\x18Z \x01(\v2\x12.TSD.StrokeArchiveR#headerRowPivotGroupDeemphasisStroke\x12T\n" +
	"\x1dheader_row_pivot_title_stroke\x18[ \x01(\v2\x12.TSD.StrokeArchiveR\x19headerRowPivotTitleStroke\x12e\n" +
	"&footer_row_pivot_group_vertical_stroke\x18\\ \x01(\v2\x12.TSD.StrokeArchiveR!footerRowPivotGroupVerticalStroke\"\x8a\x01\n" +
	"\x17TableStylePresetArchive\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12$\n" +
	"\x05image\x18\x02 \x01(\v2\x0e.TSP.ReferenceR\x05image\x123\n" +
	"\rstyle_network\x18\x03 \x01(\v2\x0e.TSP.ReferenceR\fstyleNetwork\"0\n" +
	"\x18TableStrokePresetArchive\x12\x14\n" +
	"\x05index\x18\x01 \x02(\x05R\x05index\"\xa0\x01\n" +
	"\x13ThemePresetsArchive\x12>\n" +
	"\x13table_style_presets\x18\x01 \x03(\v2\x0e.TSP.ReferenceR\x11tableStylePresets\x12I\n" +
	"\x19table_cell_stroke_presets\x18\x02 \x03(\v2\x0e.TSP.ReferenceR\x16tableCellStrokePresetsB/Z-github.com/orcastor/iwork-converter/proto/TST"

var (
	file_TSTStylePropertyArchiving_proto_rawDescOnce sync.Once
	file_TSTStylePropertyArchiving_proto_rawDescData []byte
)

func file_TSTStylePropertyArchiving_proto_rawDescGZIP() []byte {
	file_TSTStylePropertyArchiving_proto_rawDescOnce.Do(func() {
		file_TSTStylePropertyArchiving_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_TSTStylePropertyArchiving_proto_rawDesc), len(file_TSTStylePropertyArchiving_proto_rawDesc)))
	})
	return file_TSTStylePropertyArchiving_proto_rawDescData
}

var file_TSTStylePropertyArchiving_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_TSTStylePropertyArchiving_proto_goTypes = []any{
	(*Deprecated_TableStrokeArchive)(nil),      // 0: TST.Deprecated_TableStrokeArchive
	(*CellStylePropertiesArchive)(nil),         // 1: TST.CellStylePropertiesArchive
	(*Deprecated_StrokePresetDataArchive)(nil), // 2: TST.Deprecated_StrokePresetDataArchive
	(*StrokePresetDataArchive)(nil),            // 3: TST.StrokePresetDataArchive
	(*StrokePresetListArchive)(nil),            // 4: TST.StrokePresetListArchive
	(*TableStylePropertiesArchive)(nil),        // 5: TST.TableStylePropertiesArchive
	(*TableStylePresetArchive)(nil),            // 6: TST.TableStylePresetArchive
	(*TableStrokePresetArchive)(nil),           // 7: TST.TableStrokePresetArchive
	(*ThemePresetsArchive)(nil),                // 8: TST.ThemePresetsArchive
	(*TSD.StrokeArchive)(nil),                  // 9: TSD.StrokeArchive
	(*TSD.FillArchive)(nil),                    // 10: TSD.FillArchive
	(*TSWP.PaddingArchive)(nil),                // 11: TSWP.PaddingArchive
	(TSWP.WritingDirectionType)(0),             // 12: TSWP.WritingDirectionType
	(*TSP.Reference)(nil),                      // 13: TSP.Reference
}
var file_TSTStylePropertyArchiving_proto_depIdxs = []int32{
	9,  // 0: TST.Deprecated_TableStrokeArchive.stroke:type_name -> TSD.StrokeArchive
	10, // 1: TST.CellStylePropertiesArchive.cell_fill:type_name -> TSD.FillArchive
	0,  // 2: TST.CellStylePropertiesArchive.deprecated_top_stroke:type_name -> TST.Deprecated_TableStrokeArchive
	0,  // 3: TST.CellStylePropertiesArchive.deprecated_right_stroke:type_name -> TST.Deprecated_TableStrokeArchive
	0,  // 4: TST.CellStylePropertiesArchive.deprecated_bottom_stroke:type_name -> TST.Deprecated_TableStrokeArchive
	0,  // 5: TST.CellStylePropertiesArchive.deprecated_left_stroke:type_name -> TST.Deprecated_TableStrokeArchive
	11, // 6: TST.CellStylePropertiesArchive.padding:type_name -> TSWP.PaddingArchive
	9,  // 7: TST.CellStylePropertiesArchive.top_stroke:type_name -> TSD.StrokeArchive
	9,  // 8: TST.CellStylePropertiesArchive.right_stroke:type_name -> TSD.StrokeArchive
	9,  // 9: TST.CellStylePropertiesArchive.bottom_stroke:type_name -> TSD.StrokeArchive
	9,  // 10: TST.CellStylePropertiesArchive.left_stroke:type_name -> TSD.StrokeArchive
	0,  // 11: TST.Deprecated_StrokePresetDataArchive.deprecated_horizontal_stroke:type_name -> TST.Deprecated_TableStrokeArchive
	0,  // 12: TST.Deprecated_StrokePresetDataArchive.deprecated_vertical_stroke:type_name -> TST.Deprecated_TableStrokeArchive
	0,  // 13: TST.Deprecated_StrokePresetDataArchive.deprecated_exterior_stroke:type_name -> TST.Deprecated_TableStrokeArchive
	9,  // 14: TST.StrokePresetDataArchive.horizontal_stroke:type_name -> TSD.StrokeArchive
	9,  // 15: TST.StrokePresetDataArchive.vertical_stroke:type_name -> TSD.StrokeArchive
	9,  // 16: TST.StrokePresetDataArchive.exterior_stroke:type_name -> TSD.StrokeArchive
	2,  // 17: TST.StrokePresetListArchive.deprecated_preset:type_name -> TST.Deprecated_StrokePresetDataArchive
	3,  // 18: TST.StrokePresetListArchive.preset:type_name -> TST.StrokePresetDataArchive
	10, // 19: TST.TableStylePropertiesArchive.banded_fill:type_name -> TSD.FillArchive
	0,  // 20: TST.TableStylePropertiesArchive.deprecated_header_row_separator_stroke:type_name -> TST.Deprecated_TableStrokeArchive
	0,  // 21: TST.TableStylePropertiesArchive.deprecated_header_row_border_stroke:type_name -> TST.Deprecated_TableStrokeArchive
	0,  // 22: TST.TableStylePropertiesArchive.deprecated_header_row_horizontal_stroke:type_name -> TST.Deprecated_TableStrokeArchive
	0,  // 23: TST.TableStylePropertiesArchive.deprecated_header_row_vertical_stroke:type_name -> TST.Deprecated_TableStrokeArchive
	0,  // 24: TST.TableStylePropertiesArchive.deprecated_header_column_border_stroke:type_name -> TST.Deprecated_TableStrokeArchive
	0,  // 25: TST.TableStylePropertiesArchive.deprecated_header_column_separator_stroke:type_name -> TST.Deprecated_TableStrokeArchive
	0,  // 26: TST.TableStylePropertiesArchive.deprecated_header_column_horizontal_stroke:type_name -> TST.Deprecated_TableStrokeArchive
	0,  // 27: TST.TableStylePropertiesArchive.deprecated_header_column_vertical_stroke:type_name -> TST.Deprecated_TableStrokeArchive
	0,  // 28: TST.TableStylePropertiesArchive.deprecated_footer_row_separator_stroke:type_name -> TST.Deprecated_TableStrokeArchive
	0,  // 29: TST.TableStylePropertiesArchive.deprecated_footer_row_border_stroke:type_name -> TST.Deprecated_TableStrokeArchive
	0,  // 30: TST.TableStylePropertiesArchive.deprecated_footer_row_horizontal_stroke:type_name -> TST.Deprecated_TableStrokeArchive
	0,  // 31: TST.TableStylePropertiesArchive.deprecated_footer_row_vertical_stroke:type_name -> TST.Deprecated_TableStrokeArchive
	0,  // 32: TST.TableStylePropertiesArchive.deprecated_table_body_horizontal_border_stroke:type_name -> TST.Deprecated_TableStrokeArchive
	0,  // 33: TST.TableStylePropertiesArchive.deprecated_table_body_vertical_border_stroke:type_name -> TST.Deprecated_TableStrokeArchive
	0,  // 34: TST.TableStylePropertiesArchive.deprecated_table_body_horizontal_stroke:type_name -> TST.Deprecated_TableStrokeArchive
	0,  // 35: TST.TableStylePropertiesArchive.deprecated_table_body_vertical_stroke:type_name -> TST.Deprecated_TableStrokeArchive
	4,  // 36: TST.TableStylePropertiesArchive.stroke_preset_list:type_name -> TST.StrokePresetListArchive
	12, // 37: TST.TableStylePropertiesArchive.writing_direction:type_name -> TSWP.WritingDirectionType
	9,  // 38: TST.TableStylePropertiesArchive.header_row_separator_stroke:type_name -> TSD.StrokeArchive
	9,  // 39: TST.TableStylePropertiesArchive.header_row_border_stroke:type_name -> TSD.StrokeArchive
	9,  // 40: TST.TableStylePropertiesArchive.header_row_horizontal_stroke:type_name -> TSD.StrokeArchive
	9,  // 41: TST.TableStylePropertiesArchive.header_row_vertical_stroke:type_name -> TSD.StrokeArchive
	9,  // 42: TST.TableStylePropertiesArchive.header_column_border_stroke:type_name -> TSD.StrokeArchive
	9,  // 43: TST.TableStylePropertiesArchive.header_column_separator_stroke:type_name -> TSD.StrokeArchive
	9,  // 44: TST.TableStylePropertiesArchive.header_column_horizontal_stroke:type_name -> TSD.StrokeArchive
	9,  // 45: TST.TableStylePropertiesArchive.header_column_vertical_stroke:type_name -> TSD.StrokeArchive
	9,  // 46: TST.TableStylePropertiesArchive.footer_row_separator_stroke:type_name -> TSD.StrokeArchive
	9,  // 47: TST.TableStylePropertiesArchive.footer_row_border_stroke:type_name -> TSD.StrokeArchive
	9,  // 48: TST.TableStylePropertiesArchive.footer_row_horizontal_stroke:type_name -> TSD.StrokeArchive
	9,  // 49: TST.TableStylePropertiesArchive.footer_row_vertical_stroke:type_name -> TSD.StrokeArchive
	9,  // 50: TST.TableStylePropertiesArchive.table_body_horizontal_border_stroke:type_name -> TSD.StrokeArchive
	9,  // 51: TST.TableStylePropertiesArchive.table_body_vertical_border_stroke:type_name -> TSD.StrokeArchive
	9,  // 52: TST.TableStylePropertiesArchive.table_body_horizontal_stroke:type_name -> TSD.StrokeArchive
	9,  // 53: TST.TableStylePropertiesArchive.table_body_vertical_stroke:type_name -> TSD.StrokeArchive
	9,  // 54: TST.TableStylePropertiesArchive.category_level1_top_stroke:type_name -> TSD.StrokeArchive
	9,  // 55: TST.TableStylePropertiesArchive.category_level2_top_stroke:type_name -> TSD.StrokeArchive
	9,  // 56: TST.TableStylePropertiesArchive.category_level3_top_stroke:type_name -> TSD.StrokeArchive
	9,  // 57: TST.TableStylePropertiesArchive.category_level4_top_stroke:type_name -> TSD.StrokeArchive
	9,  // 58: TST.TableStylePropertiesArchive.category_level5_top_stroke:type_name -> TSD.StrokeArchive
	9,  // 59: TST.TableStylePropertiesArchive.category_level1_bottom_stroke:type_name -> TSD.StrokeArchive
	9,  // 60: TST.TableStylePropertiesArchive.category_level2_bottom_stroke:type_name -> TSD.StrokeArchive
	9,  // 61: TST.TableStylePropertiesArchive.category_level3_bottom_stroke:type_name -> TSD.StrokeArchive
	9,  // 62: TST.TableStylePropertiesArchive.category_level4_bottom_stroke:type_name -> TSD.StrokeArchive
	9,  // 63: TST.TableStylePropertiesArchive.category_level5_bottom_stroke:type_name -> TSD.StrokeArchive
	9,  // 64: TST.TableStylePropertiesArchive.category_level1_interior_stroke:type_name -> TSD.StrokeArchive
	9,  // 65: TST.TableStylePropertiesArchive.category_level2_interior_stroke:type_name -> TSD.StrokeArchive
	9,  // 66: TST.TableStylePropertiesArchive.category_level3_interior_stroke:type_name -> TSD.StrokeArchive
	9,  // 67: TST.TableStylePropertiesArchive.category_level4_interior_stroke:type_name -> TSD.StrokeArchive
	9,  // 68: TST.TableStylePropertiesArchive.category_level5_interior_stroke:type_name -> TSD.StrokeArchive
	9,  // 69: TST.TableStylePropertiesArchive.category_level1_label_separator_stroke:type_name -> TSD.StrokeArchive
	9,  // 70: TST.TableStylePropertiesArchive.category_level2_label_separator_stroke:type_name -> TSD.StrokeArchive
	9,  // 71: TST.TableStylePropertiesArchive.category_level3_label_separator_stroke:type_name -> TSD.StrokeArchive
	9,  // 72: TST.TableStylePropertiesArchive.category_level4_label_separator_stroke:type_name -> TSD.StrokeArchive
	9,  // 73: TST.TableStylePropertiesArchive.category_level5_label_separator_stroke:type_name -> TSD.StrokeArchive
	9,  // 74: TST.TableStylePropertiesArchive.table_body_pivot_group_horizontal_stroke:type_name -> TSD.StrokeArchive
	9,  // 75: TST.TableStylePropertiesArchive.table_body_pivot_group_vertical_stroke:type_name -> TSD.StrokeArchive
	9,  // 76: TST.TableStylePropertiesArchive.table_body_pivot_deemphasis_horizontal_stroke:type_name -> TSD.StrokeArchive
	9,  // 77: TST.TableStylePropertiesArchive.table_body_pivot_emphasis_vertical_stroke:type_name -> TSD.StrokeArchive
	9,  // 78: TST.TableStylePropertiesArchive.header_column_pivot_group_horizontal_stroke:type_name -> TSD.StrokeArchive
	9,  // 79: TST.TableStylePropertiesArchive.header_column_pivot_group_deemphasis_stroke:type_name -> TSD.StrokeArchive
	9,  // 80: TST.TableStylePropertiesArchive.header_column_pivot_separator_stroke:type_name -> TSD.StrokeArchive
	9,  // 81: TST.TableStylePropertiesArchive.header_row_pivot_group_vertical_stroke:type_name -> TSD.StrokeArchive
	9,  // 82: TST.TableStylePropertiesArchive.header_row_pivot_group_deemphasis_stroke:type_name -> TSD.StrokeArchive
	9,  // 83: TST.TableStylePropertiesArchive.header_row_pivot_title_stroke:type_name -> TSD.StrokeArchive
	9,  // 84: TST.TableStylePropertiesArchive.footer_row_pivot_group_vertical_stroke:type_name -> TSD.StrokeArchive
	13, // 85: TST.TableStylePresetArchive.image:type_name -> TSP.Reference
	13, // 86: TST.TableStylePresetArchive.style_network:type_name -> TSP.Reference
	13, // 87: TST.ThemePresetsArchive.table_style_presets:type_name -> TSP.Reference
	13, // 88: TST.ThemePresetsArchive.table_cell_stroke_presets:type_name -> TSP.Reference
	89, // [89:89] is the sub-list for method output_type
	89, // [89:89] is the sub-list for method input_type
	89, // [89:89] is the sub-list for extension type_name
	89, // [89:89] is the sub-list for extension extendee
	0,  // [0:89] is the sub-list for field type_name
}

func init() { file_TSTStylePropertyArchiving_proto_init() }
func file_TSTStylePropertyArchiving_proto_init() {
	if File_TSTStylePropertyArchiving_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_TSTStylePropertyArchiving_proto_rawDesc), len(file_TSTStylePropertyArchiving_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TSTStylePropertyArchiving_proto_goTypes,
		DependencyIndexes: file_TSTStylePropertyArchiving_proto_depIdxs,
		MessageInfos:      file_TSTStylePropertyArchiving_proto_msgTypes,
	}.Build()
	File_TSTStylePropertyArchiving_proto = out.File
	file_TSTStylePropertyArchiving_proto_goTypes = nil
	file_TSTStylePropertyArchiving_proto_depIdxs = nil
}
