// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: TSCKArchives.proto

package TSCK

import (
	_ "github.com/orcastor/iwork-converter/proto/TSK"
	TSP "github.com/orcastor/iwork-converter/proto/TSP"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddIdOperationArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      *TSP.UUID              `protobuf:"bytes,1,opt,name=object_id,json=objectId" json:"object_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddIdOperationArgs) Reset() {
	*x = AddIdOperationArgs{}
	mi := &file_TSCKArchives_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddIdOperationArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddIdOperationArgs) ProtoMessage() {}

func (x *AddIdOperationArgs) ProtoReflect() protoreflect.Message {
	mi := &file_TSCKArchives_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddIdOperationArgs.ProtoReflect.Descriptor instead.
func (*AddIdOperationArgs) Descriptor() ([]byte, []int) {
	return file_TSCKArchives_proto_rawDescGZIP(), []int{0}
}

func (x *AddIdOperationArgs) GetObjectId() *TSP.UUID {
	if x != nil {
		return x.ObjectId
	}
	return nil
}

type IdPlacementOperationArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      *TSP.UUID              `protobuf:"bytes,1,opt,name=object_id,json=objectId" json:"object_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdPlacementOperationArgs) Reset() {
	*x = IdPlacementOperationArgs{}
	mi := &file_TSCKArchives_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdPlacementOperationArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdPlacementOperationArgs) ProtoMessage() {}

func (x *IdPlacementOperationArgs) ProtoReflect() protoreflect.Message {
	mi := &file_TSCKArchives_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdPlacementOperationArgs.ProtoReflect.Descriptor instead.
func (*IdPlacementOperationArgs) Descriptor() ([]byte, []int) {
	return file_TSCKArchives_proto_rawDescGZIP(), []int{1}
}

func (x *IdPlacementOperationArgs) GetObjectId() *TSP.UUID {
	if x != nil {
		return x.ObjectId
	}
	return nil
}

type RemoveIdOperationArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      *TSP.UUID              `protobuf:"bytes,1,opt,name=object_id,json=objectId" json:"object_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveIdOperationArgs) Reset() {
	*x = RemoveIdOperationArgs{}
	mi := &file_TSCKArchives_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveIdOperationArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveIdOperationArgs) ProtoMessage() {}

func (x *RemoveIdOperationArgs) ProtoReflect() protoreflect.Message {
	mi := &file_TSCKArchives_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveIdOperationArgs.ProtoReflect.Descriptor instead.
func (*RemoveIdOperationArgs) Descriptor() ([]byte, []int) {
	return file_TSCKArchives_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveIdOperationArgs) GetObjectId() *TSP.UUID {
	if x != nil {
		return x.ObjectId
	}
	return nil
}

type RearrangeIdOperationArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObjectId      *TSP.UUID              `protobuf:"bytes,1,opt,name=object_id,json=objectId" json:"object_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RearrangeIdOperationArgs) Reset() {
	*x = RearrangeIdOperationArgs{}
	mi := &file_TSCKArchives_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RearrangeIdOperationArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RearrangeIdOperationArgs) ProtoMessage() {}

func (x *RearrangeIdOperationArgs) ProtoReflect() protoreflect.Message {
	mi := &file_TSCKArchives_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RearrangeIdOperationArgs.ProtoReflect.Descriptor instead.
func (*RearrangeIdOperationArgs) Descriptor() ([]byte, []int) {
	return file_TSCKArchives_proto_rawDescGZIP(), []int{3}
}

func (x *RearrangeIdOperationArgs) GetObjectId() *TSP.UUID {
	if x != nil {
		return x.ObjectId
	}
	return nil
}

type CommandActivityBehaviorArchive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Super         *TSP.Reference         `protobuf:"bytes,1,opt,name=super" json:"super,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandActivityBehaviorArchive) Reset() {
	*x = CommandActivityBehaviorArchive{}
	mi := &file_TSCKArchives_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandActivityBehaviorArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandActivityBehaviorArchive) ProtoMessage() {}

func (x *CommandActivityBehaviorArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSCKArchives_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandActivityBehaviorArchive.ProtoReflect.Descriptor instead.
func (*CommandActivityBehaviorArchive) Descriptor() ([]byte, []int) {
	return file_TSCKArchives_proto_rawDescGZIP(), []int{4}
}

func (x *CommandActivityBehaviorArchive) GetSuper() *TSP.Reference {
	if x != nil {
		return x.Super
	}
	return nil
}

var File_TSCKArchives_proto protoreflect.FileDescriptor

const file_TSCKArchives_proto_rawDesc = "" +
	"\n" +
	"\x12TSCKArchives.proto\x12\x04TSCK\x1a\x11TSPMessages.proto\x1a\x11TSKArchives.proto\"<\n" +
	"\x12AddIdOperationArgs\x12&\n" +
	"\tobject_id\x18\x01 \x01(\v2\t.TSP.UUIDR\bobjectId\"B\n" +
	"\x18IdPlacementOperationArgs\x12&\n" +
	"\tobject_id\x18\x01 \x01(\v2\t.TSP.UUIDR\bobjectId\"?\n" +
	"\x15RemoveIdOperationArgs\x12&\n" +
	"\tobject_id\x18\x01 \x01(\v2\t.TSP.UUIDR\bobjectId\"B\n" +
	"\x18RearrangeIdOperationArgs\x12&\n" +
	"\tobject_id\x18\x01 \x01(\v2\t.TSP.UUIDR\bobjectId\"F\n" +
	"\x1eCommandActivityBehaviorArchive\x12$\n" +
	"\x05super\x18\x01 \x01(\v2\x0e.TSP.ReferenceR\x05superB0Z.github.com/orcastor/iwork-converter/proto/TSCK"

var (
	file_TSCKArchives_proto_rawDescOnce sync.Once
	file_TSCKArchives_proto_rawDescData []byte
)

func file_TSCKArchives_proto_rawDescGZIP() []byte {
	file_TSCKArchives_proto_rawDescOnce.Do(func() {
		file_TSCKArchives_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_TSCKArchives_proto_rawDesc), len(file_TSCKArchives_proto_rawDesc)))
	})
	return file_TSCKArchives_proto_rawDescData
}

var file_TSCKArchives_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_TSCKArchives_proto_goTypes = []any{
	(*AddIdOperationArgs)(nil),             // 0: TSCK.AddIdOperationArgs
	(*IdPlacementOperationArgs)(nil),       // 1: TSCK.IdPlacementOperationArgs
	(*RemoveIdOperationArgs)(nil),          // 2: TSCK.RemoveIdOperationArgs
	(*RearrangeIdOperationArgs)(nil),       // 3: TSCK.RearrangeIdOperationArgs
	(*CommandActivityBehaviorArchive)(nil), // 4: TSCK.CommandActivityBehaviorArchive
	(*TSP.UUID)(nil),                       // 5: TSP.UUID
	(*TSP.Reference)(nil),                  // 6: TSP.Reference
}
var file_TSCKArchives_proto_depIdxs = []int32{
	5, // 0: TSCK.AddIdOperationArgs.object_id:type_name -> TSP.UUID
	5, // 1: TSCK.IdPlacementOperationArgs.object_id:type_name -> TSP.UUID
	5, // 2: TSCK.RemoveIdOperationArgs.object_id:type_name -> TSP.UUID
	5, // 3: TSCK.RearrangeIdOperationArgs.object_id:type_name -> TSP.UUID
	6, // 4: TSCK.CommandActivityBehaviorArchive.super:type_name -> TSP.Reference
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_TSCKArchives_proto_init() }
func file_TSCKArchives_proto_init() {
	if File_TSCKArchives_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_TSCKArchives_proto_rawDesc), len(file_TSCKArchives_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TSCKArchives_proto_goTypes,
		DependencyIndexes: file_TSCKArchives_proto_depIdxs,
		MessageInfos:      file_TSCKArchives_proto_msgTypes,
	}.Build()
	File_TSCKArchives_proto = out.File
	file_TSCKArchives_proto_goTypes = nil
	file_TSCKArchives_proto_depIdxs = nil
}
