// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: TSPDatabaseMessages.proto

package TSP

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DatabaseImageDataArchive_ImageType int32

const (
	DatabaseImageDataArchive_unknown DatabaseImageDataArchive_ImageType = 0
	DatabaseImageDataArchive_bitmap  DatabaseImageDataArchive_ImageType = 1
	DatabaseImageDataArchive_pdf     DatabaseImageDataArchive_ImageType = 2
)

// Enum value maps for DatabaseImageDataArchive_ImageType.
var (
	DatabaseImageDataArchive_ImageType_name = map[int32]string{
		0: "unknown",
		1: "bitmap",
		2: "pdf",
	}
	DatabaseImageDataArchive_ImageType_value = map[string]int32{
		"unknown": 0,
		"bitmap":  1,
		"pdf":     2,
	}
)

func (x DatabaseImageDataArchive_ImageType) Enum() *DatabaseImageDataArchive_ImageType {
	p := new(DatabaseImageDataArchive_ImageType)
	*p = x
	return p
}

func (x DatabaseImageDataArchive_ImageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DatabaseImageDataArchive_ImageType) Descriptor() protoreflect.EnumDescriptor {
	return file_TSPDatabaseMessages_proto_enumTypes[0].Descriptor()
}

func (DatabaseImageDataArchive_ImageType) Type() protoreflect.EnumType {
	return &file_TSPDatabaseMessages_proto_enumTypes[0]
}

func (x DatabaseImageDataArchive_ImageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *DatabaseImageDataArchive_ImageType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = DatabaseImageDataArchive_ImageType(num)
	return nil
}

// Deprecated: Use DatabaseImageDataArchive_ImageType.Descriptor instead.
func (DatabaseImageDataArchive_ImageType) EnumDescriptor() ([]byte, []int) {
	return file_TSPDatabaseMessages_proto_rawDescGZIP(), []int{2, 0}
}

type DatabaseData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *DataReference         `protobuf:"bytes,1,req,name=data" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseData) Reset() {
	*x = DatabaseData{}
	mi := &file_TSPDatabaseMessages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseData) ProtoMessage() {}

func (x *DatabaseData) ProtoReflect() protoreflect.Message {
	mi := &file_TSPDatabaseMessages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseData.ProtoReflect.Descriptor instead.
func (*DatabaseData) Descriptor() ([]byte, []int) {
	return file_TSPDatabaseMessages_proto_rawDescGZIP(), []int{0}
}

func (x *DatabaseData) GetData() *DataReference {
	if x != nil {
		return x.Data
	}
	return nil
}

type DatabaseDataArchive struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Data            *Reference             `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	AppRelativePath *string                `protobuf:"bytes,2,opt,name=app_relative_path,json=appRelativePath" json:"app_relative_path,omitempty"`
	DisplayName     *string                `protobuf:"bytes,3,req,name=display_name,json=displayName" json:"display_name,omitempty"`
	Length          *uint64                `protobuf:"varint,4,opt,name=length" json:"length,omitempty"`
	Hash            *uint32                `protobuf:"varint,5,opt,name=hash" json:"hash,omitempty"`
	Sharable        *bool                  `protobuf:"varint,6,req,name=sharable,def=1" json:"sharable,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

// Default values for DatabaseDataArchive fields.
const (
	Default_DatabaseDataArchive_Sharable = bool(true)
)

func (x *DatabaseDataArchive) Reset() {
	*x = DatabaseDataArchive{}
	mi := &file_TSPDatabaseMessages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseDataArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseDataArchive) ProtoMessage() {}

func (x *DatabaseDataArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSPDatabaseMessages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseDataArchive.ProtoReflect.Descriptor instead.
func (*DatabaseDataArchive) Descriptor() ([]byte, []int) {
	return file_TSPDatabaseMessages_proto_rawDescGZIP(), []int{1}
}

func (x *DatabaseDataArchive) GetData() *Reference {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DatabaseDataArchive) GetAppRelativePath() string {
	if x != nil && x.AppRelativePath != nil {
		return *x.AppRelativePath
	}
	return ""
}

func (x *DatabaseDataArchive) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *DatabaseDataArchive) GetLength() uint64 {
	if x != nil && x.Length != nil {
		return *x.Length
	}
	return 0
}

func (x *DatabaseDataArchive) GetHash() uint32 {
	if x != nil && x.Hash != nil {
		return *x.Hash
	}
	return 0
}

func (x *DatabaseDataArchive) GetSharable() bool {
	if x != nil && x.Sharable != nil {
		return *x.Sharable
	}
	return Default_DatabaseDataArchive_Sharable
}

type DatabaseImageDataArchive struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Super         *DatabaseDataArchive                `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Type          *DatabaseImageDataArchive_ImageType `protobuf:"varint,2,req,name=type,enum=TSP.DatabaseImageDataArchive_ImageType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseImageDataArchive) Reset() {
	*x = DatabaseImageDataArchive{}
	mi := &file_TSPDatabaseMessages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseImageDataArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseImageDataArchive) ProtoMessage() {}

func (x *DatabaseImageDataArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSPDatabaseMessages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseImageDataArchive.ProtoReflect.Descriptor instead.
func (*DatabaseImageDataArchive) Descriptor() ([]byte, []int) {
	return file_TSPDatabaseMessages_proto_rawDescGZIP(), []int{2}
}

func (x *DatabaseImageDataArchive) GetSuper() *DatabaseDataArchive {
	if x != nil {
		return x.Super
	}
	return nil
}

func (x *DatabaseImageDataArchive) GetType() DatabaseImageDataArchive_ImageType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return DatabaseImageDataArchive_unknown
}

var File_TSPDatabaseMessages_proto protoreflect.FileDescriptor

const file_TSPDatabaseMessages_proto_rawDesc = "" +
	"\n" +
	"\x19TSPDatabaseMessages.proto\x12\x03TSP\x1a\x11TSPMessages.proto\"6\n" +
	"\fDatabaseData\x12&\n" +
	"\x04data\x18\x01 \x02(\v2\x12.TSP.DataReferenceR\x04data\"\xd6\x01\n" +
	"\x13DatabaseDataArchive\x12\"\n" +
	"\x04data\x18\x01 \x01(\v2\x0e.TSP.ReferenceR\x04data\x12*\n" +
	"\x11app_relative_path\x18\x02 \x01(\tR\x0fappRelativePath\x12!\n" +
	"\fdisplay_name\x18\x03 \x02(\tR\vdisplayName\x12\x16\n" +
	"\x06length\x18\x04 \x01(\x04R\x06length\x12\x12\n" +
	"\x04hash\x18\x05 \x01(\rR\x04hash\x12 \n" +
	"\bsharable\x18\x06 \x02(\b:\x04trueR\bsharable\"\xb6\x01\n" +
	"\x18DatabaseImageDataArchive\x12.\n" +
	"\x05super\x18\x01 \x02(\v2\x18.TSP.DatabaseDataArchiveR\x05super\x12;\n" +
	"\x04type\x18\x02 \x02(\x0e2'.TSP.DatabaseImageDataArchive.ImageTypeR\x04type\"-\n" +
	"\tImageType\x12\v\n" +
	"\aunknown\x10\x00\x12\n" +
	"\n" +
	"\x06bitmap\x10\x01\x12\a\n" +
	"\x03pdf\x10\x02B/Z-github.com/orcastor/iwork-converter/proto/TSP"

var (
	file_TSPDatabaseMessages_proto_rawDescOnce sync.Once
	file_TSPDatabaseMessages_proto_rawDescData []byte
)

func file_TSPDatabaseMessages_proto_rawDescGZIP() []byte {
	file_TSPDatabaseMessages_proto_rawDescOnce.Do(func() {
		file_TSPDatabaseMessages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_TSPDatabaseMessages_proto_rawDesc), len(file_TSPDatabaseMessages_proto_rawDesc)))
	})
	return file_TSPDatabaseMessages_proto_rawDescData
}

var file_TSPDatabaseMessages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_TSPDatabaseMessages_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_TSPDatabaseMessages_proto_goTypes = []any{
	(DatabaseImageDataArchive_ImageType)(0), // 0: TSP.DatabaseImageDataArchive.ImageType
	(*DatabaseData)(nil),                    // 1: TSP.DatabaseData
	(*DatabaseDataArchive)(nil),             // 2: TSP.DatabaseDataArchive
	(*DatabaseImageDataArchive)(nil),        // 3: TSP.DatabaseImageDataArchive
	(*DataReference)(nil),                   // 4: TSP.DataReference
	(*Reference)(nil),                       // 5: TSP.Reference
}
var file_TSPDatabaseMessages_proto_depIdxs = []int32{
	4, // 0: TSP.DatabaseData.data:type_name -> TSP.DataReference
	5, // 1: TSP.DatabaseDataArchive.data:type_name -> TSP.Reference
	2, // 2: TSP.DatabaseImageDataArchive.super:type_name -> TSP.DatabaseDataArchive
	0, // 3: TSP.DatabaseImageDataArchive.type:type_name -> TSP.DatabaseImageDataArchive.ImageType
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_TSPDatabaseMessages_proto_init() }
func file_TSPDatabaseMessages_proto_init() {
	if File_TSPDatabaseMessages_proto != nil {
		return
	}
	file_TSPMessages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_TSPDatabaseMessages_proto_rawDesc), len(file_TSPDatabaseMessages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TSPDatabaseMessages_proto_goTypes,
		DependencyIndexes: file_TSPDatabaseMessages_proto_depIdxs,
		EnumInfos:         file_TSPDatabaseMessages_proto_enumTypes,
		MessageInfos:      file_TSPDatabaseMessages_proto_msgTypes,
	}.Build()
	File_TSPDatabaseMessages_proto = out.File
	file_TSPDatabaseMessages_proto_goTypes = nil
	file_TSPDatabaseMessages_proto_depIdxs = nil
}
