syntax = "proto2";

package TN;
option go_package = "github.com/orcastor/iwork-converter/proto/TN";
import "TSACommandArchives.sos.proto";
import "TSKArchives.proto";
import "TSPMessages.proto";

message InducedVerifyDocumentWithServerCommandArchive {
  required .TSK.CommandArchive super = 1;
  repeated .TSP.UUID sheet_id_list = 2;
  optional bool sheet_id_list_undefined = 3;
}

message InducedVerifyDrawableZOrdersWithServerCommandArchive {
  required .TSA.InducedVerifyDrawableZOrdersWithServerCommandArchive super = 1;
}

