// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: TSACommandArchives.sos.proto

package TSA

import (
	TSK "github.com/orcastor/iwork-converter/proto/TSK"
	_ "github.com/orcastor/iwork-converter/proto/TSP"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InducedVerifyDrawableZOrdersWithServerCommandArchive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Super         *TSK.CommandArchive    `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InducedVerifyDrawableZOrdersWithServerCommandArchive) Reset() {
	*x = InducedVerifyDrawableZOrdersWithServerCommandArchive{}
	mi := &file_TSACommandArchives_sos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InducedVerifyDrawableZOrdersWithServerCommandArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InducedVerifyDrawableZOrdersWithServerCommandArchive) ProtoMessage() {}

func (x *InducedVerifyDrawableZOrdersWithServerCommandArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSACommandArchives_sos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InducedVerifyDrawableZOrdersWithServerCommandArchive.ProtoReflect.Descriptor instead.
func (*InducedVerifyDrawableZOrdersWithServerCommandArchive) Descriptor() ([]byte, []int) {
	return file_TSACommandArchives_sos_proto_rawDescGZIP(), []int{0}
}

func (x *InducedVerifyDrawableZOrdersWithServerCommandArchive) GetSuper() *TSK.CommandArchive {
	if x != nil {
		return x.Super
	}
	return nil
}

type CommandReapplyMasterArchive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Super         *TSK.CommandArchive    `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandReapplyMasterArchive) Reset() {
	*x = CommandReapplyMasterArchive{}
	mi := &file_TSACommandArchives_sos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandReapplyMasterArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandReapplyMasterArchive) ProtoMessage() {}

func (x *CommandReapplyMasterArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TSACommandArchives_sos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandReapplyMasterArchive.ProtoReflect.Descriptor instead.
func (*CommandReapplyMasterArchive) Descriptor() ([]byte, []int) {
	return file_TSACommandArchives_sos_proto_rawDescGZIP(), []int{1}
}

func (x *CommandReapplyMasterArchive) GetSuper() *TSK.CommandArchive {
	if x != nil {
		return x.Super
	}
	return nil
}

var File_TSACommandArchives_sos_proto protoreflect.FileDescriptor

const file_TSACommandArchives_sos_proto_rawDesc = "" +
	"\n" +
	"\x1cTSACommandArchives.sos.proto\x12\x03TSA\x1a\x11TSPMessages.proto\x1a\x11TSKArchives.proto\"a\n" +
	"4InducedVerifyDrawableZOrdersWithServerCommandArchive\x12)\n" +
	"\x05super\x18\x01 \x02(\v2\x13.TSK.CommandArchiveR\x05super\"H\n" +
	"\x1bCommandReapplyMasterArchive\x12)\n" +
	"\x05super\x18\x01 \x02(\v2\x13.TSK.CommandArchiveR\x05superB/Z-github.com/orcastor/iwork-converter/proto/TSA"

var (
	file_TSACommandArchives_sos_proto_rawDescOnce sync.Once
	file_TSACommandArchives_sos_proto_rawDescData []byte
)

func file_TSACommandArchives_sos_proto_rawDescGZIP() []byte {
	file_TSACommandArchives_sos_proto_rawDescOnce.Do(func() {
		file_TSACommandArchives_sos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_TSACommandArchives_sos_proto_rawDesc), len(file_TSACommandArchives_sos_proto_rawDesc)))
	})
	return file_TSACommandArchives_sos_proto_rawDescData
}

var file_TSACommandArchives_sos_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_TSACommandArchives_sos_proto_goTypes = []any{
	(*InducedVerifyDrawableZOrdersWithServerCommandArchive)(nil), // 0: TSA.InducedVerifyDrawableZOrdersWithServerCommandArchive
	(*CommandReapplyMasterArchive)(nil),                          // 1: TSA.CommandReapplyMasterArchive
	(*TSK.CommandArchive)(nil),                                   // 2: TSK.CommandArchive
}
var file_TSACommandArchives_sos_proto_depIdxs = []int32{
	2, // 0: TSA.InducedVerifyDrawableZOrdersWithServerCommandArchive.super:type_name -> TSK.CommandArchive
	2, // 1: TSA.CommandReapplyMasterArchive.super:type_name -> TSK.CommandArchive
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_TSACommandArchives_sos_proto_init() }
func file_TSACommandArchives_sos_proto_init() {
	if File_TSACommandArchives_sos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_TSACommandArchives_sos_proto_rawDesc), len(file_TSACommandArchives_sos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TSACommandArchives_sos_proto_goTypes,
		DependencyIndexes: file_TSACommandArchives_sos_proto_depIdxs,
		MessageInfos:      file_TSACommandArchives_sos_proto_msgTypes,
	}.Build()
	File_TSACommandArchives_sos_proto = out.File
	file_TSACommandArchives_sos_proto_goTypes = nil
	file_TSACommandArchives_sos_proto_depIdxs = nil
}
