// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: KNCommandArchives.sos.proto

package KN

import (
	TSA "github.com/orcastor/iwork-converter/proto/TSA"
	TSK "github.com/orcastor/iwork-converter/proto/TSK"
	TSP "github.com/orcastor/iwork-converter/proto/TSP"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InducedVerifyDocumentWithServerCommandArchive struct {
	state                            protoimpl.MessageState `protogen:"open.v1"`
	Super                            *TSK.CommandArchive    `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	SlideNodeIdList                  []*TSP.UUID            `protobuf:"bytes,2,rep,name=slide_node_id_list,json=slideNodeIdList" json:"slide_node_id_list,omitempty"`
	SlideNodeIdListUndefined         *bool                  `protobuf:"varint,3,opt,name=slide_node_id_list_undefined,json=slideNodeIdListUndefined" json:"slide_node_id_list_undefined,omitempty"`
	TemplateSlideNodeIdList          []*TSP.UUID            `protobuf:"bytes,4,rep,name=template_slide_node_id_list,json=templateSlideNodeIdList" json:"template_slide_node_id_list,omitempty"`
	TemplateSlideNodeIdListUndefined *bool                  `protobuf:"varint,5,opt,name=template_slide_node_id_list_undefined,json=templateSlideNodeIdListUndefined" json:"template_slide_node_id_list_undefined,omitempty"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *InducedVerifyDocumentWithServerCommandArchive) Reset() {
	*x = InducedVerifyDocumentWithServerCommandArchive{}
	mi := &file_KNCommandArchives_sos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InducedVerifyDocumentWithServerCommandArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InducedVerifyDocumentWithServerCommandArchive) ProtoMessage() {}

func (x *InducedVerifyDocumentWithServerCommandArchive) ProtoReflect() protoreflect.Message {
	mi := &file_KNCommandArchives_sos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InducedVerifyDocumentWithServerCommandArchive.ProtoReflect.Descriptor instead.
func (*InducedVerifyDocumentWithServerCommandArchive) Descriptor() ([]byte, []int) {
	return file_KNCommandArchives_sos_proto_rawDescGZIP(), []int{0}
}

func (x *InducedVerifyDocumentWithServerCommandArchive) GetSuper() *TSK.CommandArchive {
	if x != nil {
		return x.Super
	}
	return nil
}

func (x *InducedVerifyDocumentWithServerCommandArchive) GetSlideNodeIdList() []*TSP.UUID {
	if x != nil {
		return x.SlideNodeIdList
	}
	return nil
}

func (x *InducedVerifyDocumentWithServerCommandArchive) GetSlideNodeIdListUndefined() bool {
	if x != nil && x.SlideNodeIdListUndefined != nil {
		return *x.SlideNodeIdListUndefined
	}
	return false
}

func (x *InducedVerifyDocumentWithServerCommandArchive) GetTemplateSlideNodeIdList() []*TSP.UUID {
	if x != nil {
		return x.TemplateSlideNodeIdList
	}
	return nil
}

func (x *InducedVerifyDocumentWithServerCommandArchive) GetTemplateSlideNodeIdListUndefined() bool {
	if x != nil && x.TemplateSlideNodeIdListUndefined != nil {
		return *x.TemplateSlideNodeIdListUndefined
	}
	return false
}

type InducedVerifyDrawableZOrdersWithServerCommandArchive struct {
	state         protoimpl.MessageState                                    `protogen:"open.v1"`
	Super         *TSA.InducedVerifyDrawableZOrdersWithServerCommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InducedVerifyDrawableZOrdersWithServerCommandArchive) Reset() {
	*x = InducedVerifyDrawableZOrdersWithServerCommandArchive{}
	mi := &file_KNCommandArchives_sos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InducedVerifyDrawableZOrdersWithServerCommandArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InducedVerifyDrawableZOrdersWithServerCommandArchive) ProtoMessage() {}

func (x *InducedVerifyDrawableZOrdersWithServerCommandArchive) ProtoReflect() protoreflect.Message {
	mi := &file_KNCommandArchives_sos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InducedVerifyDrawableZOrdersWithServerCommandArchive.ProtoReflect.Descriptor instead.
func (*InducedVerifyDrawableZOrdersWithServerCommandArchive) Descriptor() ([]byte, []int) {
	return file_KNCommandArchives_sos_proto_rawDescGZIP(), []int{1}
}

func (x *InducedVerifyDrawableZOrdersWithServerCommandArchive) GetSuper() *TSA.InducedVerifyDrawableZOrdersWithServerCommandArchive {
	if x != nil {
		return x.Super
	}
	return nil
}

type CommandSlideReapplyTemplateSlideArchive struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Super         *TSA.CommandReapplyMasterArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandSlideReapplyTemplateSlideArchive) Reset() {
	*x = CommandSlideReapplyTemplateSlideArchive{}
	mi := &file_KNCommandArchives_sos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandSlideReapplyTemplateSlideArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandSlideReapplyTemplateSlideArchive) ProtoMessage() {}

func (x *CommandSlideReapplyTemplateSlideArchive) ProtoReflect() protoreflect.Message {
	mi := &file_KNCommandArchives_sos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandSlideReapplyTemplateSlideArchive.ProtoReflect.Descriptor instead.
func (*CommandSlideReapplyTemplateSlideArchive) Descriptor() ([]byte, []int) {
	return file_KNCommandArchives_sos_proto_rawDescGZIP(), []int{2}
}

func (x *CommandSlideReapplyTemplateSlideArchive) GetSuper() *TSA.CommandReapplyMasterArchive {
	if x != nil {
		return x.Super
	}
	return nil
}

var File_KNCommandArchives_sos_proto protoreflect.FileDescriptor

const file_KNCommandArchives_sos_proto_rawDesc = "" +
	"\n" +
	"\x1bKNCommandArchives.sos.proto\x12\x02KN\x1a\x1cTSACommandArchives.sos.proto\x1a\x11TSKArchives.proto\x1a\x11TSPMessages.proto\"\xec\x02\n" +
	"-InducedVerifyDocumentWithServerCommandArchive\x12)\n" +
	"\x05super\x18\x01 \x02(\v2\x13.TSK.CommandArchiveR\x05super\x126\n" +
	"\x12slide_node_id_list\x18\x02 \x03(\v2\t.TSP.UUIDR\x0fslideNodeIdList\x12>\n" +
	"\x1cslide_node_id_list_undefined\x18\x03 \x01(\bR\x18slideNodeIdListUndefined\x12G\n" +
	"\x1btemplate_slide_node_id_list\x18\x04 \x03(\v2\t.TSP.UUIDR\x17templateSlideNodeIdList\x12O\n" +
	"%template_slide_node_id_list_undefined\x18\x05 \x01(\bR templateSlideNodeIdListUndefined\"\x87\x01\n" +
	"4InducedVerifyDrawableZOrdersWithServerCommandArchive\x12O\n" +
	"\x05super\x18\x01 \x02(\v29.TSA.InducedVerifyDrawableZOrdersWithServerCommandArchiveR\x05super\"a\n" +
	"'CommandSlideReapplyTemplateSlideArchive\x126\n" +
	"\x05super\x18\x01 \x02(\v2 .TSA.CommandReapplyMasterArchiveR\x05superB.Z,github.com/orcastor/iwork-converter/proto/KN"

var (
	file_KNCommandArchives_sos_proto_rawDescOnce sync.Once
	file_KNCommandArchives_sos_proto_rawDescData []byte
)

func file_KNCommandArchives_sos_proto_rawDescGZIP() []byte {
	file_KNCommandArchives_sos_proto_rawDescOnce.Do(func() {
		file_KNCommandArchives_sos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_KNCommandArchives_sos_proto_rawDesc), len(file_KNCommandArchives_sos_proto_rawDesc)))
	})
	return file_KNCommandArchives_sos_proto_rawDescData
}

var file_KNCommandArchives_sos_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_KNCommandArchives_sos_proto_goTypes = []any{
	(*InducedVerifyDocumentWithServerCommandArchive)(nil),            // 0: KN.InducedVerifyDocumentWithServerCommandArchive
	(*InducedVerifyDrawableZOrdersWithServerCommandArchive)(nil),     // 1: KN.InducedVerifyDrawableZOrdersWithServerCommandArchive
	(*CommandSlideReapplyTemplateSlideArchive)(nil),                  // 2: KN.CommandSlideReapplyTemplateSlideArchive
	(*TSK.CommandArchive)(nil),                                       // 3: TSK.CommandArchive
	(*TSP.UUID)(nil),                                                 // 4: TSP.UUID
	(*TSA.InducedVerifyDrawableZOrdersWithServerCommandArchive)(nil), // 5: TSA.InducedVerifyDrawableZOrdersWithServerCommandArchive
	(*TSA.CommandReapplyMasterArchive)(nil),                          // 6: TSA.CommandReapplyMasterArchive
}
var file_KNCommandArchives_sos_proto_depIdxs = []int32{
	3, // 0: KN.InducedVerifyDocumentWithServerCommandArchive.super:type_name -> TSK.CommandArchive
	4, // 1: KN.InducedVerifyDocumentWithServerCommandArchive.slide_node_id_list:type_name -> TSP.UUID
	4, // 2: KN.InducedVerifyDocumentWithServerCommandArchive.template_slide_node_id_list:type_name -> TSP.UUID
	5, // 3: KN.InducedVerifyDrawableZOrdersWithServerCommandArchive.super:type_name -> TSA.InducedVerifyDrawableZOrdersWithServerCommandArchive
	6, // 4: KN.CommandSlideReapplyTemplateSlideArchive.super:type_name -> TSA.CommandReapplyMasterArchive
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_KNCommandArchives_sos_proto_init() }
func file_KNCommandArchives_sos_proto_init() {
	if File_KNCommandArchives_sos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_KNCommandArchives_sos_proto_rawDesc), len(file_KNCommandArchives_sos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_KNCommandArchives_sos_proto_goTypes,
		DependencyIndexes: file_KNCommandArchives_sos_proto_depIdxs,
		MessageInfos:      file_KNCommandArchives_sos_proto_msgTypes,
	}.Build()
	File_KNCommandArchives_sos_proto = out.File
	file_KNCommandArchives_sos_proto_goTypes = nil
	file_KNCommandArchives_sos_proto_depIdxs = nil
}
