// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: TNArchives.proto

package TN

import (
	TSA "github.com/orcastor/iwork-converter/proto/TSA"
	TSCE "github.com/orcastor/iwork-converter/proto/TSCE"
	TSCH "github.com/orcastor/iwork-converter/proto/TSCH"
	TSCK "github.com/orcastor/iwork-converter/proto/TSCK"
	TSD "github.com/orcastor/iwork-converter/proto/TSD"
	TSK "github.com/orcastor/iwork-converter/proto/TSK"
	TSP "github.com/orcastor/iwork-converter/proto/TSP"
	TSS "github.com/orcastor/iwork-converter/proto/TSS"
	TST "github.com/orcastor/iwork-converter/proto/TST"
	TSWP "github.com/orcastor/iwork-converter/proto/TSWP"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PageOrder int32

const (
	PageOrder_PageOrderTopToBottom PageOrder = 0
	PageOrder_PageOrderLeftToRight PageOrder = 1
)

// Enum value maps for PageOrder.
var (
	PageOrder_name = map[int32]string{
		0: "PageOrderTopToBottom",
		1: "PageOrderLeftToRight",
	}
	PageOrder_value = map[string]int32{
		"PageOrderTopToBottom": 0,
		"PageOrderLeftToRight": 1,
	}
)

func (x PageOrder) Enum() *PageOrder {
	p := new(PageOrder)
	*p = x
	return p
}

func (x PageOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PageOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_TNArchives_proto_enumTypes[0].Descriptor()
}

func (PageOrder) Type() protoreflect.EnumType {
	return &file_TNArchives_proto_enumTypes[0]
}

func (x PageOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *PageOrder) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = PageOrder(num)
	return nil
}

// Deprecated: Use PageOrder.Descriptor instead.
func (PageOrder) EnumDescriptor() ([]byte, []int) {
	return file_TNArchives_proto_rawDescGZIP(), []int{0}
}

type PageLayoutDirection int32

const (
	PageLayoutDirection_PageLayoutDirectionLeftToRight PageLayoutDirection = 0
	PageLayoutDirection_PageLayoutDirectionRightToLeft PageLayoutDirection = 1
)

// Enum value maps for PageLayoutDirection.
var (
	PageLayoutDirection_name = map[int32]string{
		0: "PageLayoutDirectionLeftToRight",
		1: "PageLayoutDirectionRightToLeft",
	}
	PageLayoutDirection_value = map[string]int32{
		"PageLayoutDirectionLeftToRight": 0,
		"PageLayoutDirectionRightToLeft": 1,
	}
)

func (x PageLayoutDirection) Enum() *PageLayoutDirection {
	p := new(PageLayoutDirection)
	*p = x
	return p
}

func (x PageLayoutDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PageLayoutDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_TNArchives_proto_enumTypes[1].Descriptor()
}

func (PageLayoutDirection) Type() protoreflect.EnumType {
	return &file_TNArchives_proto_enumTypes[1]
}

func (x PageLayoutDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *PageLayoutDirection) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = PageLayoutDirection(num)
	return nil
}

// Deprecated: Use PageLayoutDirection.Descriptor instead.
func (PageLayoutDirection) EnumDescriptor() ([]byte, []int) {
	return file_TNArchives_proto_rawDescGZIP(), []int{1}
}

type UIStateArchive_InspectorPaneViewMode int32

const (
	UIStateArchive_kInspectorPaneViewModeFormat UIStateArchive_InspectorPaneViewMode = 0
	UIStateArchive_kInspectorPaneViewModeFilter UIStateArchive_InspectorPaneViewMode = 1
)

// Enum value maps for UIStateArchive_InspectorPaneViewMode.
var (
	UIStateArchive_InspectorPaneViewMode_name = map[int32]string{
		0: "kInspectorPaneViewModeFormat",
		1: "kInspectorPaneViewModeFilter",
	}
	UIStateArchive_InspectorPaneViewMode_value = map[string]int32{
		"kInspectorPaneViewModeFormat": 0,
		"kInspectorPaneViewModeFilter": 1,
	}
)

func (x UIStateArchive_InspectorPaneViewMode) Enum() *UIStateArchive_InspectorPaneViewMode {
	p := new(UIStateArchive_InspectorPaneViewMode)
	*p = x
	return p
}

func (x UIStateArchive_InspectorPaneViewMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UIStateArchive_InspectorPaneViewMode) Descriptor() protoreflect.EnumDescriptor {
	return file_TNArchives_proto_enumTypes[2].Descriptor()
}

func (UIStateArchive_InspectorPaneViewMode) Type() protoreflect.EnumType {
	return &file_TNArchives_proto_enumTypes[2]
}

func (x UIStateArchive_InspectorPaneViewMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *UIStateArchive_InspectorPaneViewMode) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = UIStateArchive_InspectorPaneViewMode(num)
	return nil
}

// Deprecated: Use UIStateArchive_InspectorPaneViewMode.Descriptor instead.
func (UIStateArchive_InspectorPaneViewMode) EnumDescriptor() ([]byte, []int) {
	return file_TNArchives_proto_rawDescGZIP(), []int{3, 0}
}

type SheetUIStateArchive struct {
	state                       protoimpl.MessageState    `protogen:"open.v1"`
	ViewScale                   *float32                  `protobuf:"fixed32,1,req,name=view_scale,json=viewScale" json:"view_scale,omitempty"`
	ScrollPosition              *TSP.Point                `protobuf:"bytes,2,req,name=scroll_position,json=scrollPosition" json:"scroll_position,omitempty"`
	PreviousViewScale           *float32                  `protobuf:"fixed32,3,opt,name=previous_view_scale,json=previousViewScale" json:"previous_view_scale,omitempty"`
	ScrollPositionIsUnscaled    *bool                     `protobuf:"varint,4,opt,name=scroll_position_is_unscaled,json=scrollPositionIsUnscaled" json:"scroll_position_is_unscaled,omitempty"`
	PreviousScrollPosition      *TSP.Point                `protobuf:"bytes,5,opt,name=previous_scroll_position,json=previousScrollPosition" json:"previous_scroll_position,omitempty"`
	ScrollPositionValid         *bool                     `protobuf:"varint,6,opt,name=scroll_position_valid,json=scrollPositionValid" json:"scroll_position_valid,omitempty"`
	PreviousScrollPositionValid *bool                     `protobuf:"varint,7,opt,name=previous_scroll_position_valid,json=previousScrollPositionValid" json:"previous_scroll_position_valid,omitempty"`
	VisibleSize                 *TSP.Size                 `protobuf:"bytes,8,opt,name=visible_size,json=visibleSize" json:"visible_size,omitempty"`
	PreviousVisibleSize         *TSP.Size                 `protobuf:"bytes,9,opt,name=previous_visible_size,json=previousVisibleSize" json:"previous_visible_size,omitempty"`
	DeviceIdiom                 *uint32                   `protobuf:"varint,10,opt,name=device_idiom,json=deviceIdiom" json:"device_idiom,omitempty"`
	SelectionPath               *TSK.SelectionPathArchive `protobuf:"bytes,11,opt,name=selection_path,json=selectionPath" json:"selection_path,omitempty"`
	SelectionPathTransformer    *TSP.Reference            `protobuf:"bytes,12,opt,name=selection_path_transformer,json=selectionPathTransformer" json:"selection_path_transformer,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *SheetUIStateArchive) Reset() {
	*x = SheetUIStateArchive{}
	mi := &file_TNArchives_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SheetUIStateArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SheetUIStateArchive) ProtoMessage() {}

func (x *SheetUIStateArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TNArchives_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SheetUIStateArchive.ProtoReflect.Descriptor instead.
func (*SheetUIStateArchive) Descriptor() ([]byte, []int) {
	return file_TNArchives_proto_rawDescGZIP(), []int{0}
}

func (x *SheetUIStateArchive) GetViewScale() float32 {
	if x != nil && x.ViewScale != nil {
		return *x.ViewScale
	}
	return 0
}

func (x *SheetUIStateArchive) GetScrollPosition() *TSP.Point {
	if x != nil {
		return x.ScrollPosition
	}
	return nil
}

func (x *SheetUIStateArchive) GetPreviousViewScale() float32 {
	if x != nil && x.PreviousViewScale != nil {
		return *x.PreviousViewScale
	}
	return 0
}

func (x *SheetUIStateArchive) GetScrollPositionIsUnscaled() bool {
	if x != nil && x.ScrollPositionIsUnscaled != nil {
		return *x.ScrollPositionIsUnscaled
	}
	return false
}

func (x *SheetUIStateArchive) GetPreviousScrollPosition() *TSP.Point {
	if x != nil {
		return x.PreviousScrollPosition
	}
	return nil
}

func (x *SheetUIStateArchive) GetScrollPositionValid() bool {
	if x != nil && x.ScrollPositionValid != nil {
		return *x.ScrollPositionValid
	}
	return false
}

func (x *SheetUIStateArchive) GetPreviousScrollPositionValid() bool {
	if x != nil && x.PreviousScrollPositionValid != nil {
		return *x.PreviousScrollPositionValid
	}
	return false
}

func (x *SheetUIStateArchive) GetVisibleSize() *TSP.Size {
	if x != nil {
		return x.VisibleSize
	}
	return nil
}

func (x *SheetUIStateArchive) GetPreviousVisibleSize() *TSP.Size {
	if x != nil {
		return x.PreviousVisibleSize
	}
	return nil
}

func (x *SheetUIStateArchive) GetDeviceIdiom() uint32 {
	if x != nil && x.DeviceIdiom != nil {
		return *x.DeviceIdiom
	}
	return 0
}

func (x *SheetUIStateArchive) GetSelectionPath() *TSK.SelectionPathArchive {
	if x != nil {
		return x.SelectionPath
	}
	return nil
}

func (x *SheetUIStateArchive) GetSelectionPathTransformer() *TSP.Reference {
	if x != nil {
		return x.SelectionPathTransformer
	}
	return nil
}

type SheetUIStateDictionaryEntryArchive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sheet         *TSP.Reference         `protobuf:"bytes,1,req,name=sheet" json:"sheet,omitempty"`
	SheetUistate  *SheetUIStateArchive   `protobuf:"bytes,2,req,name=sheet_uistate,json=sheetUistate" json:"sheet_uistate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SheetUIStateDictionaryEntryArchive) Reset() {
	*x = SheetUIStateDictionaryEntryArchive{}
	mi := &file_TNArchives_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SheetUIStateDictionaryEntryArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SheetUIStateDictionaryEntryArchive) ProtoMessage() {}

func (x *SheetUIStateDictionaryEntryArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TNArchives_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SheetUIStateDictionaryEntryArchive.ProtoReflect.Descriptor instead.
func (*SheetUIStateDictionaryEntryArchive) Descriptor() ([]byte, []int) {
	return file_TNArchives_proto_rawDescGZIP(), []int{1}
}

func (x *SheetUIStateDictionaryEntryArchive) GetSheet() *TSP.Reference {
	if x != nil {
		return x.Sheet
	}
	return nil
}

func (x *SheetUIStateDictionaryEntryArchive) GetSheetUistate() *SheetUIStateArchive {
	if x != nil {
		return x.SheetUistate
	}
	return nil
}

type UUIDSheetUIStateDictionaryArchive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SheetUuid     *TSP.UUID              `protobuf:"bytes,1,req,name=sheet_uuid,json=sheetUuid" json:"sheet_uuid,omitempty"`
	SheetUistate  *SheetUIStateArchive   `protobuf:"bytes,2,req,name=sheet_uistate,json=sheetUistate" json:"sheet_uistate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UUIDSheetUIStateDictionaryArchive) Reset() {
	*x = UUIDSheetUIStateDictionaryArchive{}
	mi := &file_TNArchives_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UUIDSheetUIStateDictionaryArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUIDSheetUIStateDictionaryArchive) ProtoMessage() {}

func (x *UUIDSheetUIStateDictionaryArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TNArchives_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUIDSheetUIStateDictionaryArchive.ProtoReflect.Descriptor instead.
func (*UUIDSheetUIStateDictionaryArchive) Descriptor() ([]byte, []int) {
	return file_TNArchives_proto_rawDescGZIP(), []int{2}
}

func (x *UUIDSheetUIStateDictionaryArchive) GetSheetUuid() *TSP.UUID {
	if x != nil {
		return x.SheetUuid
	}
	return nil
}

func (x *UUIDSheetUIStateDictionaryArchive) GetSheetUistate() *SheetUIStateArchive {
	if x != nil {
		return x.SheetUistate
	}
	return nil
}

type UIStateArchive struct {
	state                               protoimpl.MessageState                `protogen:"open.v1"`
	ActiveSheetIndex                    *uint32                               `protobuf:"varint,1,req,name=active_sheet_index,json=activeSheetIndex" json:"active_sheet_index,omitempty"`
	SelectedInfo                        []*TSP.Reference                      `protobuf:"bytes,2,rep,name=selected_info,json=selectedInfo" json:"selected_info,omitempty"`
	SheetUistateDictionaryEntry         []*SheetUIStateDictionaryEntryArchive `protobuf:"bytes,3,rep,name=sheet_uistate_dictionary_entry,json=sheetUistateDictionaryEntry" json:"sheet_uistate_dictionary_entry,omitempty"`
	TableSelection                      *TST.SelectionArchive                 `protobuf:"bytes,4,opt,name=table_selection,json=tableSelection" json:"table_selection,omitempty"`
	EditingSheetIndex                   *uint32                               `protobuf:"varint,5,opt,name=editing_sheet_index,json=editingSheetIndex" json:"editing_sheet_index,omitempty"`
	DocumentMode                        *int32                                `protobuf:"varint,6,opt,name=document_mode,json=documentMode" json:"document_mode,omitempty"`
	EditModeSheetUistateDictionaryEntry []*SheetUIStateDictionaryEntryArchive `protobuf:"bytes,7,rep,name=edit_mode_sheet_uistate_dictionary_entry,json=editModeSheetUistateDictionaryEntry" json:"edit_mode_sheet_uistate_dictionary_entry,omitempty"`
	TableEditingMode                    *int32                                `protobuf:"varint,8,opt,name=table_editing_mode,json=tableEditingMode" json:"table_editing_mode,omitempty"`
	FormFocusedRecordIndex              *uint32                               `protobuf:"varint,9,opt,name=form_focused_record_index,json=formFocusedRecordIndex" json:"form_focused_record_index,omitempty"`
	FormFocusedFieldIndex               *uint32                               `protobuf:"varint,10,opt,name=form_focused_field_index,json=formFocusedFieldIndex" json:"form_focused_field_index,omitempty"`
	InChartMode                         *bool                                 `protobuf:"varint,11,opt,name=in_chart_mode,json=inChartMode" json:"in_chart_mode,omitempty"`
	ChartSelection                      *ChartSelectionArchive                `protobuf:"bytes,12,opt,name=chart_selection,json=chartSelection" json:"chart_selection,omitempty"`
	SheetSelection                      *TSP.Reference                        `protobuf:"bytes,13,opt,name=sheet_selection,json=sheetSelection" json:"sheet_selection,omitempty"`
	InspectorPaneVisible                *bool                                 `protobuf:"varint,14,opt,name=inspector_pane_visible,json=inspectorPaneVisible,def=1" json:"inspector_pane_visible,omitempty"`
	InspectorPaneViewMode               *UIStateArchive_InspectorPaneViewMode `protobuf:"varint,15,opt,name=inspector_pane_view_mode,json=inspectorPaneViewMode,enum=TN.UIStateArchive_InspectorPaneViewMode,def=0" json:"inspector_pane_view_mode,omitempty"`
	SelectedQuickCalcFunctions          []uint32                              `protobuf:"varint,16,rep,name=selected_quick_calc_functions,json=selectedQuickCalcFunctions" json:"selected_quick_calc_functions,omitempty"`
	RemovedAllQuickCalcFunctions        *bool                                 `protobuf:"varint,17,opt,name=removed_all_quick_calc_functions,json=removedAllQuickCalcFunctions" json:"removed_all_quick_calc_functions,omitempty"`
	ShowCanvasGuides                    *bool                                 `protobuf:"varint,18,opt,name=show_canvas_guides,json=showCanvasGuides" json:"show_canvas_guides,omitempty"`
	ShowsComments                       *bool                                 `protobuf:"varint,19,opt,name=shows_comments,json=showsComments" json:"shows_comments,omitempty"`
	DesktopWindowOrigin                 *TSP.Point                            `protobuf:"bytes,20,opt,name=desktop_window_origin,json=desktopWindowOrigin" json:"desktop_window_origin,omitempty"`
	DesktopWindowSize                   *TSP.Size                             `protobuf:"bytes,21,opt,name=desktop_window_size,json=desktopWindowSize" json:"desktop_window_size,omitempty"`
	DesktopScreenSize                   *TSP.Size                             `protobuf:"bytes,22,opt,name=desktop_screen_size,json=desktopScreenSize" json:"desktop_screen_size,omitempty"`
	ChartUiState                        []*TSCH.ChartUIState                  `protobuf:"bytes,23,rep,name=chart_ui_state,json=chartUiState" json:"chart_ui_state,omitempty"`
	SelectionPath                       *TSK.SelectionPathArchive             `protobuf:"bytes,24,opt,name=selection_path,json=selectionPath" json:"selection_path,omitempty"`
	InspectorPaneAutohidden             *bool                                 `protobuf:"varint,25,opt,name=inspector_pane_autohidden,json=inspectorPaneAutohidden" json:"inspector_pane_autohidden,omitempty"`
	ShowsSidebar                        *bool                                 `protobuf:"varint,26,opt,name=shows_sidebar,json=showsSidebar" json:"shows_sidebar,omitempty"`
	ShowsRulers                         *bool                                 `protobuf:"varint,27,opt,name=shows_rulers,json=showsRulers" json:"shows_rulers,omitempty"`
	UuidSheetUistateDictionary          []*UUIDSheetUIStateDictionaryArchive  `protobuf:"bytes,28,rep,name=uuid_sheet_uistate_dictionary,json=uuidSheetUistateDictionary" json:"uuid_sheet_uistate_dictionary,omitempty"`
	FreehandDrawingToolkitState         *TSP.Reference                        `protobuf:"bytes,29,opt,name=freehand_drawing_toolkit_state,json=freehandDrawingToolkitState" json:"freehand_drawing_toolkit_state,omitempty"`
	SelectionPathTransformer            *TSP.Reference                        `protobuf:"bytes,30,opt,name=selection_path_transformer,json=selectionPathTransformer" json:"selection_path_transformer,omitempty"`
	EditingDisabled                     *bool                                 `protobuf:"varint,31,opt,name=editing_disabled,json=editingDisabled" json:"editing_disabled,omitempty"`
	SidebarVisible                      *bool                                 `protobuf:"varint,32,opt,name=sidebar_visible,json=sidebarVisible" json:"sidebar_visible,omitempty"`
	SidebarWidth                        *float32                              `protobuf:"fixed32,33,opt,name=sidebar_width,json=sidebarWidth" json:"sidebar_width,omitempty"`
	unknownFields                       protoimpl.UnknownFields
	sizeCache                           protoimpl.SizeCache
}

// Default values for UIStateArchive fields.
const (
	Default_UIStateArchive_InspectorPaneVisible  = bool(true)
	Default_UIStateArchive_InspectorPaneViewMode = UIStateArchive_kInspectorPaneViewModeFormat
)

func (x *UIStateArchive) Reset() {
	*x = UIStateArchive{}
	mi := &file_TNArchives_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIStateArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIStateArchive) ProtoMessage() {}

func (x *UIStateArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TNArchives_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIStateArchive.ProtoReflect.Descriptor instead.
func (*UIStateArchive) Descriptor() ([]byte, []int) {
	return file_TNArchives_proto_rawDescGZIP(), []int{3}
}

func (x *UIStateArchive) GetActiveSheetIndex() uint32 {
	if x != nil && x.ActiveSheetIndex != nil {
		return *x.ActiveSheetIndex
	}
	return 0
}

func (x *UIStateArchive) GetSelectedInfo() []*TSP.Reference {
	if x != nil {
		return x.SelectedInfo
	}
	return nil
}

func (x *UIStateArchive) GetSheetUistateDictionaryEntry() []*SheetUIStateDictionaryEntryArchive {
	if x != nil {
		return x.SheetUistateDictionaryEntry
	}
	return nil
}

func (x *UIStateArchive) GetTableSelection() *TST.SelectionArchive {
	if x != nil {
		return x.TableSelection
	}
	return nil
}

func (x *UIStateArchive) GetEditingSheetIndex() uint32 {
	if x != nil && x.EditingSheetIndex != nil {
		return *x.EditingSheetIndex
	}
	return 0
}

func (x *UIStateArchive) GetDocumentMode() int32 {
	if x != nil && x.DocumentMode != nil {
		return *x.DocumentMode
	}
	return 0
}

func (x *UIStateArchive) GetEditModeSheetUistateDictionaryEntry() []*SheetUIStateDictionaryEntryArchive {
	if x != nil {
		return x.EditModeSheetUistateDictionaryEntry
	}
	return nil
}

func (x *UIStateArchive) GetTableEditingMode() int32 {
	if x != nil && x.TableEditingMode != nil {
		return *x.TableEditingMode
	}
	return 0
}

func (x *UIStateArchive) GetFormFocusedRecordIndex() uint32 {
	if x != nil && x.FormFocusedRecordIndex != nil {
		return *x.FormFocusedRecordIndex
	}
	return 0
}

func (x *UIStateArchive) GetFormFocusedFieldIndex() uint32 {
	if x != nil && x.FormFocusedFieldIndex != nil {
		return *x.FormFocusedFieldIndex
	}
	return 0
}

func (x *UIStateArchive) GetInChartMode() bool {
	if x != nil && x.InChartMode != nil {
		return *x.InChartMode
	}
	return false
}

func (x *UIStateArchive) GetChartSelection() *ChartSelectionArchive {
	if x != nil {
		return x.ChartSelection
	}
	return nil
}

func (x *UIStateArchive) GetSheetSelection() *TSP.Reference {
	if x != nil {
		return x.SheetSelection
	}
	return nil
}

func (x *UIStateArchive) GetInspectorPaneVisible() bool {
	if x != nil && x.InspectorPaneVisible != nil {
		return *x.InspectorPaneVisible
	}
	return Default_UIStateArchive_InspectorPaneVisible
}

func (x *UIStateArchive) GetInspectorPaneViewMode() UIStateArchive_InspectorPaneViewMode {
	if x != nil && x.InspectorPaneViewMode != nil {
		return *x.InspectorPaneViewMode
	}
	return Default_UIStateArchive_InspectorPaneViewMode
}

func (x *UIStateArchive) GetSelectedQuickCalcFunctions() []uint32 {
	if x != nil {
		return x.SelectedQuickCalcFunctions
	}
	return nil
}

func (x *UIStateArchive) GetRemovedAllQuickCalcFunctions() bool {
	if x != nil && x.RemovedAllQuickCalcFunctions != nil {
		return *x.RemovedAllQuickCalcFunctions
	}
	return false
}

func (x *UIStateArchive) GetShowCanvasGuides() bool {
	if x != nil && x.ShowCanvasGuides != nil {
		return *x.ShowCanvasGuides
	}
	return false
}

func (x *UIStateArchive) GetShowsComments() bool {
	if x != nil && x.ShowsComments != nil {
		return *x.ShowsComments
	}
	return false
}

func (x *UIStateArchive) GetDesktopWindowOrigin() *TSP.Point {
	if x != nil {
		return x.DesktopWindowOrigin
	}
	return nil
}

func (x *UIStateArchive) GetDesktopWindowSize() *TSP.Size {
	if x != nil {
		return x.DesktopWindowSize
	}
	return nil
}

func (x *UIStateArchive) GetDesktopScreenSize() *TSP.Size {
	if x != nil {
		return x.DesktopScreenSize
	}
	return nil
}

func (x *UIStateArchive) GetChartUiState() []*TSCH.ChartUIState {
	if x != nil {
		return x.ChartUiState
	}
	return nil
}

func (x *UIStateArchive) GetSelectionPath() *TSK.SelectionPathArchive {
	if x != nil {
		return x.SelectionPath
	}
	return nil
}

func (x *UIStateArchive) GetInspectorPaneAutohidden() bool {
	if x != nil && x.InspectorPaneAutohidden != nil {
		return *x.InspectorPaneAutohidden
	}
	return false
}

func (x *UIStateArchive) GetShowsSidebar() bool {
	if x != nil && x.ShowsSidebar != nil {
		return *x.ShowsSidebar
	}
	return false
}

func (x *UIStateArchive) GetShowsRulers() bool {
	if x != nil && x.ShowsRulers != nil {
		return *x.ShowsRulers
	}
	return false
}

func (x *UIStateArchive) GetUuidSheetUistateDictionary() []*UUIDSheetUIStateDictionaryArchive {
	if x != nil {
		return x.UuidSheetUistateDictionary
	}
	return nil
}

func (x *UIStateArchive) GetFreehandDrawingToolkitState() *TSP.Reference {
	if x != nil {
		return x.FreehandDrawingToolkitState
	}
	return nil
}

func (x *UIStateArchive) GetSelectionPathTransformer() *TSP.Reference {
	if x != nil {
		return x.SelectionPathTransformer
	}
	return nil
}

func (x *UIStateArchive) GetEditingDisabled() bool {
	if x != nil && x.EditingDisabled != nil {
		return *x.EditingDisabled
	}
	return false
}

func (x *UIStateArchive) GetSidebarVisible() bool {
	if x != nil && x.SidebarVisible != nil {
		return *x.SidebarVisible
	}
	return false
}

func (x *UIStateArchive) GetSidebarWidth() float32 {
	if x != nil && x.SidebarWidth != nil {
		return *x.SidebarWidth
	}
	return 0
}

type SheetSelectionArchive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sheet         *TSP.Reference         `protobuf:"bytes,1,opt,name=sheet" json:"sheet,omitempty"`
	Paginated     *bool                  `protobuf:"varint,2,opt,name=paginated" json:"paginated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SheetSelectionArchive) Reset() {
	*x = SheetSelectionArchive{}
	mi := &file_TNArchives_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SheetSelectionArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SheetSelectionArchive) ProtoMessage() {}

func (x *SheetSelectionArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TNArchives_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SheetSelectionArchive.ProtoReflect.Descriptor instead.
func (*SheetSelectionArchive) Descriptor() ([]byte, []int) {
	return file_TNArchives_proto_rawDescGZIP(), []int{4}
}

func (x *SheetSelectionArchive) GetSheet() *TSP.Reference {
	if x != nil {
		return x.Sheet
	}
	return nil
}

func (x *SheetSelectionArchive) GetPaginated() bool {
	if x != nil && x.Paginated != nil {
		return *x.Paginated
	}
	return false
}

type FormSelectionArchive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecordIndex   *uint32                `protobuf:"varint,1,req,name=record_index,json=recordIndex" json:"record_index,omitempty"`
	FieldIndex    *uint32                `protobuf:"varint,2,req,name=field_index,json=fieldIndex" json:"field_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FormSelectionArchive) Reset() {
	*x = FormSelectionArchive{}
	mi := &file_TNArchives_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormSelectionArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormSelectionArchive) ProtoMessage() {}

func (x *FormSelectionArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TNArchives_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormSelectionArchive.ProtoReflect.Descriptor instead.
func (*FormSelectionArchive) Descriptor() ([]byte, []int) {
	return file_TNArchives_proto_rawDescGZIP(), []int{5}
}

func (x *FormSelectionArchive) GetRecordIndex() uint32 {
	if x != nil && x.RecordIndex != nil {
		return *x.RecordIndex
	}
	return 0
}

func (x *FormSelectionArchive) GetFieldIndex() uint32 {
	if x != nil && x.FieldIndex != nil {
		return *x.FieldIndex
	}
	return 0
}

type FormBuilderSelectionArchive struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ViewingRecordIndex *uint32                `protobuf:"varint,1,opt,name=viewing_record_index,json=viewingRecordIndex" json:"viewing_record_index,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FormBuilderSelectionArchive) Reset() {
	*x = FormBuilderSelectionArchive{}
	mi := &file_TNArchives_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormBuilderSelectionArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormBuilderSelectionArchive) ProtoMessage() {}

func (x *FormBuilderSelectionArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TNArchives_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormBuilderSelectionArchive.ProtoReflect.Descriptor instead.
func (*FormBuilderSelectionArchive) Descriptor() ([]byte, []int) {
	return file_TNArchives_proto_rawDescGZIP(), []int{6}
}

func (x *FormBuilderSelectionArchive) GetViewingRecordIndex() uint32 {
	if x != nil && x.ViewingRecordIndex != nil {
		return *x.ViewingRecordIndex
	}
	return 0
}

type FormTableChooserSelectionArchive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FormTableChooserSelectionArchive) Reset() {
	*x = FormTableChooserSelectionArchive{}
	mi := &file_TNArchives_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormTableChooserSelectionArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormTableChooserSelectionArchive) ProtoMessage() {}

func (x *FormTableChooserSelectionArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TNArchives_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormTableChooserSelectionArchive.ProtoReflect.Descriptor instead.
func (*FormTableChooserSelectionArchive) Descriptor() ([]byte, []int) {
	return file_TNArchives_proto_rawDescGZIP(), []int{7}
}

type UndoRedoStateArchive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UiState       *UIStateArchive        `protobuf:"bytes,1,req,name=ui_state,json=uiState" json:"ui_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UndoRedoStateArchive) Reset() {
	*x = UndoRedoStateArchive{}
	mi := &file_TNArchives_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UndoRedoStateArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UndoRedoStateArchive) ProtoMessage() {}

func (x *UndoRedoStateArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TNArchives_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UndoRedoStateArchive.ProtoReflect.Descriptor instead.
func (*UndoRedoStateArchive) Descriptor() ([]byte, []int) {
	return file_TNArchives_proto_rawDescGZIP(), []int{8}
}

func (x *UndoRedoStateArchive) GetUiState() *UIStateArchive {
	if x != nil {
		return x.UiState
	}
	return nil
}

type DocumentArchive struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Sheets            []*TSP.Reference       `protobuf:"bytes,1,rep,name=sheets" json:"sheets,omitempty"`
	Super             *TSA.DocumentArchive   `protobuf:"bytes,8,req,name=super" json:"super,omitempty"`
	CalculationEngine *TSP.Reference         `protobuf:"bytes,3,opt,name=calculation_engine,json=calculationEngine" json:"calculation_engine,omitempty"`
	Stylesheet        *TSP.Reference         `protobuf:"bytes,4,req,name=stylesheet" json:"stylesheet,omitempty"`
	SidebarOrder      *TSP.Reference         `protobuf:"bytes,5,req,name=sidebar_order,json=sidebarOrder" json:"sidebar_order,omitempty"`
	Theme             *TSP.Reference         `protobuf:"bytes,6,req,name=theme" json:"theme,omitempty"`
	Uistate           *UIStateArchive        `protobuf:"bytes,7,opt,name=uistate" json:"uistate,omitempty"`
	CustomFormatList  *TSP.Reference         `protobuf:"bytes,9,opt,name=custom_format_list,json=customFormatList" json:"custom_format_list,omitempty"`
	PrinterId         *string                `protobuf:"bytes,10,opt,name=printer_id,json=printerId" json:"printer_id,omitempty"`
	PaperId           *string                `protobuf:"bytes,11,opt,name=paper_id,json=paperId" json:"paper_id,omitempty"`
	PageSize          *TSP.Size              `protobuf:"bytes,12,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DocumentArchive) Reset() {
	*x = DocumentArchive{}
	mi := &file_TNArchives_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentArchive) ProtoMessage() {}

func (x *DocumentArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TNArchives_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentArchive.ProtoReflect.Descriptor instead.
func (*DocumentArchive) Descriptor() ([]byte, []int) {
	return file_TNArchives_proto_rawDescGZIP(), []int{9}
}

func (x *DocumentArchive) GetSheets() []*TSP.Reference {
	if x != nil {
		return x.Sheets
	}
	return nil
}

func (x *DocumentArchive) GetSuper() *TSA.DocumentArchive {
	if x != nil {
		return x.Super
	}
	return nil
}

func (x *DocumentArchive) GetCalculationEngine() *TSP.Reference {
	if x != nil {
		return x.CalculationEngine
	}
	return nil
}

func (x *DocumentArchive) GetStylesheet() *TSP.Reference {
	if x != nil {
		return x.Stylesheet
	}
	return nil
}

func (x *DocumentArchive) GetSidebarOrder() *TSP.Reference {
	if x != nil {
		return x.SidebarOrder
	}
	return nil
}

func (x *DocumentArchive) GetTheme() *TSP.Reference {
	if x != nil {
		return x.Theme
	}
	return nil
}

func (x *DocumentArchive) GetUistate() *UIStateArchive {
	if x != nil {
		return x.Uistate
	}
	return nil
}

func (x *DocumentArchive) GetCustomFormatList() *TSP.Reference {
	if x != nil {
		return x.CustomFormatList
	}
	return nil
}

func (x *DocumentArchive) GetPrinterId() string {
	if x != nil && x.PrinterId != nil {
		return *x.PrinterId
	}
	return ""
}

func (x *DocumentArchive) GetPaperId() string {
	if x != nil && x.PaperId != nil {
		return *x.PaperId
	}
	return ""
}

func (x *DocumentArchive) GetPageSize() *TSP.Size {
	if x != nil {
		return x.PageSize
	}
	return nil
}

type PlaceholderArchive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Super         *TSWP.ShapeInfoArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceholderArchive) Reset() {
	*x = PlaceholderArchive{}
	mi := &file_TNArchives_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceholderArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceholderArchive) ProtoMessage() {}

func (x *PlaceholderArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TNArchives_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceholderArchive.ProtoReflect.Descriptor instead.
func (*PlaceholderArchive) Descriptor() ([]byte, []int) {
	return file_TNArchives_proto_rawDescGZIP(), []int{10}
}

func (x *PlaceholderArchive) GetSuper() *TSWP.ShapeInfoArchive {
	if x != nil {
		return x.Super
	}
	return nil
}

type SheetArchive struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Name                      *string                `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	DrawableInfos             []*TSP.Reference       `protobuf:"bytes,2,rep,name=drawable_infos,json=drawableInfos" json:"drawable_infos,omitempty"`
	InPortraitPageOrientation *bool                  `protobuf:"varint,3,opt,name=in_portrait_page_orientation,json=inPortraitPageOrientation" json:"in_portrait_page_orientation,omitempty"`
	ShowRepeatingHeaders      *bool                  `protobuf:"varint,4,opt,name=show_repeating_headers,json=showRepeatingHeaders" json:"show_repeating_headers,omitempty"`
	ShowPageNumbers           *bool                  `protobuf:"varint,5,opt,name=show_page_numbers,json=showPageNumbers" json:"show_page_numbers,omitempty"`
	IsAutofitOn               *bool                  `protobuf:"varint,6,opt,name=is_autofit_on,json=isAutofitOn" json:"is_autofit_on,omitempty"`
	ContentScale              *float32               `protobuf:"fixed32,7,opt,name=content_scale,json=contentScale" json:"content_scale,omitempty"`
	PageOrder                 *PageOrder             `protobuf:"varint,8,opt,name=page_order,json=pageOrder,enum=TN.PageOrder" json:"page_order,omitempty"`
	PrintMargins              *TSD.EdgeInsetsArchive `protobuf:"bytes,10,opt,name=print_margins,json=printMargins" json:"print_margins,omitempty"`
	UsingStartPageNumber      *bool                  `protobuf:"varint,11,opt,name=using_start_page_number,json=usingStartPageNumber" json:"using_start_page_number,omitempty"`
	StartPageNumber           *int32                 `protobuf:"varint,12,opt,name=start_page_number,json=startPageNumber" json:"start_page_number,omitempty"`
	PageHeaderInset           *float32               `protobuf:"fixed32,13,opt,name=page_header_inset,json=pageHeaderInset" json:"page_header_inset,omitempty"`
	PageFooterInset           *float32               `protobuf:"fixed32,14,opt,name=page_footer_inset,json=pageFooterInset" json:"page_footer_inset,omitempty"`
	HeaderStorage             *TSP.Reference         `protobuf:"bytes,15,opt,name=header_storage,json=headerStorage" json:"header_storage,omitempty"`
	FooterStorage             *TSP.Reference         `protobuf:"bytes,16,opt,name=footer_storage,json=footerStorage" json:"footer_storage,omitempty"`
	UserDefinedGuideStorage   *TSP.Reference         `protobuf:"bytes,17,opt,name=userDefinedGuideStorage" json:"userDefinedGuideStorage,omitempty"`
	Headers                   []*TSP.Reference       `protobuf:"bytes,18,rep,name=headers" json:"headers,omitempty"`
	Footers                   []*TSP.Reference       `protobuf:"bytes,19,rep,name=footers" json:"footers,omitempty"`
	UsesSingleHeaderFooter    *bool                  `protobuf:"varint,20,opt,name=uses_single_header_footer,json=usesSingleHeaderFooter" json:"uses_single_header_footer,omitempty"`
	LayoutDirection           *PageLayoutDirection   `protobuf:"varint,21,opt,name=layout_direction,json=layoutDirection,enum=TN.PageLayoutDirection,def=0" json:"layout_direction,omitempty"`
	Style                     *TSP.Reference         `protobuf:"bytes,22,opt,name=style" json:"style,omitempty"`
	PrintBackgrounds          *bool                  `protobuf:"varint,23,opt,name=print_backgrounds,json=printBackgrounds" json:"print_backgrounds,omitempty"`
	ShouldPrintComments       *bool                  `protobuf:"varint,24,opt,name=should_print_comments,json=shouldPrintComments" json:"should_print_comments,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

// Default values for SheetArchive fields.
const (
	Default_SheetArchive_LayoutDirection = PageLayoutDirection_PageLayoutDirectionLeftToRight
)

func (x *SheetArchive) Reset() {
	*x = SheetArchive{}
	mi := &file_TNArchives_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SheetArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SheetArchive) ProtoMessage() {}

func (x *SheetArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TNArchives_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SheetArchive.ProtoReflect.Descriptor instead.
func (*SheetArchive) Descriptor() ([]byte, []int) {
	return file_TNArchives_proto_rawDescGZIP(), []int{11}
}

func (x *SheetArchive) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *SheetArchive) GetDrawableInfos() []*TSP.Reference {
	if x != nil {
		return x.DrawableInfos
	}
	return nil
}

func (x *SheetArchive) GetInPortraitPageOrientation() bool {
	if x != nil && x.InPortraitPageOrientation != nil {
		return *x.InPortraitPageOrientation
	}
	return false
}

func (x *SheetArchive) GetShowRepeatingHeaders() bool {
	if x != nil && x.ShowRepeatingHeaders != nil {
		return *x.ShowRepeatingHeaders
	}
	return false
}

func (x *SheetArchive) GetShowPageNumbers() bool {
	if x != nil && x.ShowPageNumbers != nil {
		return *x.ShowPageNumbers
	}
	return false
}

func (x *SheetArchive) GetIsAutofitOn() bool {
	if x != nil && x.IsAutofitOn != nil {
		return *x.IsAutofitOn
	}
	return false
}

func (x *SheetArchive) GetContentScale() float32 {
	if x != nil && x.ContentScale != nil {
		return *x.ContentScale
	}
	return 0
}

func (x *SheetArchive) GetPageOrder() PageOrder {
	if x != nil && x.PageOrder != nil {
		return *x.PageOrder
	}
	return PageOrder_PageOrderTopToBottom
}

func (x *SheetArchive) GetPrintMargins() *TSD.EdgeInsetsArchive {
	if x != nil {
		return x.PrintMargins
	}
	return nil
}

func (x *SheetArchive) GetUsingStartPageNumber() bool {
	if x != nil && x.UsingStartPageNumber != nil {
		return *x.UsingStartPageNumber
	}
	return false
}

func (x *SheetArchive) GetStartPageNumber() int32 {
	if x != nil && x.StartPageNumber != nil {
		return *x.StartPageNumber
	}
	return 0
}

func (x *SheetArchive) GetPageHeaderInset() float32 {
	if x != nil && x.PageHeaderInset != nil {
		return *x.PageHeaderInset
	}
	return 0
}

func (x *SheetArchive) GetPageFooterInset() float32 {
	if x != nil && x.PageFooterInset != nil {
		return *x.PageFooterInset
	}
	return 0
}

func (x *SheetArchive) GetHeaderStorage() *TSP.Reference {
	if x != nil {
		return x.HeaderStorage
	}
	return nil
}

func (x *SheetArchive) GetFooterStorage() *TSP.Reference {
	if x != nil {
		return x.FooterStorage
	}
	return nil
}

func (x *SheetArchive) GetUserDefinedGuideStorage() *TSP.Reference {
	if x != nil {
		return x.UserDefinedGuideStorage
	}
	return nil
}

func (x *SheetArchive) GetHeaders() []*TSP.Reference {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *SheetArchive) GetFooters() []*TSP.Reference {
	if x != nil {
		return x.Footers
	}
	return nil
}

func (x *SheetArchive) GetUsesSingleHeaderFooter() bool {
	if x != nil && x.UsesSingleHeaderFooter != nil {
		return *x.UsesSingleHeaderFooter
	}
	return false
}

func (x *SheetArchive) GetLayoutDirection() PageLayoutDirection {
	if x != nil && x.LayoutDirection != nil {
		return *x.LayoutDirection
	}
	return Default_SheetArchive_LayoutDirection
}

func (x *SheetArchive) GetStyle() *TSP.Reference {
	if x != nil {
		return x.Style
	}
	return nil
}

func (x *SheetArchive) GetPrintBackgrounds() bool {
	if x != nil && x.PrintBackgrounds != nil {
		return *x.PrintBackgrounds
	}
	return false
}

func (x *SheetArchive) GetShouldPrintComments() bool {
	if x != nil && x.ShouldPrintComments != nil {
		return *x.ShouldPrintComments
	}
	return false
}

type SheetStylePropertiesArchive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fill          *TSD.FillArchive       `protobuf:"bytes,1,opt,name=fill" json:"fill,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SheetStylePropertiesArchive) Reset() {
	*x = SheetStylePropertiesArchive{}
	mi := &file_TNArchives_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SheetStylePropertiesArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SheetStylePropertiesArchive) ProtoMessage() {}

func (x *SheetStylePropertiesArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TNArchives_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SheetStylePropertiesArchive.ProtoReflect.Descriptor instead.
func (*SheetStylePropertiesArchive) Descriptor() ([]byte, []int) {
	return file_TNArchives_proto_rawDescGZIP(), []int{12}
}

func (x *SheetStylePropertiesArchive) GetFill() *TSD.FillArchive {
	if x != nil {
		return x.Fill
	}
	return nil
}

type SheetStyleArchive struct {
	state           protoimpl.MessageState       `protogen:"open.v1"`
	Super           *TSS.StyleArchive            `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	OverrideCount   *uint32                      `protobuf:"varint,2,opt,name=override_count,json=overrideCount" json:"override_count,omitempty"`
	SheetProperties *SheetStylePropertiesArchive `protobuf:"bytes,3,opt,name=sheet_properties,json=sheetProperties" json:"sheet_properties,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SheetStyleArchive) Reset() {
	*x = SheetStyleArchive{}
	mi := &file_TNArchives_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SheetStyleArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SheetStyleArchive) ProtoMessage() {}

func (x *SheetStyleArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TNArchives_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SheetStyleArchive.ProtoReflect.Descriptor instead.
func (*SheetStyleArchive) Descriptor() ([]byte, []int) {
	return file_TNArchives_proto_rawDescGZIP(), []int{13}
}

func (x *SheetStyleArchive) GetSuper() *TSS.StyleArchive {
	if x != nil {
		return x.Super
	}
	return nil
}

func (x *SheetStyleArchive) GetOverrideCount() uint32 {
	if x != nil && x.OverrideCount != nil {
		return *x.OverrideCount
	}
	return 0
}

func (x *SheetStyleArchive) GetSheetProperties() *SheetStylePropertiesArchive {
	if x != nil {
		return x.SheetProperties
	}
	return nil
}

type FormBasedSheetArchive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Super         *SheetArchive          `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	TableId       *TSP.CFUUIDArchive     `protobuf:"bytes,2,opt,name=table_id,json=tableId" json:"table_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FormBasedSheetArchive) Reset() {
	*x = FormBasedSheetArchive{}
	mi := &file_TNArchives_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormBasedSheetArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormBasedSheetArchive) ProtoMessage() {}

func (x *FormBasedSheetArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TNArchives_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormBasedSheetArchive.ProtoReflect.Descriptor instead.
func (*FormBasedSheetArchive) Descriptor() ([]byte, []int) {
	return file_TNArchives_proto_rawDescGZIP(), []int{14}
}

func (x *FormBasedSheetArchive) GetSuper() *SheetArchive {
	if x != nil {
		return x.Super
	}
	return nil
}

func (x *FormBasedSheetArchive) GetTableId() *TSP.CFUUIDArchive {
	if x != nil {
		return x.TableId
	}
	return nil
}

type ThemeArchive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Super         *TSS.ThemeArchive      `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	Prototypes    []*TSP.Reference       `protobuf:"bytes,2,rep,name=prototypes" json:"prototypes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThemeArchive) Reset() {
	*x = ThemeArchive{}
	mi := &file_TNArchives_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThemeArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThemeArchive) ProtoMessage() {}

func (x *ThemeArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TNArchives_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThemeArchive.ProtoReflect.Descriptor instead.
func (*ThemeArchive) Descriptor() ([]byte, []int) {
	return file_TNArchives_proto_rawDescGZIP(), []int{15}
}

func (x *ThemeArchive) GetSuper() *TSS.ThemeArchive {
	if x != nil {
		return x.Super
	}
	return nil
}

func (x *ThemeArchive) GetPrototypes() []*TSP.Reference {
	if x != nil {
		return x.Prototypes
	}
	return nil
}

type PasteboardNativeStorageArchive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sheet         *TSP.Reference         `protobuf:"bytes,1,opt,name=sheet" json:"sheet,omitempty"`
	UiState       *SheetUIStateArchive   `protobuf:"bytes,2,opt,name=ui_state,json=uiState" json:"ui_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasteboardNativeStorageArchive) Reset() {
	*x = PasteboardNativeStorageArchive{}
	mi := &file_TNArchives_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasteboardNativeStorageArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasteboardNativeStorageArchive) ProtoMessage() {}

func (x *PasteboardNativeStorageArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TNArchives_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasteboardNativeStorageArchive.ProtoReflect.Descriptor instead.
func (*PasteboardNativeStorageArchive) Descriptor() ([]byte, []int) {
	return file_TNArchives_proto_rawDescGZIP(), []int{16}
}

func (x *PasteboardNativeStorageArchive) GetSheet() *TSP.Reference {
	if x != nil {
		return x.Sheet
	}
	return nil
}

func (x *PasteboardNativeStorageArchive) GetUiState() *SheetUIStateArchive {
	if x != nil {
		return x.UiState
	}
	return nil
}

type ChartMediatorFormulaStorage struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	DataFormulae                   []*TSCE.FormulaArchive `protobuf:"bytes,1,rep,name=data_formulae,json=dataFormulae" json:"data_formulae,omitempty"`
	RowLabelFormulae               []*TSCE.FormulaArchive `protobuf:"bytes,3,rep,name=row_label_formulae,json=rowLabelFormulae" json:"row_label_formulae,omitempty"`
	ColLabelFormulae               []*TSCE.FormulaArchive `protobuf:"bytes,4,rep,name=col_label_formulae,json=colLabelFormulae" json:"col_label_formulae,omitempty"`
	Direction                      *int32                 `protobuf:"varint,5,opt,name=direction" json:"direction,omitempty"`
	ErrorCustomPosFormulae         []*TSCE.FormulaArchive `protobuf:"bytes,6,rep,name=error_custom_pos_formulae,json=errorCustomPosFormulae" json:"error_custom_pos_formulae,omitempty"`
	ErrorCustomNegFormulae         []*TSCE.FormulaArchive `protobuf:"bytes,7,rep,name=error_custom_neg_formulae,json=errorCustomNegFormulae" json:"error_custom_neg_formulae,omitempty"`
	ErrorCustomPosScatterXFormulae []*TSCE.FormulaArchive `protobuf:"bytes,8,rep,name=error_custom_pos_scatterX_formulae,json=errorCustomPosScatterXFormulae" json:"error_custom_pos_scatterX_formulae,omitempty"`
	ErrorCustomNegScatterXFormulae []*TSCE.FormulaArchive `protobuf:"bytes,9,rep,name=error_custom_neg_scatterX_formulae,json=errorCustomNegScatterXFormulae" json:"error_custom_neg_scatterX_formulae,omitempty"`
	Scheme                         *int32                 `protobuf:"varint,10,opt,name=scheme" json:"scheme,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *ChartMediatorFormulaStorage) Reset() {
	*x = ChartMediatorFormulaStorage{}
	mi := &file_TNArchives_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChartMediatorFormulaStorage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChartMediatorFormulaStorage) ProtoMessage() {}

func (x *ChartMediatorFormulaStorage) ProtoReflect() protoreflect.Message {
	mi := &file_TNArchives_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChartMediatorFormulaStorage.ProtoReflect.Descriptor instead.
func (*ChartMediatorFormulaStorage) Descriptor() ([]byte, []int) {
	return file_TNArchives_proto_rawDescGZIP(), []int{17}
}

func (x *ChartMediatorFormulaStorage) GetDataFormulae() []*TSCE.FormulaArchive {
	if x != nil {
		return x.DataFormulae
	}
	return nil
}

func (x *ChartMediatorFormulaStorage) GetRowLabelFormulae() []*TSCE.FormulaArchive {
	if x != nil {
		return x.RowLabelFormulae
	}
	return nil
}

func (x *ChartMediatorFormulaStorage) GetColLabelFormulae() []*TSCE.FormulaArchive {
	if x != nil {
		return x.ColLabelFormulae
	}
	return nil
}

func (x *ChartMediatorFormulaStorage) GetDirection() int32 {
	if x != nil && x.Direction != nil {
		return *x.Direction
	}
	return 0
}

func (x *ChartMediatorFormulaStorage) GetErrorCustomPosFormulae() []*TSCE.FormulaArchive {
	if x != nil {
		return x.ErrorCustomPosFormulae
	}
	return nil
}

func (x *ChartMediatorFormulaStorage) GetErrorCustomNegFormulae() []*TSCE.FormulaArchive {
	if x != nil {
		return x.ErrorCustomNegFormulae
	}
	return nil
}

func (x *ChartMediatorFormulaStorage) GetErrorCustomPosScatterXFormulae() []*TSCE.FormulaArchive {
	if x != nil {
		return x.ErrorCustomPosScatterXFormulae
	}
	return nil
}

func (x *ChartMediatorFormulaStorage) GetErrorCustomNegScatterXFormulae() []*TSCE.FormulaArchive {
	if x != nil {
		return x.ErrorCustomNegScatterXFormulae
	}
	return nil
}

func (x *ChartMediatorFormulaStorage) GetScheme() int32 {
	if x != nil && x.Scheme != nil {
		return *x.Scheme
	}
	return 0
}

type ChartMediatorArchive struct {
	state                      protoimpl.MessageState       `protogen:"open.v1"`
	Super                      *TSCH.ChartMediatorArchive   `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	EntityId                   *string                      `protobuf:"bytes,2,req,name=entity_id,json=entityId" json:"entity_id,omitempty"`
	Formulas                   *ChartMediatorFormulaStorage `protobuf:"bytes,3,opt,name=formulas" json:"formulas,omitempty"`
	ColumnsAreSeries           *bool                        `protobuf:"varint,4,opt,name=columns_are_series,json=columnsAreSeries" json:"columns_are_series,omitempty"`
	IsRegisteredWithCalcEngine *bool                        `protobuf:"varint,5,opt,name=is_registered_with_calc_engine,json=isRegisteredWithCalcEngine" json:"is_registered_with_calc_engine,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *ChartMediatorArchive) Reset() {
	*x = ChartMediatorArchive{}
	mi := &file_TNArchives_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChartMediatorArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChartMediatorArchive) ProtoMessage() {}

func (x *ChartMediatorArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TNArchives_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChartMediatorArchive.ProtoReflect.Descriptor instead.
func (*ChartMediatorArchive) Descriptor() ([]byte, []int) {
	return file_TNArchives_proto_rawDescGZIP(), []int{18}
}

func (x *ChartMediatorArchive) GetSuper() *TSCH.ChartMediatorArchive {
	if x != nil {
		return x.Super
	}
	return nil
}

func (x *ChartMediatorArchive) GetEntityId() string {
	if x != nil && x.EntityId != nil {
		return *x.EntityId
	}
	return ""
}

func (x *ChartMediatorArchive) GetFormulas() *ChartMediatorFormulaStorage {
	if x != nil {
		return x.Formulas
	}
	return nil
}

func (x *ChartMediatorArchive) GetColumnsAreSeries() bool {
	if x != nil && x.ColumnsAreSeries != nil {
		return *x.ColumnsAreSeries
	}
	return false
}

func (x *ChartMediatorArchive) GetIsRegisteredWithCalcEngine() bool {
	if x != nil && x.IsRegisteredWithCalcEngine != nil {
		return *x.IsRegisteredWithCalcEngine
	}
	return false
}

type ChartSelectionArchive struct {
	state           protoimpl.MessageState        `protogen:"open.v1"`
	Reference       *TSCE.RangeReferenceArchive   `protobuf:"bytes,1,opt,name=reference" json:"reference,omitempty"`
	DeprecatedSuper *TSCH.ChartSelectionArchive   `protobuf:"bytes,2,opt,name=deprecated_super,json=deprecatedSuper" json:"deprecated_super,omitempty"`
	Chart           *TSP.Reference                `protobuf:"bytes,3,opt,name=chart" json:"chart,omitempty"`
	Super           *TSD.DrawableSelectionArchive `protobuf:"bytes,4,opt,name=super" json:"super,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChartSelectionArchive) Reset() {
	*x = ChartSelectionArchive{}
	mi := &file_TNArchives_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChartSelectionArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChartSelectionArchive) ProtoMessage() {}

func (x *ChartSelectionArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TNArchives_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChartSelectionArchive.ProtoReflect.Descriptor instead.
func (*ChartSelectionArchive) Descriptor() ([]byte, []int) {
	return file_TNArchives_proto_rawDescGZIP(), []int{19}
}

func (x *ChartSelectionArchive) GetReference() *TSCE.RangeReferenceArchive {
	if x != nil {
		return x.Reference
	}
	return nil
}

func (x *ChartSelectionArchive) GetDeprecatedSuper() *TSCH.ChartSelectionArchive {
	if x != nil {
		return x.DeprecatedSuper
	}
	return nil
}

func (x *ChartSelectionArchive) GetChart() *TSP.Reference {
	if x != nil {
		return x.Chart
	}
	return nil
}

func (x *ChartSelectionArchive) GetSuper() *TSD.DrawableSelectionArchive {
	if x != nil {
		return x.Super
	}
	return nil
}

type FormCommandActivityBehaviorArchive struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Super         *TSCK.CommandActivityBehaviorArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FormCommandActivityBehaviorArchive) Reset() {
	*x = FormCommandActivityBehaviorArchive{}
	mi := &file_TNArchives_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormCommandActivityBehaviorArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormCommandActivityBehaviorArchive) ProtoMessage() {}

func (x *FormCommandActivityBehaviorArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TNArchives_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormCommandActivityBehaviorArchive.ProtoReflect.Descriptor instead.
func (*FormCommandActivityBehaviorArchive) Descriptor() ([]byte, []int) {
	return file_TNArchives_proto_rawDescGZIP(), []int{20}
}

func (x *FormCommandActivityBehaviorArchive) GetSuper() *TSCK.CommandActivityBehaviorArchive {
	if x != nil {
		return x.Super
	}
	return nil
}

var File_TNArchives_proto protoreflect.FileDescriptor

const file_TNArchives_proto_rawDesc = "" +
	"\n" +
	"\x10TNArchives.proto\x12\x02TN\x1a\x11TSPMessages.proto\x1a\x11TSKArchives.proto\x1a\x12TSCKArchives.proto\x1a\x12TSCHArchives.proto\x1a\x12TSCEArchives.proto\x1a\x11TSSArchives.proto\x1a\x11TSDArchives.proto\x1a\x12TSWPArchives.proto\x1a\x11TSAArchives.proto\x1a\x11TSTArchives.proto\"\xb7\x05\n" +
	"\x13SheetUIStateArchive\x12\x1d\n" +
	"\n" +
	"view_scale\x18\x01 \x02(\x02R\tviewScale\x123\n" +
	"\x0fscroll_position\x18\x02 \x02(\v2\n" +
	".TSP.PointR\x0escrollPosition\x12.\n" +
	"\x13previous_view_scale\x18\x03 \x01(\x02R\x11previousViewScale\x12=\n" +
	"\x1bscroll_position_is_unscaled\x18\x04 \x01(\bR\x18scrollPositionIsUnscaled\x12D\n" +
	"\x18previous_scroll_position\x18\x05 \x01(\v2\n" +
	".TSP.PointR\x16previousScrollPosition\x122\n" +
	"\x15scroll_position_valid\x18\x06 \x01(\bR\x13scrollPositionValid\x12C\n" +
	"\x1eprevious_scroll_position_valid\x18\a \x01(\bR\x1bpreviousScrollPositionValid\x12,\n" +
	"\fvisible_size\x18\b \x01(\v2\t.TSP.SizeR\vvisibleSize\x12=\n" +
	"\x15previous_visible_size\x18\t \x01(\v2\t.TSP.SizeR\x13previousVisibleSize\x12!\n" +
	"\fdevice_idiom\x18\n" +
	" \x01(\rR\vdeviceIdiom\x12@\n" +
	"\x0eselection_path\x18\v \x01(\v2\x19.TSK.SelectionPathArchiveR\rselectionPath\x12L\n" +
	"\x1aselection_path_transformer\x18\f \x01(\v2\x0e.TSP.ReferenceR\x18selectionPathTransformer\"\x88\x01\n" +
	"\"SheetUIStateDictionaryEntryArchive\x12$\n" +
	"\x05sheet\x18\x01 \x02(\v2\x0e.TSP.ReferenceR\x05sheet\x12<\n" +
	"\rsheet_uistate\x18\x02 \x02(\v2\x17.TN.SheetUIStateArchiveR\fsheetUistate\"\x8b\x01\n" +
	"!UUIDSheetUIStateDictionaryArchive\x12(\n" +
	"\n" +
	"sheet_uuid\x18\x01 \x02(\v2\t.TSP.UUIDR\tsheetUuid\x12<\n" +
	"\rsheet_uistate\x18\x02 \x02(\v2\x17.TN.SheetUIStateArchiveR\fsheetUistate\"\xed\x10\n" +
	"\x0eUIStateArchive\x12,\n" +
	"\x12active_sheet_index\x18\x01 \x02(\rR\x10activeSheetIndex\x123\n" +
	"\rselected_info\x18\x02 \x03(\v2\x0e.TSP.ReferenceR\fselectedInfo\x12k\n" +
	"\x1esheet_uistate_dictionary_entry\x18\x03 \x03(\v2&.TN.SheetUIStateDictionaryEntryArchiveR\x1bsheetUistateDictionaryEntry\x12>\n" +
	"\x0ftable_selection\x18\x04 \x01(\v2\x15.TST.SelectionArchiveR\x0etableSelection\x12.\n" +
	"\x13editing_sheet_index\x18\x05 \x01(\rR\x11editingSheetIndex\x12#\n" +
	"\rdocument_mode\x18\x06 \x01(\x05R\fdocumentMode\x12}\n" +
	"(edit_mode_sheet_uistate_dictionary_entry\x18\a \x03(\v2&.TN.SheetUIStateDictionaryEntryArchiveR#editModeSheetUistateDictionaryEntry\x12,\n" +
	"\x12table_editing_mode\x18\b \x01(\x05R\x10tableEditingMode\x129\n" +
	"\x19form_focused_record_index\x18\t \x01(\rR\x16formFocusedRecordIndex\x127\n" +
	"\x18form_focused_field_index\x18\n" +
	" \x01(\rR\x15formFocusedFieldIndex\x12\"\n" +
	"\rin_chart_mode\x18\v \x01(\bR\vinChartMode\x12B\n" +
	"\x0fchart_selection\x18\f \x01(\v2\x19.TN.ChartSelectionArchiveR\x0echartSelection\x127\n" +
	"\x0fsheet_selection\x18\r \x01(\v2\x0e.TSP.ReferenceR\x0esheetSelection\x12:\n" +
	"\x16inspector_pane_visible\x18\x0e \x01(\b:\x04trueR\x14inspectorPaneVisible\x12\x7f\n" +
	"\x18inspector_pane_view_mode\x18\x0f \x01(\x0e2(.TN.UIStateArchive.InspectorPaneViewMode:\x1ckInspectorPaneViewModeFormatR\x15inspectorPaneViewMode\x12A\n" +
	"\x1dselected_quick_calc_functions\x18\x10 \x03(\rR\x1aselectedQuickCalcFunctions\x12F\n" +
	" removed_all_quick_calc_functions\x18\x11 \x01(\bR\x1cremovedAllQuickCalcFunctions\x12,\n" +
	"\x12show_canvas_guides\x18\x12 \x01(\bR\x10showCanvasGuides\x12%\n" +
	"\x0eshows_comments\x18\x13 \x01(\bR\rshowsComments\x12>\n" +
	"\x15desktop_window_origin\x18\x14 \x01(\v2\n" +
	".TSP.PointR\x13desktopWindowOrigin\x129\n" +
	"\x13desktop_window_size\x18\x15 \x01(\v2\t.TSP.SizeR\x11desktopWindowSize\x129\n" +
	"\x13desktop_screen_size\x18\x16 \x01(\v2\t.TSP.SizeR\x11desktopScreenSize\x128\n" +
	"\x0echart_ui_state\x18\x17 \x03(\v2\x12.TSCH.ChartUIStateR\fchartUiState\x12@\n" +
	"\x0eselection_path\x18\x18 \x01(\v2\x19.TSK.SelectionPathArchiveR\rselectionPath\x12:\n" +
	"\x19inspector_pane_autohidden\x18\x19 \x01(\bR\x17inspectorPaneAutohidden\x12#\n" +
	"\rshows_sidebar\x18\x1a \x01(\bR\fshowsSidebar\x12!\n" +
	"\fshows_rulers\x18\x1b \x01(\bR\vshowsRulers\x12h\n" +
	"\x1duuid_sheet_uistate_dictionary\x18\x1c \x03(\v2%.TN.UUIDSheetUIStateDictionaryArchiveR\x1auuidSheetUistateDictionary\x12S\n" +
	"\x1efreehand_drawing_toolkit_state\x18\x1d \x01(\v2\x0e.TSP.ReferenceR\x1bfreehandDrawingToolkitState\x12L\n" +
	"\x1aselection_path_transformer\x18\x1e \x01(\v2\x0e.TSP.ReferenceR\x18selectionPathTransformer\x12)\n" +
	"\x10editing_disabled\x18\x1f \x01(\bR\x0feditingDisabled\x12'\n" +
	"\x0fsidebar_visible\x18  \x01(\bR\x0esidebarVisible\x12#\n" +
	"\rsidebar_width\x18! \x01(\x02R\fsidebarWidth\"[\n" +
	"\x15InspectorPaneViewMode\x12 \n" +
	"\x1ckInspectorPaneViewModeFormat\x10\x00\x12 \n" +
	"\x1ckInspectorPaneViewModeFilter\x10\x01\"[\n" +
	"\x15SheetSelectionArchive\x12$\n" +
	"\x05sheet\x18\x01 \x01(\v2\x0e.TSP.ReferenceR\x05sheet\x12\x1c\n" +
	"\tpaginated\x18\x02 \x01(\bR\tpaginated\"Z\n" +
	"\x14FormSelectionArchive\x12!\n" +
	"\frecord_index\x18\x01 \x02(\rR\vrecordIndex\x12\x1f\n" +
	"\vfield_index\x18\x02 \x02(\rR\n" +
	"fieldIndex\"O\n" +
	"\x1bFormBuilderSelectionArchive\x120\n" +
	"\x14viewing_record_index\x18\x01 \x01(\rR\x12viewingRecordIndex\"\"\n" +
	" FormTableChooserSelectionArchive\"E\n" +
	"\x14UndoRedoStateArchive\x12-\n" +
	"\bui_state\x18\x01 \x02(\v2\x12.TN.UIStateArchiveR\auiState\"\xfd\x03\n" +
	"\x0fDocumentArchive\x12&\n" +
	"\x06sheets\x18\x01 \x03(\v2\x0e.TSP.ReferenceR\x06sheets\x12*\n" +
	"\x05super\x18\b \x02(\v2\x14.TSA.DocumentArchiveR\x05super\x12=\n" +
	"\x12calculation_engine\x18\x03 \x01(\v2\x0e.TSP.ReferenceR\x11calculationEngine\x12.\n" +
	"\n" +
	"stylesheet\x18\x04 \x02(\v2\x0e.TSP.ReferenceR\n" +
	"stylesheet\x123\n" +
	"\rsidebar_order\x18\x05 \x02(\v2\x0e.TSP.ReferenceR\fsidebarOrder\x12$\n" +
	"\x05theme\x18\x06 \x02(\v2\x0e.TSP.ReferenceR\x05theme\x12,\n" +
	"\auistate\x18\a \x01(\v2\x12.TN.UIStateArchiveR\auistate\x12<\n" +
	"\x12custom_format_list\x18\t \x01(\v2\x0e.TSP.ReferenceR\x10customFormatList\x12\x1d\n" +
	"\n" +
	"printer_id\x18\n" +
	" \x01(\tR\tprinterId\x12\x19\n" +
	"\bpaper_id\x18\v \x01(\tR\apaperId\x12&\n" +
	"\tpage_size\x18\f \x01(\v2\t.TSP.SizeR\bpageSize\"B\n" +
	"\x12PlaceholderArchive\x12,\n" +
	"\x05super\x18\x01 \x02(\v2\x16.TSWP.ShapeInfoArchiveR\x05super\"\x9d\t\n" +
	"\fSheetArchive\x12\x12\n" +
	"\x04name\x18\x01 \x02(\tR\x04name\x125\n" +
	"\x0edrawable_infos\x18\x02 \x03(\v2\x0e.TSP.ReferenceR\rdrawableInfos\x12?\n" +
	"\x1cin_portrait_page_orientation\x18\x03 \x01(\bR\x19inPortraitPageOrientation\x124\n" +
	"\x16show_repeating_headers\x18\x04 \x01(\bR\x14showRepeatingHeaders\x12*\n" +
	"\x11show_page_numbers\x18\x05 \x01(\bR\x0fshowPageNumbers\x12\"\n" +
	"\ris_autofit_on\x18\x06 \x01(\bR\visAutofitOn\x12#\n" +
	"\rcontent_scale\x18\a \x01(\x02R\fcontentScale\x12,\n" +
	"\n" +
	"page_order\x18\b \x01(\x0e2\r.TN.PageOrderR\tpageOrder\x12;\n" +
	"\rprint_margins\x18\n" +
	" \x01(\v2\x16.TSD.EdgeInsetsArchiveR\fprintMargins\x125\n" +
	"\x17using_start_page_number\x18\v \x01(\bR\x14usingStartPageNumber\x12*\n" +
	"\x11start_page_number\x18\f \x01(\x05R\x0fstartPageNumber\x12*\n" +
	"\x11page_header_inset\x18\r \x01(\x02R\x0fpageHeaderInset\x12*\n" +
	"\x11page_footer_inset\x18\x0e \x01(\x02R\x0fpageFooterInset\x125\n" +
	"\x0eheader_storage\x18\x0f \x01(\v2\x0e.TSP.ReferenceR\rheaderStorage\x125\n" +
	"\x0efooter_storage\x18\x10 \x01(\v2\x0e.TSP.ReferenceR\rfooterStorage\x12H\n" +
	"\x17userDefinedGuideStorage\x18\x11 \x01(\v2\x0e.TSP.ReferenceR\x17userDefinedGuideStorage\x12(\n" +
	"\aheaders\x18\x12 \x03(\v2\x0e.TSP.ReferenceR\aheaders\x12(\n" +
	"\afooters\x18\x13 \x03(\v2\x0e.TSP.ReferenceR\afooters\x129\n" +
	"\x19uses_single_header_footer\x18\x14 \x01(\bR\x16usesSingleHeaderFooter\x12b\n" +
	"\x10layout_direction\x18\x15 \x01(\x0e2\x17.TN.PageLayoutDirection:\x1ePageLayoutDirectionLeftToRightR\x0flayoutDirection\x12$\n" +
	"\x05style\x18\x16 \x01(\v2\x0e.TSP.ReferenceR\x05style\x12+\n" +
	"\x11print_backgrounds\x18\x17 \x01(\bR\x10printBackgrounds\x122\n" +
	"\x15should_print_comments\x18\x18 \x01(\bR\x13shouldPrintComments\"C\n" +
	"\x1bSheetStylePropertiesArchive\x12$\n" +
	"\x04fill\x18\x01 \x01(\v2\x10.TSD.FillArchiveR\x04fill\"\xaf\x01\n" +
	"\x11SheetStyleArchive\x12'\n" +
	"\x05super\x18\x01 \x02(\v2\x11.TSS.StyleArchiveR\x05super\x12%\n" +
	"\x0eoverride_count\x18\x02 \x01(\rR\roverrideCount\x12J\n" +
	"\x10sheet_properties\x18\x03 \x01(\v2\x1f.TN.SheetStylePropertiesArchiveR\x0fsheetProperties\"n\n" +
	"\x15FormBasedSheetArchive\x12&\n" +
	"\x05super\x18\x01 \x02(\v2\x10.TN.SheetArchiveR\x05super\x12-\n" +
	"\btable_id\x18\x02 \x01(\v2\x12.TSP.CFUUIDArchiveR\atableId\"g\n" +
	"\fThemeArchive\x12'\n" +
	"\x05super\x18\x01 \x02(\v2\x11.TSS.ThemeArchiveR\x05super\x12.\n" +
	"\n" +
	"prototypes\x18\x02 \x03(\v2\x0e.TSP.ReferenceR\n" +
	"prototypes\"z\n" +
	"\x1ePasteboardNativeStorageArchive\x12$\n" +
	"\x05sheet\x18\x01 \x01(\v2\x0e.TSP.ReferenceR\x05sheet\x122\n" +
	"\bui_state\x18\x02 \x01(\v2\x17.TN.SheetUIStateArchiveR\auiState\"\xfc\x04\n" +
	"\x1bChartMediatorFormulaStorage\x129\n" +
	"\rdata_formulae\x18\x01 \x03(\v2\x14.TSCE.FormulaArchiveR\fdataFormulae\x12B\n" +
	"\x12row_label_formulae\x18\x03 \x03(\v2\x14.TSCE.FormulaArchiveR\x10rowLabelFormulae\x12B\n" +
	"\x12col_label_formulae\x18\x04 \x03(\v2\x14.TSCE.FormulaArchiveR\x10colLabelFormulae\x12\x1c\n" +
	"\tdirection\x18\x05 \x01(\x05R\tdirection\x12O\n" +
	"\x19error_custom_pos_formulae\x18\x06 \x03(\v2\x14.TSCE.FormulaArchiveR\x16errorCustomPosFormulae\x12O\n" +
	"\x19error_custom_neg_formulae\x18\a \x03(\v2\x14.TSCE.FormulaArchiveR\x16errorCustomNegFormulae\x12`\n" +
	"\"error_custom_pos_scatterX_formulae\x18\b \x03(\v2\x14.TSCE.FormulaArchiveR\x1eerrorCustomPosScatterXFormulae\x12`\n" +
	"\"error_custom_neg_scatterX_formulae\x18\t \x03(\v2\x14.TSCE.FormulaArchiveR\x1eerrorCustomNegScatterXFormulae\x12\x16\n" +
	"\x06scheme\x18\n" +
	" \x01(\x05R\x06scheme\"\x94\x02\n" +
	"\x14ChartMediatorArchive\x120\n" +
	"\x05super\x18\x01 \x02(\v2\x1a.TSCH.ChartMediatorArchiveR\x05super\x12\x1b\n" +
	"\tentity_id\x18\x02 \x02(\tR\bentityId\x12;\n" +
	"\bformulas\x18\x03 \x01(\v2\x1f.TN.ChartMediatorFormulaStorageR\bformulas\x12,\n" +
	"\x12columns_are_series\x18\x04 \x01(\bR\x10columnsAreSeries\x12B\n" +
	"\x1eis_registered_with_calc_engine\x18\x05 \x01(\bR\x1aisRegisteredWithCalcEngine\"\xf5\x01\n" +
	"\x15ChartSelectionArchive\x129\n" +
	"\treference\x18\x01 \x01(\v2\x1b.TSCE.RangeReferenceArchiveR\treference\x12F\n" +
	"\x10deprecated_super\x18\x02 \x01(\v2\x1b.TSCH.ChartSelectionArchiveR\x0fdeprecatedSuper\x12$\n" +
	"\x05chart\x18\x03 \x01(\v2\x0e.TSP.ReferenceR\x05chart\x123\n" +
	"\x05super\x18\x04 \x01(\v2\x1d.TSD.DrawableSelectionArchiveR\x05super\"`\n" +
	"\"FormCommandActivityBehaviorArchive\x12:\n" +
	"\x05super\x18\x01 \x02(\v2$.TSCK.CommandActivityBehaviorArchiveR\x05super*?\n" +
	"\tPageOrder\x12\x18\n" +
	"\x14PageOrderTopToBottom\x10\x00\x12\x18\n" +
	"\x14PageOrderLeftToRight\x10\x01*]\n" +
	"\x13PageLayoutDirection\x12\"\n" +
	"\x1ePageLayoutDirectionLeftToRight\x10\x00\x12\"\n" +
	"\x1ePageLayoutDirectionRightToLeft\x10\x01B.Z,github.com/orcastor/iwork-converter/proto/TN"

var (
	file_TNArchives_proto_rawDescOnce sync.Once
	file_TNArchives_proto_rawDescData []byte
)

func file_TNArchives_proto_rawDescGZIP() []byte {
	file_TNArchives_proto_rawDescOnce.Do(func() {
		file_TNArchives_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_TNArchives_proto_rawDesc), len(file_TNArchives_proto_rawDesc)))
	})
	return file_TNArchives_proto_rawDescData
}

var file_TNArchives_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_TNArchives_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_TNArchives_proto_goTypes = []any{
	(PageOrder)(0),                              // 0: TN.PageOrder
	(PageLayoutDirection)(0),                    // 1: TN.PageLayoutDirection
	(UIStateArchive_InspectorPaneViewMode)(0),   // 2: TN.UIStateArchive.InspectorPaneViewMode
	(*SheetUIStateArchive)(nil),                 // 3: TN.SheetUIStateArchive
	(*SheetUIStateDictionaryEntryArchive)(nil),  // 4: TN.SheetUIStateDictionaryEntryArchive
	(*UUIDSheetUIStateDictionaryArchive)(nil),   // 5: TN.UUIDSheetUIStateDictionaryArchive
	(*UIStateArchive)(nil),                      // 6: TN.UIStateArchive
	(*SheetSelectionArchive)(nil),               // 7: TN.SheetSelectionArchive
	(*FormSelectionArchive)(nil),                // 8: TN.FormSelectionArchive
	(*FormBuilderSelectionArchive)(nil),         // 9: TN.FormBuilderSelectionArchive
	(*FormTableChooserSelectionArchive)(nil),    // 10: TN.FormTableChooserSelectionArchive
	(*UndoRedoStateArchive)(nil),                // 11: TN.UndoRedoStateArchive
	(*DocumentArchive)(nil),                     // 12: TN.DocumentArchive
	(*PlaceholderArchive)(nil),                  // 13: TN.PlaceholderArchive
	(*SheetArchive)(nil),                        // 14: TN.SheetArchive
	(*SheetStylePropertiesArchive)(nil),         // 15: TN.SheetStylePropertiesArchive
	(*SheetStyleArchive)(nil),                   // 16: TN.SheetStyleArchive
	(*FormBasedSheetArchive)(nil),               // 17: TN.FormBasedSheetArchive
	(*ThemeArchive)(nil),                        // 18: TN.ThemeArchive
	(*PasteboardNativeStorageArchive)(nil),      // 19: TN.PasteboardNativeStorageArchive
	(*ChartMediatorFormulaStorage)(nil),         // 20: TN.ChartMediatorFormulaStorage
	(*ChartMediatorArchive)(nil),                // 21: TN.ChartMediatorArchive
	(*ChartSelectionArchive)(nil),               // 22: TN.ChartSelectionArchive
	(*FormCommandActivityBehaviorArchive)(nil),  // 23: TN.FormCommandActivityBehaviorArchive
	(*TSP.Point)(nil),                           // 24: TSP.Point
	(*TSP.Size)(nil),                            // 25: TSP.Size
	(*TSK.SelectionPathArchive)(nil),            // 26: TSK.SelectionPathArchive
	(*TSP.Reference)(nil),                       // 27: TSP.Reference
	(*TSP.UUID)(nil),                            // 28: TSP.UUID
	(*TST.SelectionArchive)(nil),                // 29: TST.SelectionArchive
	(*TSCH.ChartUIState)(nil),                   // 30: TSCH.ChartUIState
	(*TSA.DocumentArchive)(nil),                 // 31: TSA.DocumentArchive
	(*TSWP.ShapeInfoArchive)(nil),               // 32: TSWP.ShapeInfoArchive
	(*TSD.EdgeInsetsArchive)(nil),               // 33: TSD.EdgeInsetsArchive
	(*TSD.FillArchive)(nil),                     // 34: TSD.FillArchive
	(*TSS.StyleArchive)(nil),                    // 35: TSS.StyleArchive
	(*TSP.CFUUIDArchive)(nil),                   // 36: TSP.CFUUIDArchive
	(*TSS.ThemeArchive)(nil),                    // 37: TSS.ThemeArchive
	(*TSCE.FormulaArchive)(nil),                 // 38: TSCE.FormulaArchive
	(*TSCH.ChartMediatorArchive)(nil),           // 39: TSCH.ChartMediatorArchive
	(*TSCE.RangeReferenceArchive)(nil),          // 40: TSCE.RangeReferenceArchive
	(*TSCH.ChartSelectionArchive)(nil),          // 41: TSCH.ChartSelectionArchive
	(*TSD.DrawableSelectionArchive)(nil),        // 42: TSD.DrawableSelectionArchive
	(*TSCK.CommandActivityBehaviorArchive)(nil), // 43: TSCK.CommandActivityBehaviorArchive
}
var file_TNArchives_proto_depIdxs = []int32{
	24, // 0: TN.SheetUIStateArchive.scroll_position:type_name -> TSP.Point
	24, // 1: TN.SheetUIStateArchive.previous_scroll_position:type_name -> TSP.Point
	25, // 2: TN.SheetUIStateArchive.visible_size:type_name -> TSP.Size
	25, // 3: TN.SheetUIStateArchive.previous_visible_size:type_name -> TSP.Size
	26, // 4: TN.SheetUIStateArchive.selection_path:type_name -> TSK.SelectionPathArchive
	27, // 5: TN.SheetUIStateArchive.selection_path_transformer:type_name -> TSP.Reference
	27, // 6: TN.SheetUIStateDictionaryEntryArchive.sheet:type_name -> TSP.Reference
	3,  // 7: TN.SheetUIStateDictionaryEntryArchive.sheet_uistate:type_name -> TN.SheetUIStateArchive
	28, // 8: TN.UUIDSheetUIStateDictionaryArchive.sheet_uuid:type_name -> TSP.UUID
	3,  // 9: TN.UUIDSheetUIStateDictionaryArchive.sheet_uistate:type_name -> TN.SheetUIStateArchive
	27, // 10: TN.UIStateArchive.selected_info:type_name -> TSP.Reference
	4,  // 11: TN.UIStateArchive.sheet_uistate_dictionary_entry:type_name -> TN.SheetUIStateDictionaryEntryArchive
	29, // 12: TN.UIStateArchive.table_selection:type_name -> TST.SelectionArchive
	4,  // 13: TN.UIStateArchive.edit_mode_sheet_uistate_dictionary_entry:type_name -> TN.SheetUIStateDictionaryEntryArchive
	22, // 14: TN.UIStateArchive.chart_selection:type_name -> TN.ChartSelectionArchive
	27, // 15: TN.UIStateArchive.sheet_selection:type_name -> TSP.Reference
	2,  // 16: TN.UIStateArchive.inspector_pane_view_mode:type_name -> TN.UIStateArchive.InspectorPaneViewMode
	24, // 17: TN.UIStateArchive.desktop_window_origin:type_name -> TSP.Point
	25, // 18: TN.UIStateArchive.desktop_window_size:type_name -> TSP.Size
	25, // 19: TN.UIStateArchive.desktop_screen_size:type_name -> TSP.Size
	30, // 20: TN.UIStateArchive.chart_ui_state:type_name -> TSCH.ChartUIState
	26, // 21: TN.UIStateArchive.selection_path:type_name -> TSK.SelectionPathArchive
	5,  // 22: TN.UIStateArchive.uuid_sheet_uistate_dictionary:type_name -> TN.UUIDSheetUIStateDictionaryArchive
	27, // 23: TN.UIStateArchive.freehand_drawing_toolkit_state:type_name -> TSP.Reference
	27, // 24: TN.UIStateArchive.selection_path_transformer:type_name -> TSP.Reference
	27, // 25: TN.SheetSelectionArchive.sheet:type_name -> TSP.Reference
	6,  // 26: TN.UndoRedoStateArchive.ui_state:type_name -> TN.UIStateArchive
	27, // 27: TN.DocumentArchive.sheets:type_name -> TSP.Reference
	31, // 28: TN.DocumentArchive.super:type_name -> TSA.DocumentArchive
	27, // 29: TN.DocumentArchive.calculation_engine:type_name -> TSP.Reference
	27, // 30: TN.DocumentArchive.stylesheet:type_name -> TSP.Reference
	27, // 31: TN.DocumentArchive.sidebar_order:type_name -> TSP.Reference
	27, // 32: TN.DocumentArchive.theme:type_name -> TSP.Reference
	6,  // 33: TN.DocumentArchive.uistate:type_name -> TN.UIStateArchive
	27, // 34: TN.DocumentArchive.custom_format_list:type_name -> TSP.Reference
	25, // 35: TN.DocumentArchive.page_size:type_name -> TSP.Size
	32, // 36: TN.PlaceholderArchive.super:type_name -> TSWP.ShapeInfoArchive
	27, // 37: TN.SheetArchive.drawable_infos:type_name -> TSP.Reference
	0,  // 38: TN.SheetArchive.page_order:type_name -> TN.PageOrder
	33, // 39: TN.SheetArchive.print_margins:type_name -> TSD.EdgeInsetsArchive
	27, // 40: TN.SheetArchive.header_storage:type_name -> TSP.Reference
	27, // 41: TN.SheetArchive.footer_storage:type_name -> TSP.Reference
	27, // 42: TN.SheetArchive.userDefinedGuideStorage:type_name -> TSP.Reference
	27, // 43: TN.SheetArchive.headers:type_name -> TSP.Reference
	27, // 44: TN.SheetArchive.footers:type_name -> TSP.Reference
	1,  // 45: TN.SheetArchive.layout_direction:type_name -> TN.PageLayoutDirection
	27, // 46: TN.SheetArchive.style:type_name -> TSP.Reference
	34, // 47: TN.SheetStylePropertiesArchive.fill:type_name -> TSD.FillArchive
	35, // 48: TN.SheetStyleArchive.super:type_name -> TSS.StyleArchive
	15, // 49: TN.SheetStyleArchive.sheet_properties:type_name -> TN.SheetStylePropertiesArchive
	14, // 50: TN.FormBasedSheetArchive.super:type_name -> TN.SheetArchive
	36, // 51: TN.FormBasedSheetArchive.table_id:type_name -> TSP.CFUUIDArchive
	37, // 52: TN.ThemeArchive.super:type_name -> TSS.ThemeArchive
	27, // 53: TN.ThemeArchive.prototypes:type_name -> TSP.Reference
	27, // 54: TN.PasteboardNativeStorageArchive.sheet:type_name -> TSP.Reference
	3,  // 55: TN.PasteboardNativeStorageArchive.ui_state:type_name -> TN.SheetUIStateArchive
	38, // 56: TN.ChartMediatorFormulaStorage.data_formulae:type_name -> TSCE.FormulaArchive
	38, // 57: TN.ChartMediatorFormulaStorage.row_label_formulae:type_name -> TSCE.FormulaArchive
	38, // 58: TN.ChartMediatorFormulaStorage.col_label_formulae:type_name -> TSCE.FormulaArchive
	38, // 59: TN.ChartMediatorFormulaStorage.error_custom_pos_formulae:type_name -> TSCE.FormulaArchive
	38, // 60: TN.ChartMediatorFormulaStorage.error_custom_neg_formulae:type_name -> TSCE.FormulaArchive
	38, // 61: TN.ChartMediatorFormulaStorage.error_custom_pos_scatterX_formulae:type_name -> TSCE.FormulaArchive
	38, // 62: TN.ChartMediatorFormulaStorage.error_custom_neg_scatterX_formulae:type_name -> TSCE.FormulaArchive
	39, // 63: TN.ChartMediatorArchive.super:type_name -> TSCH.ChartMediatorArchive
	20, // 64: TN.ChartMediatorArchive.formulas:type_name -> TN.ChartMediatorFormulaStorage
	40, // 65: TN.ChartSelectionArchive.reference:type_name -> TSCE.RangeReferenceArchive
	41, // 66: TN.ChartSelectionArchive.deprecated_super:type_name -> TSCH.ChartSelectionArchive
	27, // 67: TN.ChartSelectionArchive.chart:type_name -> TSP.Reference
	42, // 68: TN.ChartSelectionArchive.super:type_name -> TSD.DrawableSelectionArchive
	43, // 69: TN.FormCommandActivityBehaviorArchive.super:type_name -> TSCK.CommandActivityBehaviorArchive
	70, // [70:70] is the sub-list for method output_type
	70, // [70:70] is the sub-list for method input_type
	70, // [70:70] is the sub-list for extension type_name
	70, // [70:70] is the sub-list for extension extendee
	0,  // [0:70] is the sub-list for field type_name
}

func init() { file_TNArchives_proto_init() }
func file_TNArchives_proto_init() {
	if File_TNArchives_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_TNArchives_proto_rawDesc), len(file_TNArchives_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TNArchives_proto_goTypes,
		DependencyIndexes: file_TNArchives_proto_depIdxs,
		EnumInfos:         file_TNArchives_proto_enumTypes,
		MessageInfos:      file_TNArchives_proto_msgTypes,
	}.Build()
	File_TNArchives_proto = out.File
	file_TNArchives_proto_goTypes = nil
	file_TNArchives_proto_depIdxs = nil
}
