// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: TNCommandArchives.sos.proto

package TN

import (
	TSA "github.com/orcastor/iwork-converter/proto/TSA"
	TSK "github.com/orcastor/iwork-converter/proto/TSK"
	TSP "github.com/orcastor/iwork-converter/proto/TSP"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InducedVerifyDocumentWithServerCommandArchive struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Super                *TSK.CommandArchive    `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	SheetIdList          []*TSP.UUID            `protobuf:"bytes,2,rep,name=sheet_id_list,json=sheetIdList" json:"sheet_id_list,omitempty"`
	SheetIdListUndefined *bool                  `protobuf:"varint,3,opt,name=sheet_id_list_undefined,json=sheetIdListUndefined" json:"sheet_id_list_undefined,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *InducedVerifyDocumentWithServerCommandArchive) Reset() {
	*x = InducedVerifyDocumentWithServerCommandArchive{}
	mi := &file_TNCommandArchives_sos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InducedVerifyDocumentWithServerCommandArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InducedVerifyDocumentWithServerCommandArchive) ProtoMessage() {}

func (x *InducedVerifyDocumentWithServerCommandArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TNCommandArchives_sos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InducedVerifyDocumentWithServerCommandArchive.ProtoReflect.Descriptor instead.
func (*InducedVerifyDocumentWithServerCommandArchive) Descriptor() ([]byte, []int) {
	return file_TNCommandArchives_sos_proto_rawDescGZIP(), []int{0}
}

func (x *InducedVerifyDocumentWithServerCommandArchive) GetSuper() *TSK.CommandArchive {
	if x != nil {
		return x.Super
	}
	return nil
}

func (x *InducedVerifyDocumentWithServerCommandArchive) GetSheetIdList() []*TSP.UUID {
	if x != nil {
		return x.SheetIdList
	}
	return nil
}

func (x *InducedVerifyDocumentWithServerCommandArchive) GetSheetIdListUndefined() bool {
	if x != nil && x.SheetIdListUndefined != nil {
		return *x.SheetIdListUndefined
	}
	return false
}

type InducedVerifyDrawableZOrdersWithServerCommandArchive struct {
	state         protoimpl.MessageState                                    `protogen:"open.v1"`
	Super         *TSA.InducedVerifyDrawableZOrdersWithServerCommandArchive `protobuf:"bytes,1,req,name=super" json:"super,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InducedVerifyDrawableZOrdersWithServerCommandArchive) Reset() {
	*x = InducedVerifyDrawableZOrdersWithServerCommandArchive{}
	mi := &file_TNCommandArchives_sos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InducedVerifyDrawableZOrdersWithServerCommandArchive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InducedVerifyDrawableZOrdersWithServerCommandArchive) ProtoMessage() {}

func (x *InducedVerifyDrawableZOrdersWithServerCommandArchive) ProtoReflect() protoreflect.Message {
	mi := &file_TNCommandArchives_sos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InducedVerifyDrawableZOrdersWithServerCommandArchive.ProtoReflect.Descriptor instead.
func (*InducedVerifyDrawableZOrdersWithServerCommandArchive) Descriptor() ([]byte, []int) {
	return file_TNCommandArchives_sos_proto_rawDescGZIP(), []int{1}
}

func (x *InducedVerifyDrawableZOrdersWithServerCommandArchive) GetSuper() *TSA.InducedVerifyDrawableZOrdersWithServerCommandArchive {
	if x != nil {
		return x.Super
	}
	return nil
}

var File_TNCommandArchives_sos_proto protoreflect.FileDescriptor

const file_TNCommandArchives_sos_proto_rawDesc = "" +
	"\n" +
	"\x1bTNCommandArchives.sos.proto\x12\x02TN\x1a\x1cTSACommandArchives.sos.proto\x1a\x11TSKArchives.proto\x1a\x11TSPMessages.proto\"\xc0\x01\n" +
	"-InducedVerifyDocumentWithServerCommandArchive\x12)\n" +
	"\x05super\x18\x01 \x02(\v2\x13.TSK.CommandArchiveR\x05super\x12-\n" +
	"\rsheet_id_list\x18\x02 \x03(\v2\t.TSP.UUIDR\vsheetIdList\x125\n" +
	"\x17sheet_id_list_undefined\x18\x03 \x01(\bR\x14sheetIdListUndefined\"\x87\x01\n" +
	"4InducedVerifyDrawableZOrdersWithServerCommandArchive\x12O\n" +
	"\x05super\x18\x01 \x02(\v29.TSA.InducedVerifyDrawableZOrdersWithServerCommandArchiveR\x05superB.Z,github.com/orcastor/iwork-converter/proto/TN"

var (
	file_TNCommandArchives_sos_proto_rawDescOnce sync.Once
	file_TNCommandArchives_sos_proto_rawDescData []byte
)

func file_TNCommandArchives_sos_proto_rawDescGZIP() []byte {
	file_TNCommandArchives_sos_proto_rawDescOnce.Do(func() {
		file_TNCommandArchives_sos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_TNCommandArchives_sos_proto_rawDesc), len(file_TNCommandArchives_sos_proto_rawDesc)))
	})
	return file_TNCommandArchives_sos_proto_rawDescData
}

var file_TNCommandArchives_sos_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_TNCommandArchives_sos_proto_goTypes = []any{
	(*InducedVerifyDocumentWithServerCommandArchive)(nil),            // 0: TN.InducedVerifyDocumentWithServerCommandArchive
	(*InducedVerifyDrawableZOrdersWithServerCommandArchive)(nil),     // 1: TN.InducedVerifyDrawableZOrdersWithServerCommandArchive
	(*TSK.CommandArchive)(nil),                                       // 2: TSK.CommandArchive
	(*TSP.UUID)(nil),                                                 // 3: TSP.UUID
	(*TSA.InducedVerifyDrawableZOrdersWithServerCommandArchive)(nil), // 4: TSA.InducedVerifyDrawableZOrdersWithServerCommandArchive
}
var file_TNCommandArchives_sos_proto_depIdxs = []int32{
	2, // 0: TN.InducedVerifyDocumentWithServerCommandArchive.super:type_name -> TSK.CommandArchive
	3, // 1: TN.InducedVerifyDocumentWithServerCommandArchive.sheet_id_list:type_name -> TSP.UUID
	4, // 2: TN.InducedVerifyDrawableZOrdersWithServerCommandArchive.super:type_name -> TSA.InducedVerifyDrawableZOrdersWithServerCommandArchive
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_TNCommandArchives_sos_proto_init() }
func file_TNCommandArchives_sos_proto_init() {
	if File_TNCommandArchives_sos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_TNCommandArchives_sos_proto_rawDesc), len(file_TNCommandArchives_sos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_TNCommandArchives_sos_proto_goTypes,
		DependencyIndexes: file_TNCommandArchives_sos_proto_depIdxs,
		MessageInfos:      file_TNCommandArchives_sos_proto_msgTypes,
	}.Build()
	File_TNCommandArchives_sos_proto = out.File
	file_TNCommandArchives_sos_proto_goTypes = nil
	file_TNCommandArchives_sos_proto_depIdxs = nil
}
